### ISSUE TITLE
registry config problem

### ISSUE THREAD

**Issue by wrfly** [docker/distribution#2464] opened 2017-12-06 06:37 UTC
If I set an env config, registry won't parse the config in my config file.

env config:
```
      REGISTRY_STORAGE: s3
      REGISTRY_STORAGE_S3_ACCESSKEY: ${REGISTRY_STORAGE_S3_ACCESSKEY}
      REGISTRY_STORAGE_S3_SECRETKEY: ${REGISTRY_STORAGE_S3_SECRETKEY}
      REGISTRY_STORAGE_S3_BUCKET: ${REGISTRY_STORAGE_S3_BUCKET}
      REGISTRY_STORAGE_S3_REGION: ${REGISTRY_STORAGE_S3_REGION}
#      REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR: redis
```

config file:
```
version: 0.1
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
  cache:
    blobdescriptor: redis
http:
  addr: 0.0.0.0:5000
  debug:
    addr: 0.0.0.0:5001
redis:
  addr: redis:6379

```

If I turn on the comment, the registry will not use redis as its blob descriptor:

```
registry_1  | time="2017-12-06T06:32:34Z" level=info msg="Starting upload purge in 53m0s" go.version=go1.7.6 instance.id=d2ee585b-e082-4d4c-a435-bd62a8711af9 version=v2.6.2
registry_1  | time="2017-12-06T06:32:34Z" level=info msg="listening on [::]:5000, tls" go.version=go1.7.6 instance.id=d2ee585b-e082-4d4c-a435-bd62a8711af9 version=v2.6.2
```

If I turn off the comment, it works:

```
registry_1  | time="2017-12-06T06:27:48Z" level=info msg="Starting upload purge in 58m0s" go.version=go1.7.6 instance.id=b96d0204-25b2-4c1f-bbba-1007ea47aa5e version=v2.6.2
registry_1  | time="2017-12-06T06:27:48Z" level=info msg="using redis blob descriptor cache" go.version=go1.7.6 instance.id=b96d0204-25b2-4c1f-bbba-1007ea47aa5e version=v2.6.2
registry_1  | time="2017-12-06T06:27:48Z" level=info msg="listening on [::]:5000, tls" go.version=go1.7.6 instance.id=b96d0204-25b2-4c1f-bbba-1007ea47aa5e version=v2.6.2
```

~~But interestingly, registry use the `delete.enable` part and ignored the `cache`.~~

**Comment by wrfly** [comment] 2017-12-06 06:48
docker version: 
```
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:37:39 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:36:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

registry version:
```
/ # registry -v
registry github.com/docker/distribution v2.6.2
/ #
```

**Comment by wrfly** [comment] 2017-12-07 01:55
I'm still working on this, although it's a little hard for me. I thought it's a defects of designation.

https://github.com/docker/distribution/blob/bc3c7b0525e59d3ecfab3e1568350895fd4a462f/configuration/parser.go#L204

```golang
	if len(path) == 1 {
		// Env var specifies this field directly
		fieldVal := reflect.New(sf.Type)
		err := yaml.Unmarshal([]byte(payload), fieldVal.Interface())
		if err != nil {
			return err
		}
		field.Set(reflect.Indirect(fieldVal))
		return nil
}
```

Since the struct may has  sub-structs, we can not simply overwrite this struct via `field.Set()`.
Maybe I can use a `switch` to check whether the `struct` is `Storage`.
Working on this...

**Comment by dmp42** [comment] 2018-03-21 16:49
@wrfly I don't understand the issue here.
If you want to use env variables, you should set the redis address as well.

Am I missing something?

**Comment by wrfly** [comment] 2018-03-21 17:08
@dmp42 Yep, maybe I didn't explain it well...
The problem here is that the config parsed from env overwrited the whole config parsed from file. It will not work if I set redis address to the env either. In this case, the config parser 'eat' the 
```
  cache:
    blobdescriptor: redis
```
in the config file since I passed an `REGISTRY_STORAGE: s3` to it. This shouldn't happen because I still want to use redis as my `blobdescriptor`. So I have to add another env config `REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR` to let the parser set it again.

It's not very serious but truly a bug.

Sorry about my poor English, hope you can understand...

**Comment by dmp42** [comment] 2018-03-21 17:17
@wrfly understood your point.
This is by design though.

If it wouldn't work like that, there would be no way to wipe out a config branch from the environment, and you could end-up with unexpected results with conflicting configuration.

I don't think we can accept this PR for this reason...

Hope that makes sense ^.

Thanks.

**Comment by wrfly** [comment] 2018-03-21 17:39
I see. Thanks for your explanation. I thought it was a combination of these configs at first.
Or maybe there should be a priority for configurations parsed via different ways, so I can wipe out the config.

I'll test if the `delete: enable: true` works or not tomorrow, too late today~ If that works, I thought the design didn't wipe the whole configs of that part.

Good night~

**Comment by wrfly** [comment] 2018-03-22 02:33
It does overwrite the `delete: enable: true` config. I'll accept it since you said it's by design, but I still think it's better if the config is a combination, because I can set the default to config file and overwrite it by pass some env configs.

**Comment by stevvooe** [comment] 2018-03-22 15:09
> It does overwrite the delete: enable: true config

Could you write out the example with the exact env variables and state of the config, step by step?

**Comment by wrfly** [comment] 2018-03-23 02:01
@stevvooe  config file:

```
version: 0.1
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
```

With env:
```
      REGISTRY_STORAGE: s3
      REGISTRY_STORAGE_S3_ACCESSKEY: ${REGISTRY_STORAGE_S3_ACCESSKEY}
      REGISTRY_STORAGE_S3_SECRETKEY: ${REGISTRY_STORAGE_S3_SECRETKEY}
      REGISTRY_STORAGE_S3_BUCKET: ${REGISTRY_STORAGE_S3_BUCKET}
      REGISTRY_STORAGE_S3_REGION: ${REGISTRY_STORAGE_S3_REGION}
```

This combination can not delete image.

Append this env will enable it: `REGISTRY_STORAGE_DELETE_ENABLED: "true"`

**Comment by dmp42** [comment] 2018-05-26 01:46
@wrfly indeed: `REGISTRY_STORAGE: s3` in the env will "wipe/ignore" anything under the `storage` key in the config file.
Albeit this may be confusing if you expect the env to be "deep merged" into the config, this behavior is by design, and not doing this would be quite problematic.

I'm going to close this for now. Please say so if you think this should be reopened.

**Closed by dmp42** 2018-05-26 01:46 UTC

**Comment by wrfly** [comment] 2018-05-26 06:53
@dmp42 Hi, can you give more details about this "design"? And what problem if merge these two configurations?
Thanks.

**Comment by dubo-dubon-duponey** [comment] 2018-05-26 07:02
@wrfly it's really as simple as

 * configuration tree
 * any key specified in the environment will override / wipe the corresponding subtree in the config

The problem if you "merge" this config file: 

```
version: 0.1
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
```


with this environment:

```
      REGISTRY_STORAGE: s3
      REGISTRY_STORAGE_S3_ACCESSKEY: ${REGISTRY_STORAGE_S3_ACCESSKEY}
      REGISTRY_STORAGE_S3_SECRETKEY: ${REGISTRY_STORAGE_S3_SECRETKEY}
      REGISTRY_STORAGE_S3_BUCKET: ${REGISTRY_STORAGE_S3_BUCKET}
      REGISTRY_STORAGE_S3_REGION: ${REGISTRY_STORAGE_S3_REGION}
```

is that the end result is this config tree:


```
version: 0.1
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  s3:
    accesskey: foo
    secretkey: foo
    bucket: foo
    region foo
  delete:
    enabled: true
```

And now you have two different backends configured, and there is no way to decide which one is the one you want.

**Comment by wrfly** [comment] 2018-05-26 07:05
@dubo-dubon-duponey Hi, in my PR, I put environment config in the first place, so in your example, it will be:

```
version: 0.1
storage:
  s3:
    accesskey: foo
    secretkey: foo
    bucket: foo
    region foo
  delete:
    enabled: true
```

**Comment by dubo-dubon-duponey** [comment] 2018-05-26 07:12
@wrfly the order doesn't matter - if you "merge", you still end-up with multiple (conflicting) backend declarations.

**Comment by wrfly** [comment] 2018-05-26 07:48
@dubo-dubon-duponey In my practice, there is no conflicts at all.

```
➜  bin git:(master) cat config.yml                                                                                                 
version: 0.1
storage:
  cache:
    blobdescriptor: inmemory
  s3:
    accesskey: foo
    secretkey: foo
    bucket: foo
    region: us-west-1
  delete:
    enabled: true
log:
  level: debug
http:
  addr: localhost:5000
➜  bin git:(master) REGISTRY_STORAGE=filesystem  REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/tmp/r ./registry-wrfly serve config.yml
WARN[0000] No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable.  go.version=go1.9.2 instance.id=8b6b7f5c-36c9-4374-9bd0-62ab8f48a20d version=v2.6.0-rc.1-241-g7c511506
INFO[0000] redis not configured                          go.version=go1.9.2 instance.id=8b6b7f5c-36c9-4374-9bd0-62ab8f48a20d version=v2.6.0-rc.1-241-g7c511506
INFO[0000] Starting upload purge in 12m0s                go.version=go1.9.2 instance.id=8b6b7f5c-36c9-4374-9bd0-62ab8f48a20d version=v2.6.0-rc.1-241-g7c511506
INFO[0000] listening on 127.0.0.1:5000                   go.version=go1.9.2 instance.id=8b6b7f5c-36c9-4374-9bd0-62ab8f48a20d version=v2.6.0-rc.1-241-g7c511506

```

```
➜  ~ rm /tmp/r -rf
➜  ~ docker push localhost:5000/busybox
The push refers to a repository [localhost:5000/busybox]
0314be9edf00: Pushed 
latest: digest: sha256:0b29c5182b3fa4c81ffac17702e362532730be4f7f762f32d1b98e0af56fab5e size: 527
➜  ~ ls /tmp/r/                   
docker
➜  ~ 
```

**Comment by dubo-dubon-duponey** [comment] 2018-05-26 08:06
@wrfly how do you deep merge, say, `notifications endpoints`? Or wipe a `reporting` section?

**Comment by wrfly** [comment] 2018-05-26 08:17
@dubo-dubon-duponey I can't, neither can the original `registry`, for now.

But if I were you, I would like to delete them in the config file.

Optionally, I can make this happen via setting some special character to delete that key, for example `_` .
