### ISSUE TITLE
No useful log in some error conditions

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#102] opened 2015-01-23 18:29 UTC
In conditions like #100 there seem to be no information available in the logs.

cc @jlhawn

**Comment by stevvooe** [comment] 2015-01-23 19:32
The logging situation is a little thin and #86 was filed to address this. Without modifying the registry, the error messages provided in the response should provide some insight.

Closing this a duplicate of #86.

**Closed by stevvooe** 2015-01-23 19:32 UTC
Labels: Bug, Duplicate, Urgent
