### ISSUE TITLE
Can an image be deleted from the registry?

### ISSUE THREAD

**Issue by drmalex07** [docker/distribution#1349] opened 2016-01-14 13:43 UTC
Am trying to setup a local registry running distribution/registry:2.2. My docker client/server are at 1.9.1.

I can successfully pull/push images to the registry, but i cannot delete unwanted images. Let's assume i have pushed a foo:1.5 image.

I issue `GET /v2/foo/manifests/1.5` and i obtain the image digest by looking at `Docker-Content-Digest` header's value.

I then issue a `DELETE /v2/foo/tags/<IMAGE-DIGEST>` and i receive a `202 Accepted` status. 
So, it reports that it was deleted, but if i issue a `GET /v2/foo/tags/list` the just-deleted image tag is present. Is this the expected behavior?

Moreover, if i try to re-push the image no actual layer seems to be uploaded. So, i think i can safely assume that all referenced BLOBs are all present (and storage size will continuously grow). Is there available any kind of garbage collection on actual BLOBs ?

**Comment by RichardScothern** [comment] 2016-01-14 18:44
@drmalex07 : Delete removes references to the image and makes them eliglible for garbage collection.   There are a couple of GC scripts out there, and we intend to choose and release an official one.

The fact that the image appears in the tag list is a bug which was fixed and will be available in the next release.

**Comment by drmalex07** [comment] 2016-01-14 23:00
@RichardScothern can you please point me to a garbage-collecting script that you think is mature enough to be used on a production site? I was only able to find relevant documentation for the "Trusted Registry".

**Comment by drmalex07** [comment] 2016-01-19 09:04
Any suggestions on this?

**Comment by RichardScothern** [comment] 2016-01-19 18:27
@drmalex07 : there is a discussion [here](https://github.com/docker/distribution/issues/462) and a link to a script.

**Comment by stevvooe** [comment] 2016-01-20 02:41
Duplicate of #1305.

**Closed by stevvooe** 2016-01-20 02:41 UTC
