### ISSUE TITLE
Memory leak with swift backend plus mirror

### ISSUE THREAD

**Issue by tdsparrow** [docker/distribution#1113] opened 2015-10-20 02:58 UTC
Setup a private registry with swift backend and mirror to official registry. Memory usage increased from ~400M till out of memory(4G system memory) in short time just before finish pulling image mysql from another client.

```
~# docker -v
Docker version 1.8.2, build 0a8c2e3
```

```
~# docker info
Containers: 4
Images: 23
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 31
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-40-generic
Operating System: Ubuntu precise (12.04.5 LTS)
CPUs: 2
Total Memory: 3.86 GiB
Name: lr-hub
ID: UJJD:QU63:UMBC:HLKC:OM65:KDDY:HCCQ:ADPF:MY6F:IVP5:ATMW:F4RN
WARNING: No swap limit support
```

```
# registry -version
registry github.com/docker/distribution v2.1.1
```

command to launch distribution:
```
#  docker run -p 5000:5000 -v /root/config.yml:/etc/docker/registry/config.yml --name registry registry:2
```
config.yml
```
version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory    
    swift:
        authurl: http://example.com/auth/v1.0
        username: tdsparrow
        password: *******
        container: docker-registry
http:
    addr: :5000
proxy:
    remoteurl: https://registry-1.docker.io
```

Backtrace:

```
fatal error: runtime: out of memory

runtime stack:
runtime.SysMap(0xc2d35d0000, 0x7e60000, 0xc208001c00, 0x10a59d8)
        /usr/src/go/src/runtime/mem_linux.c:149 +0x98
runtime.MHeap_SysAlloc(0x10ab0c0, 0x7e60000, 0x436052)
        /usr/src/go/src/runtime/malloc.c:284 +0x124
runtime.MHeap_Alloc(0x10ab0c0, 0x3f2c, 0x10100000000, 0x7f41fc)
        /usr/src/go/src/runtime/mheap.c:240 +0x66

goroutine 63 [running]:
runtime.switchtoM()
        /usr/src/go/src/runtime/asm_amd64.s:198 fp=0xc20871a9f0 sp=0xc20871a9e8
runtime.mallocgc(0x7e58000, 0x8ec220, 0x7f4b00000000, 0x30000c2d3508a20)
        /usr/src/go/src/runtime/malloc.go:199 +0x9f3 fp=0xc20871aaa0 sp=0xc20871a9f0
runtime.newarray(0x8ec220, 0xfcb000, 0xc2d3506f20)
        /usr/src/go/src/runtime/malloc.go:365 +0xc1 fp=0xc20871aad8 sp=0xc20871aaa0
runtime.growslice(0x8f2dc0, 0xc2aeb60000, 0xca2400, 0xca2400, 0x1, 0x0, 0x0, 0x0)
        /usr/src/go/src/runtime/slice.go:87 +0x2bb fp=0xc20871ab38 sp=0xc20871aad8
runtime.addtimerLocked(0xc2d3504808)
        /usr/src/go/src/runtime/time.go:98 +0xa8 fp=0xc20871abb0 sp=0xc20871ab38
runtime.addtimer(0xc2d3504808)
        /usr/src/go/src/runtime/time.go:84 +0x38 fp=0xc20871abc0 sp=0xc20871abb0
runtime.startTimer(0xc2d3504808)
        /usr/src/go/src/runtime/time.go:66 +0x28 fp=0xc20871abd0 sp=0xc20871abc0
time.NewTimer(0xd18c2e2800, 0x0)
        /usr/src/go/src/time/sleep.go:76 +0x12d fp=0xc20871ac28 sp=0xc20871abd0
time.After(0xd18c2e2800, 0xc2d34ddd50)
        /usr/src/go/src/time/sleep.go:110 +0x28 fp=0xc20871ac40 sp=0xc20871ac28
github.com/ncw/swift.(*timeoutReader).Read(0xc21f1f30a0, 0xc25927e000, 0x8000, 0x8012, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/ncw/swift/timeout_reader.go:44 +0x1af fp=0xc20871ad50 sp=0xc20871ac40
github.com/ncw/swift.(*ObjectOpenFile).Read(0xc25640c3f0, 0xc25927e000, 0x8000, 0x8012, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/ncw/swift/swift.go:1259 +0x78 fp=0xc20871ada0 sp=0xc20871ad50
io.(*teeReader).Read(0xc21f1f3420, 0xc25927e000, 0x8000, 0x8012, 0x1, 0x0, 0x0)
        /usr/src/go/src/io/io.go:495 +0x83 fp=0xc20871ae18 sp=0xc20871ada0
github.com/docker/distribution/registry/proxy.streamToClient(0x7f4b2ed49898, 0xc2080b4820, 0x7f4b2ed43d10, 0xc2081e8b90, 0xc20892cbe0, 0x18, 0x2378051, 0xc2084ccf6d, 0x47, 0x7f4b2ed59cb8, ...)
        /go/src/github.com/docker/distribution/registry/proxy/proxyblobstore.go:165 +0x337 fp=0xc20871af18 sp=0xc20871ae18
github.com/docker/distribution/registry/proxy.proxyBlobStore.ServeBlob(0x7f4b2ed443d8, 0xc2083104d0, 0x7f4b2ed444d0, 0xc2084b5540, 0xc208064360, 0x7f4b2ed49898, 0xc2080b4820, 0x7f4b2ed43d10, 0xc2081e8b90, 0xc2083065b0, ...)
        /go/src/github.com/docker/distribution/registry/proxy/proxyblobstore.go:81 +0x6fc fp=0xc20871b0c0 sp=0xc20871af18
github.com/docker/distribution/registry/proxy.(*proxyBlobStore).ServeBlob(0xc20810cb40, 0x7f4b2ed49898, 0xc2080b4820, 0x7f4b2ed43d10, 0xc2081e8b90, 0xc2083065b0, 0xc2084ccf6d, 0x47, 0x0, 0x0)
        <autogenerated>:2 +0x117 fp=0xc20871b138 sp=0xc20871b0c0
github.com/docker/distribution/notifications.(*blobServiceListener).ServeBlob(0xc2080b4a40, 0x7f4b2ed49898, 0xc2080b4820, 0x7f4b2ed43d10, 0xc2081e8b90, 0xc2083065b0, 0xc2084ccf6d, 0x47, 0x0, 0x0)
        /go/src/github.com/docker/distribution/notifications/listener.go:149 +0xcb fp=0xc20871b270 sp=0xc20871b138
github.com/docker/distribution/registry/handlers.(*blobHandler).GetBlob(0xc2080b4820, 0x7f4b2ed43d10, 0xc2081e8b90, 0xc2083065b0)
        /go/src/github.com/docker/distribution/registry/handlers/blob.go:64 +0x7c3 fp=0xc20871b408 sp=0xc20871b270
github.com/docker/distribution/registry/handlers.*blobHandler.GetBlob·fm(0x7f4b2ed43d10, 0xc2081e8b90, 0xc2083065b0)
        /go/src/github.com/docker/distribution/registry/handlers/blob.go:36 +0x45 fp=0xc20871b430 sp=0xc20871b408
net/http.HandlerFunc.ServeHTTP(0xc208159890, 0x7f4b2ed43d10, 0xc2081e8b90, 0xc2083065b0)
        /usr/src/go/src/net/http/server.go:1265 +0x41 fp=0xc20871b450 sp=0xc20871b430
github.com/gorilla/handlers.MethodHandler.ServeHTTP(0xc20810cc30, 0x7f4b2ed43d10, 0xc2081e8b90, 0xc2083065b0)
        /go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/gorilla/handlers/handlers.go:35 +0xbb fp=0xc20871b550 sp=0xc20871b450
github.com/docker/distribution/registry/handlers.func·008(0x7f4b2ed43d10, 0xc2081e8b90, 0xc2083065b0)
        /go/src/github.com/docker/distribution/registry/handlers/app.go:492 +0x1898 fp=0xc20871b828 sp=0xc20871b550
net/http.HandlerFunc.ServeHTTP(0xc208105240, 0x7f4b2ed43d10, 0xc2081e8b90, 0xc2083065b0)
        /usr/src/go/src/net/http/server.go:1265 +0x41 fp=0xc20871b848 sp=0xc20871b828
github.com/gorilla/mux.(*Router).ServeHTTP(0xc208038b90, 0x7f4b2ed43d10, 0xc2081e8b90, 0xc2083065b0)
        /go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x297 fp=0xc20871b950 sp=0xc20871b848
github.com/docker/distribution/registry/handlers.(*App).ServeHTTP(0xc208162000, 0x7f4b2ed43d10, 0xc2081e8b90, 0xc2083065b0)
        /go/src/github.com/docker/distribution/registry/handlers/app.go:430 +0x337 fp=0xc20871ba00 sp=0xc20871b950
main.func·002(0x7f4b2ed43b78, 0xc20821b3e0, 0xc2083065b0)
        /go/src/github.com/docker/distribution/cmd/registry/main.go:313 +0x77 fp=0xc20871ba40 sp=0xc20871ba00
net/http.HandlerFunc.ServeHTTP(0xc20814c780, 0x7f4b2ed43b78, 0xc20821b3e0, 0xc2083065b0)
        /usr/src/go/src/net/http/server.go:1265 +0x41 fp=0xc20871ba60 sp=0xc20871ba40
github.com/docker/distribution/health.func·003(0x7f4b2ed43b78, 0xc20821b3e0, 0xc2083065b0)
        /go/src/github.com/docker/distribution/health/health.go:223 +0x165 fp=0xc20871baf8 sp=0xc20871ba60
net/http.HandlerFunc.ServeHTTP(0xc20814c7a0, 0x7f4b2ed43b78, 0xc20821b3e0, 0xc2083065b0)
        /usr/src/go/src/net/http/server.go:1265 +0x41 fp=0xc20871bb18 sp=0xc20871baf8
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0x7f4b2ed3c2b0, 0xc208036008, 0x7f4b2ed3ca40, 0xc20814c7a0, 0x7f4b2ed439d8, 0xc2081cc780, 0xc2083065b0)
        /go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/gorilla/handlers/handlers.go:75 +0x11e fp=0xc20871bc70 sp=0xc20871bb18
github.com/gorilla/handlers.(*combinedLoggingHandler).ServeHTTP(0xc2081f5900, 0x7f4b2ed439d8, 0xc2081cc780, 0xc2083065b0)
        <autogenerated>:13 +0xbe fp=0xc20871bcb0 sp=0xc20871bc70
net/http.serverHandler.ServeHTTP(0xc2080f7aa0, 0x7f4b2ed439d8, 0xc2081cc780, 0xc2083065b0)
        /usr/src/go/src/net/http/server.go:1703 +0x19a fp=0xc20871bd08 sp=0xc20871bcb0
net/http.(*conn).serve(0xc2082ba640)
        /usr/src/go/src/net/http/server.go:1204 +0xb57 fp=0xc20871bfd8 sp=0xc20871bd08
runtime.goexit()
        /usr/src/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20871bfe0 sp=0xc20871bfd8
created by net/http.(*Server).Serve
        /usr/src/go/src/net/http/server.go:1751 +0x35e

goroutine 1 [IO wait, 4 minutes]:
net.(*pollDesc).Wait(0xc2081664c0, 0x72, 0x0, 0x0)
        /usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2081664c0, 0x0, 0x0)
        /usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208166460, 0x0, 0x7f4b2ed3c230, 0xc213552d50)
        /usr/src/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208036070, 0x4be0be, 0x0, 0x0)
        /usr/src/go/src/net/tcpsock_posix.go:234 +0x4e
github.com/docker/distribution/registry/listener.tcpKeepAliveListener.Accept(0xc208036070, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/distribution/registry/listener/listener.go:20 +0x4c
net/http.(*Server).Serve(0xc2080f7aa0, 0x7f4b2ed438b0, 0xc208036070, 0x0, 0x0)
        /usr/src/go/src/net/http/server.go:1728 +0x92
main.main()
        /go/src/github.com/docker/distribution/cmd/registry/main.go:145 +0x1990
......
```

**Comment by RichardScothern** [comment] 2015-10-22 00:44
hi @tdsparrow 

Can you test this with a more recent registry build?   (You can `docker pull distribution/registry:master`) - as the code above has changed quite a bit.

I tested this out with a registry cache configured with a swift all-in-one container and was not able to reproduce (memory usage always returned to  ~190MB) pulling `library/mysql` and a few other official images in parallel.

**Comment by tdsparrow** [comment] 2015-11-04 10:07
Sorry for late reply, I tested a recent registry build. No memory leak any more. Thanks for the help.

**Comment by thaJeztah** [comment] 2015-12-25 14:13
Looks like this issue can be closed; @tdsparrow can you close this issue?

**Closed** 2015-12-29 20:40 UTC
