### ISSUE TITLE
Upload to local repository fails with "Unsupported"

### ISSUE THREAD

**Issue by pnull** [docker/distribution#2018] opened 2016-10-24 15:41 UTC
### Problem

```
Oct 24 15:36:26 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:36:26.463579996Z" level=error msg="Upload failed, retrying: unsupported"
Oct 24 15:36:26 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:36:26.465285497Z" level=error msg="Upload failed, retrying: unsupported"
Oct 24 15:36:26 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:36:26.466413866Z" level=error msg="Upload failed, retrying: unsupported"
Oct 24 15:36:26 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:36:26.467805442Z" level=error msg="Upload failed, retrying: unsupported"
Oct 24 15:36:26 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:36:26.468811575Z" level=error msg="Upload failed, retrying: unsupported"
Oct 24 15:36:31 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:36:31.490990246Z" level=error msg="Upload failed, retrying: unsupported"
Oct 24 15:36:31 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:36:31.500045548Z" level=error msg="Upload failed, retrying: unsupported"
Oct 24 15:36:31 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:36:31.509348467Z" level=error msg="Upload failed, retrying: unsupported"
Oct 24 15:36:31 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:36:31.514694189Z" level=error msg="Upload failed, retrying: unsupported"
Oct 24 15:36:31 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:36:31.524318717Z" level=error msg="Upload failed, retrying: unsupported"
Oct 24 15:36:41 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:36:41.506033731Z" level=error msg="Upload failed, retrying: unsupported"
Oct 24 15:36:41 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:36:41.522244169Z" level=error msg="Upload failed, retrying: unsupported"
Oct 24 15:36:41 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:36:41.534779530Z" level=error msg="Upload failed, retrying: unsupported"
Oct 24 15:36:41 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:36:41.552401453Z" level=error msg="Upload failed, retrying: unsupported"
Oct 24 15:36:41 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:36:41.564145920Z" level=error msg="Upload failed, retrying: unsupported"
Oct 24 15:36:56 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:36:56.522683858Z" level=error msg="Upload failed, retrying: unsupported"
Oct 24 15:36:56 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:36:56.532205861Z" level=error msg="Upload failed, retrying: unsupported"
Oct 24 15:36:56 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:36:56.550170810Z" level=error msg="Upload failed, retrying: unsupported"
Oct 24 15:36:56 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:36:56.559562963Z" level=error msg="Upload failed, retrying: unsupported"
Oct 24 15:36:56 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:36:56.577182695Z" level=error msg="Upload failed, retrying: unsupported"
Oct 24 15:37:16 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:37:16.532180770Z" level=error msg="Upload failed: unsupported"
Oct 24 15:37:16 gitlab-ci-autoscale-runner dockerd[1255]: time="2016-10-24T15:37:16.533001313Z" level=error msg="Attempting next endpoint for push after error: unsupported"
```
### docker exec registry registry -v

```
registry github.com/docker/distribution v2.5.1
```

**Comment by RichardScothern** [comment] 2016-10-24 16:52
*Please follow these instructions to help us diagnose your issue*

 2. copy the output of:
   - `docker version`
   - `docker info`
   - `docker exec <registry-container> registry -version`
 3. copy the command line you used to launch your Registry
 4. restart your docker daemon in debug mode (add `-D` to the daemon launch arguments)
 5. reproduce your problem and get your docker daemon logs showing the error
 6. if relevant, copy your registry logs that show the error
 7. provide any relevant detail about your specific Registry configuration (e.g., storage backend used)
 8. indicate if you are using an enterprise proxy, Nginx, or anything else between you and your Registry

**Comment by stevvooe** [comment] 2017-07-18 21:22
@pnull I hope the troubleshooting information above was helpful. It looks like you have responded in some time, so I'm going to go ahead and close this issue.

**Closed by stevvooe** 2017-07-18 21:22 UTC
