### ISSUE TITLE
DIGEST_INVALID when pushing manifest in registry 2.5.1

### ISSUE THREAD

**Issue by pmalshe** [docker/distribution#2098] opened 2016-12-09 18:14 UTC
I am trying to transfer docker images from registry A to registry B (located across two sites). I am using registry notifications to receive event notification from registry A, then process and relay it with intermediate agent, and with the help of same agent, push blobs and manifests to remote registry B with registry API 2. I am using manifest V2 schema 2. Both registries are at version 2.5.1. I am receiving manifest from registry A in correct format (check below). When trying to push that to registry B, it errors with 400 Bad Request, "code":"DIGEST_INVALID","message":"provided digest did not match uploaded content". I am using correct Content-Type while pushing (application/vnd.docker.distribution.manifest.v2+json). 

Manifest received from registry A:
```
curl -v -X GET localhost/registry/v2/<imageName>/manifests/latest -H "Accept: application/vnd.docker.distribution.manifest.v2+json"
* About to connect() to localhost port 80 (#0)
*   Trying ::1...
* Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /registry/v2/<imageName>/manifests/latest HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost
> Accept: application/vnd.docker.distribution.manifest.v2+json
>
< HTTP/1.1 200 OK
< Server: nginx/1.11.3
< Date: Fri, 09 Dec 2016 18:01:44 GMT
< Content-Type: application/vnd.docker.distribution.manifest.v2+json
< Content-Length: 2181
< Connection: keep-alive
< Docker-Content-Digest: sha256:f8f5c9766fb041d11ba60c1f138057221ac3f337bbba480c8011c7090e8c99f0
< Docker-Distribution-Api-Version: registry/2.0
< Etag: "sha256:f8f5c9766fb041d11ba60c1f138057221ac3f337bbba480c8011c7090e8c99f0"
< X-Content-Type-Options: nosniff
< Strict-Transport-Security: max-age=15724800; includeSubDomains; preload
<
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 3581,
      "digest": "sha256:394ac110f48c89bd1cfac2fbf725f2a42692d325f4ac2a88bb7f21c897717c60"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 77284248,
         "digest": "sha256:7ab68ea8242f1c3dbdd8025bcf42aeefd83460d1a3f3fd3eba63299fbd84cfb5"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 525969,
         "digest": "sha256:e42e468c0ef3c2c33ba09e37dcb20f96cca7eb5d97eaaa8fd406d8ddd3e79ae3"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      }
   ]
}
```
Trying to push the same manifest to registry B:
```
curl -v -X PUT localhost:9000/v2/<imageName>/manifests/sha256:394ac110f48c89bd1cfac2fbf725f2a42692d325f4ac2a88bb7f21c897717c60 -H "Content-Type: application/vnd.docker.distribution.manifest.v2+json" --data @/tmp/manifest.json
```
No matter if I use SHA from registry A's Docker-Content-Digest response (f8f...9f0), I get the same error from registry B. Docker documentation does not say anything about pushing manifest with schema 2 version 2. Is there something missing ?

**Comment by pmalshe** [comment] 2016-12-09 23:18
Just an update: even if I use tag in place of sha256 reference while putting manifest into the registry, I get manifest blob unknown for the blob pointed sha256 in the config section.

**Comment by aaronlehmann** [comment] 2016-12-10 01:52
My suspicion is that `curl` is making minor changes to whitespace or line endings that cause the digest not to match. You might want to try `--data-binary` instead of `--data`, which may avoid this kind of processing.

After downloading the manifest, run `sha256sum` and make sure this digest matches the one given in `Docker-Content-Digest`. If that looks good, the problem is happening during the upload, and I'd suggest experimenting with different flags or tools to make sure the manifest is uploaded byte-for-byte.

> Just an update: even if I use tag (e.g. latest) in place of sha256 reference while putting manifest into the registry, I get manifest blob unknown for the blob pointed sha256 in the config section.

The sha256 referenced in the config section is referencing a different blob than the manifest. You should go by the `Docker-Content-Digest` header value.

**Comment by aaronlehmann** [comment] 2017-01-06 23:37
@pmalshe, did you have a chance to try the suggestions above?

**Comment by stevvooe** [comment] 2017-01-10 20:04
Looking at @aaronlehmann suggestion, that looks like the problem. Closing.

Let us know if you're still having a problem.

**Closed by stevvooe** 2017-01-10 20:04 UTC
