### ISSUE TITLE
Azure-related compile error "undefined: storage.DefaultBaseUrl"

### ISSUE THREAD

**Issue by jamshid** [docker/distribution#573] opened 2015-05-30 23:02 UTC
NBD but is there an easy way to disable azure support to avoid this error?
```
$ go version
go version go1.4.2 darwin/amd64
$ env | grep GO
GOROOT=/usr/local/opt/go/libexec
GOPATH=/Users/jamshid/go
$ echo $PATH
/usr/local/opt/go/libexec/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/jamshid/go/bin

$ go get github.com/docker/distribution/cmd/registry
# github.com/docker/distribution/registry/storage/driver/azure
/Users/jamshid/go/src/github.com/docker/distribution/registry/storage/driver/azure/azure.go:71: undefined: storage.DefaultBaseUrl
/Users/jamshid/go/src/github.com/docker/distribution/registry/storage/driver/azure/azure.go:79: undefined: storage.DefaultApiVersion
/Users/jamshid/go/src/github.com/docker/distribution/registry/storage/driver/azure/azure.go:117: d.client.PutBlockBlob undefined (type storage.BlobStorageClient has no field or method PutBlockBlob)
...
```

**Comment by dmp42** [comment] 2015-05-31 01:41
@jamshid for the "how to disable specific drivers" part:

@ahmetalpbalkan: we recently merged a driver for Ceph Rados, and we are using build flags (search `// +build include_rados`).

That lets people decide what they compile in or not, and gives us flexibility to by default compile some drivers but not others, depending on their maintenance status.

So, do you think you can look into adding a conditional build flag for the Azure driver?

**Comment by ahmetalpbalkan** [comment] 2015-05-31 01:46
@dmp42 there's nothing wrong with the maintenance level here. It's simply distribution uses an older version of Azure SDK (which we are still developing and taking breaking changes every day). 

Problem in this issue is @jamshid is not building with godep workspace in GOPATH and thus fetching current version of Azure SDK for Go (which obviously has breaking changes).

**Comment by dmp42** [comment] 2015-05-31 23:04
@ahmetalpbalkan maybe you missed the point :-)
I'm not concerned about quality or maintenance involvement - you guys do a great job!

I'm just looking for flexibility, and it seems like a good idea that *any* driver, well-supported or not uses conditional compilation.

Sorry if things were not clear.

**Comment by ahmetalpbalkan** [comment] 2015-05-31 23:48
@dmp42 Ah, sorry for misunderstanding. I was just trying to solve jamshid's problem, which was not using godeps.

 I'm okay with the idea of conditional compilation flag, though something like `//+build include_azure` seemed a bit inconvenient to me as people would have to rebuilt the registry image. However I'm all in for a `//+build exclude_azure` tag. Shall we make this Azure-only or for all drivers basically?

**Comment by dmp42** [comment] 2015-06-01 00:25
We would still ship Azure by default in the official image (along with any other well maintained driver). So, `include_azure` would be default.

We should certainly do that for all drivers.

Here is what was done for Ceph: https://github.com/docker/distribution/search?utf8=%E2%9C%93&q=include_rados 

Cheers.

**Comment by stevvooe** [comment] 2015-06-01 20:52
@jamshid Check out the documentation on properly building the project: https://github.com/docker/distribution/blob/master/docs/building.md.

It looks like you need to set the version of the azure package to the version we have vendored.

**Comment by hex108** [comment] 2015-06-03 10:27
I think it will be better to document it in section [**Build the development environment**](https://github.com/docker/distribution/blob/master/docs/building.md) if we need run `godep restore` first.

**Comment by stevvooe** [comment] 2015-06-04 01:22
@hex108 Running `godep restore` is not necessary to develop the registry. The issue is interface changes on the azure drivers. I've submitted #593 to disable them by default. We may want to add the `-d` flag to the `go get` command.

**Comment by ahmetalpbalkan** [comment] 2015-06-04 02:44
> Running godep restore is not necessary to develop the registry.

@stevvooe why? isn't keeping the builds consistent and repeatable from dependencies perspective the entire point of godep?

**Closed** 2015-06-04 03:14 UTC
Labels: in progress

**Comment by stevvooe** [comment] 2015-06-04 18:19
@ahmetalpbalkan Yes, it is not _necessary_ to develop while it may be used for release builds. 

For development tasks, it is very important that we remain compatible with Go community tools, such as `go get`. For instance, I should be able to cd into any package directory and run `go test` or get coverage results or leverage any go tooling. This has the following benefits:

1. To experiment with new dependencies, one does not have to fight with `godep`. One can simply `go get` the dependency.
2. Other tools can be used to manipulate GOPATH and the Makefile still works correctly.
3. Development moves much quicker since it is very easy to run part of the unit tests. If a user knows how to run `go test`, it just works. There is no need to learn the special incantations of a particular build environment.

As a contrary example, please see the main docker project. To even compile, it takes several minutes before seeing results. This makes iteration and experimentation a problem.
