### ISSUE TITLE
NULL tags in catalog API

### ISSUE THREAD

**Issue by bnordbo** [docker/distribution#1186] opened 2015-11-13 08:43 UTC
I'm not sure this is a bug or simply an undocumented aspect of the catalog API, but when listing the tags of a repository that does not exist, the API returns a `200 OK` with the JSON payload `{"name":"<repo-name>","tags":null}`. In this case, it would be more practical if `tags` were an empty list, as this would facilitate usage such as piping the response body through e.g. `jq '.tags[]'`. It would also be more in line with what one would expect after reading the API documentation.

To reproduce: `curl -s <some-2.1.1-registry>/v2/nosuchrepohere/tags/list`. This is using an S3 backend version 2.1.1 registry.

No big deal of course, but maybe something for someone wanting a quick win some rainy afternoon. :-)

**Comment by mssola** [comment] 2015-11-13 08:50
Hello, we have had a similar situation in Portus but this time when calling this method while the image was being uploaded (see SUSE/Portus#552). I'd also expect an empty list to be returned honestly.

Anyways, if this is expected behavior, maybe we could improve the documentation of this method :)

**Comment by stevvooe** [comment] 2015-11-13 21:51
This is a bug. Empty tags should probably result in a 404 from the [specification](https://github.com/docker/distribution/blob/master/docs/spec/api.md#on-failure-no-such-repository-error).

Sorry about this. I really don't like the use of `null` in json and didn't mean impose that horror on anyone else. :sob:

@bnordbo Had you _ever_ pushed to that repository then deleted it? There is actually a unit test for this and I can't reproduce this with the filesystem driver. I am suspecting some s3 oddness here. I've submitted #1187 to check for the test condition and we'll take if from there.

**Comment by stevvooe** [comment] 2015-11-13 23:57
@bnordbo @mssola After testing out the PR, I am pretty certain this is due to an inconsistency between storage driver implementations. It looks like certain drivers don't return PathNotFound when the listing a non-existent path.

 I am going to examine the impact of adding something to test suite and simple fix.

**Comment by bnordbo** [comment] 2015-11-14 09:34
Thank you for looking into this @stevvooe! In my example, I had never pushed anything to the repository, i.e. it did not exist.

**Comment by mssola** [comment] 2015-11-16 10:34
@stevvooe thanks for taking care of this :)

**Comment by RichardScothern** [comment] 2015-12-09 00:33
Closed as fixed by #1187.  This will be in the imminent release.

**Closed by RichardScothern** 2015-12-09 00:33 UTC
