### ISSUE TITLE
Issue with Retraining Tensorflow Demo

### ISSUE THREAD

**Issue by Bonkoodle** [docker/distribution#2269] opened 2017-05-08 15:23 UTC
So I'm trying to follow this tutorial: https://medium.com/@daj/creating-an-image-classifier-on-android-using-tensorflow-part-3-215d61cb5fcd
It's really important for me to get it working since it's part of my dissertation and only have 2 weeks left.

When I got to the part where it says
```
# cp /tf_files/stripped_retrained_graph.pb bazel-bin/tensorflow/examples/android/assets/stripped_output_graph.pb
# cp /tf_files/retrained_labels.txt bin/tensorflow/examples/android/assets/imagenet_comp_graph_label_strings.txt
```

It kept saying "No such file or directory"
Eventually I figured out I could do this:
`cp /tf_files/stripped_retrained_graph.pb /tensorflow/tensorflow/examples/android/assets/stripped_output_graph.pb`
and
`cp /tf_files/retrained_labels.txt /tensorflow/tensorflow/examples/android/assets/imagenet_comp_graph_label_strings.txt`

Which seemed to work, since they definitely are in the targeted location.
http://imgur.com/a/dWdnj
Is this definitely the same location that the tutorial says though?

The files seemed to be copied in correctly, but then when I installed the app it was still just running the regular demo app. Not sure why it didn’t work, so frustrating. 
When I rebuilt it after copying the files in I got these conflict messages: 
https://i.imgur.com/xltZbKgl.png

Are these normal to have? I don't think so.
I think they're quite likely the reason why it's not working, since it's using an old file stored in a different location.
It looks like a different labels file is taking priority over mine, how can I reach the external/inception5h/imagenet_comp_graph_label_strings.txt file to delete it so my file is used instead? Does the “external” part mean that I can’t actually access it from within Docker?

**Comment by dmcgowan** [comment] 2017-05-08 17:42
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by dmcgowan** 2017-05-08 17:42 UTC
