### ISSUE TITLE
Add manifest contents to push event payload

### ISSUE THREAD

**Issue by ncdc** [docker/distribution#172] opened 2015-02-13 17:53 UTC
Would you be willing to add the manifest contents to the push event payload? If we don't have that for OpenShift, we'll have to make a request to the registry as soon as we receive the push event to retrieve the manifest (we store the image metadata in OpenShift).

@stevvooe

**Comment by stevvooe** [comment] 2015-02-13 19:27
@ncdc Requiring a request to the registry to get the updated manifest is by design. It's best practice to only include identifying properties in notification messages. This ensures that the notified party can only access data to which they are privileged. Following this approach avoids exposing potentially sensitive data to notified parties.

**Comment by ncdc** [comment] 2015-02-13 19:28
@stevvooe I can understand the security concern, although in our case the notifications will be going from an OpenShift-managed registry to OpenShift itself. Perhaps we could make including the manifest contents configurable, defaulting to off?

**Comment by ncdc** [comment] 2015-02-13 19:28
cc @smarterclayton

**Comment by stevvooe** [comment] 2015-02-13 19:37
@ncdc Ideally, we'd like to keep the notification format consistent so I don't think that is a viable solution.

What is the issue with sending another request to get the manifest contents?

**Comment by ncdc** [comment] 2015-02-13 19:39
Just trying to keep the round trips to a minimum

**Comment by stevvooe** [comment] 2015-02-13 19:58
Adding the manifest contents to the event payload is not something we're going to implement for the following reasons:

1. It is best practice to only send identifying properties for an asynchronous notification where the access controls may change while in-flight. By excluding data, it requires the consumer to go through the same access controls as the client that initiated the event.
2. By excluding data, it reduces the likelihood that in-flight data becomes out of date or obsolete.
3. By keeping the event format generic, we ensure that an event consumer does not have to deal with various manifest formats that may arise. A digest and url is received and the format of the manifest can be negotiated between the consumer and the registry.
4. A given version of a manifest need only be fetched once by an endpoint, since the content is addressable.

The above properties outweigh the value saving of an extra round trip.

I'm going to close this.

**Closed** 2015-02-13 19:59 UTC
Labels: Enhancement, Question, wontfix
