### ISSUE TITLE
Windows 7 Enterprise Docker for Windows Installer.exe does not load

### ISSUE THREAD

**Issue by Xendox** [docker/distribution#2436] opened 2017-11-01 09:05 UTC
![image](https://user-images.githubusercontent.com/20001421/32267615-e2fb002c-befc-11e7-86ac-71d65681df6a.png)

**Comment by thaJeztah** [comment] 2017-11-01 12:42
Docker for Windows requires Windows 10 as a minimum; see https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install so you need an updated version of Windows to run Docker for Windows

> The current version of Docker for Windows runs on 64bit Windows 10 Pro, Enterprise and Education (1607 Anniversary Update, Build 14393 or later). In the future we will support more versions of Windows 10.

If you cannot update Windows, you can use docker toolbox as an alternative, which uses VirtualBox, and allows you to run Linux containers in a lightweight VM; https://docs.docker.com/toolbox/overview/

closing because this is not a bug

**Closed by thaJeztah** 2017-11-01 12:42 UTC
