### ISSUE TITLE
Allow S3 url to be provided in place of region

### ISSUE THREAD

**Issue by mindscratch** [docker/distribution#1007] opened 2015-09-21 13:15 UTC
Currently the S3 driver only allows a region to be provided for connecting to S3. If a region is not yet defined in the [library](https://github.com/AdRoll/goamz/blob/master/aws/regions.go) used by the driver, then you're out of luck.

It would be nice to be able to explicitly set the URL used to talk to S3.

**Comment by mboersma** [comment] 2015-09-23 16:41
This will be fixed by expanded S3 support in #808.

**Comment by BrianBland** [comment] 2016-01-26 01:59
Closing as a duplicate of #808

**Closed by BrianBland** 2016-01-26 01:59 UTC
