### ISSUE TITLE
Error pushing to registry 500 trying to push

### ISSUE THREAD

**Issue by JendaPlhak** [docker/distribution#427] opened 2015-04-23 20:07 UTC
I am having some troubles with pushing image into public repository on dockerhub. The command I run is 
     
    sudo docker push bileto/osrm-base:production

But unfortunately the result is:

    The push refers to a repository [bileto/osrm-base] (len: 1)
    bda2c71b7c56: Image push failed 
    FATA[0439] Error pushing to registry: Server error: 500 trying to push bileto/osrm-base blob -         sha256:c8fd3e2ec95adc3af152335422ec025ca54d746536283cd3cfe19f5ca1a89125

To further describe the behaviour, I think that upload to the dockerhub is ok since I get the progress bar

    bda2c71b7c56: Pushing [===================================>               ] 247.9 MB/350.5 MB

And the error occurs when upload is complete. 

I found this https://github.com/docker/distribution/issues/112 issue here on github but that apparently deals with some other bug since by blob starts with `sha256:` Would it be possible for anyone to help me out of this? I can provide more information if needed.

**Comment by stevvooe** [comment] 2015-04-23 20:22
This is a duplicate of #413. We are in the process of investigating the root cause.

If you can, please provide the output of `docker version` and `docker info`.
How big are the individual layers that you are trying to push?

**Comment by JendaPlhak** [comment] 2015-04-23 20:31
Version is 

    Docker version 1.6.0, build 4749651

And from info I get 

    Containers: 18
    Images: 537
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 573
     Dirperm1 Supported: false
    Execution Driver: native-0.2
    Kernel Version: 3.13.0-49-generic
    Operating System: Ubuntu 14.04.2 LTS
    CPUs: 8
    Total Memory: 15.61 GiB
    Name: machine
    ID: ODUZ:BM32:42EY:THF7:WERJ:CIVU:X6TB:DRBZ:FGTV:FCDX:35JF:L2JJ
    Username: jplhak
    Registry: [https://index.docker.io/v1/]
    WARNING: No swap limit support

The layers are quite big actually. First one I pushed (yeah, I succeeded somehow in pushing the first layer, but I have no idea how) has about 350 Mb. Now I get `Image already exists`. But the same error occurs when pushing the next one. That has 648 Mb. Well I hope I refer to layers correctly and understand the meaning of the word in this context.

**Comment by stevvooe** [comment] 2015-04-23 23:21
@JendaPlhak We are working on tracking down the root cause. Please watch #413 for updates. As a workaround, could you try reducing the layer size?

**Comment by JendaPlhak** [comment] 2015-04-24 08:42
I can certainly split layers into smaller parts. All except the one where I load quite big search graph (640 Mb). Splitting that seems like a lot of work unfortunately :-/ But it actually can wait till Sunday. It would be nice to work it out sooner, but it is not crucial.

**Comment by dmp42** [comment] 2015-04-24 20:31
@JendaPlhak the bug has been fixed in production.

If you can confirm this is now working for you, I will close this.

Thanks!

**Comment by JendaPlhak** [comment] 2015-04-25 07:11
It all works fine now. Thank you! :+1:

**Closed** 2015-04-26 05:03 UTC
Labels: bug, duplicate

**Comment by rakotomandimby** [comment] 2015-08-24 11:44
@dmp42 , May I know what was it about? I encounter a similar problem on a local registry. Thank you.

**Comment by dmp42** [comment] 2015-08-24 16:49
@rakotomandimby this here was a bug in the very first version (registry:2.0.0)

You should be using 2.0.1, or 2.1.1, and this should not affect you.

Please open a new issue if you are having an issue with one of these versions.

**Comment by JendaPlhak** [comment] 2015-08-28 09:20
It is ok now!
