### ISSUE TITLE
Azure Storage Driver Panic on Bad Creds

### ISSUE THREAD

**Issue by allingeek** [docker/distribution#630] opened 2015-06-14 19:50 UTC
Bad remote storage credentials should be met with an appropriate error message. The one provided by the ErrorMessage is fine. A full blown panic is a poor UX. 

Without digging into the code, this feels like a general error handling improvement. I doubt this is specific to credentials, but incorrect credentials will be a common misconfiguration.

> panic: storage: remote server returned error. StatusCode=403, ErrorCode=InsufficientAccountPermissions, ErrorMessage=The account being accessed does not have sufficient permissions to execute this operation.
RequestId:345d3621-0001-0039-79d8-a6b004000000
Time:2015-06-14T19:32:12.2033509Z, RequestId=345d3621-0001-0039-79d8-a6b004000000

>goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0x7f90c5c6fa90, 0xc20805cb40, 0xc20802b748, 0x3, 0xc20802b780, 0x5, 0x0, 0x0, 0xc20805c6f0, 0xa5e630, ...)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:81 +0x5eb
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:62 +0x439
>
goroutine 6 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

> goroutine 11 [runnable]:
net/http.(*persistConn).readLoop(0xc2080a8160)
	/usr/src/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:660 +0xc9f

>goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

>goroutine 12 [select]:
net/http.(*persistConn).writeLoop(0xc2080a8160)
	/usr/src/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:661 +0xcbc

**Comment by stevvooe** [comment] 2015-06-15 22:15
@allingeek Bad configuration blocks registry startup. This is by design.

**Comment by allingeek** [comment] 2015-06-15 22:20
I'm not suggesting that we make the registry start anyway. Just that panic messages should not make it to the user.

**Comment by stevvooe** [comment] 2015-06-15 22:37
@allingeek I agree that panic is not the best UX. We do this to avoid a much worse UX where correct actions cannot be inferred due to obscured error messages. With a panic, we know the exact cause and line of code. We also can see what might have been going on at the same time. In this case, we even get related details from the azure error.

We would be willing to accept a PR to fix this, but the current behavior both provides users with a cause and an avenue of support to resolve the issue. While this isn't the best UX, it is good enough.

**Comment by allingeek** [comment] 2015-06-16 00:22
Panics do provide excellent details, but in most cases they make users think that the software is broken. Not that their input was incorrect.

**Comment by stevvooe** [comment] 2015-06-16 01:00
@allingeek Sure, but against the catch-22 situation of "invalid config, not starting", the current behavior is a better experience. There are just too many other UX issues we are addressing at the system level to drop everything and "fix" this.

If someone would like to take this on, we would appreciate it.

**Comment by dmp42** [comment] 2015-07-24 01:41
@ahmetalpbalkan PTAL

**Comment by ahmetalpbalkan** [comment] 2015-07-24 03:19
@dmp42 looks like the issue here is mostly UX. The reason this might not be happening on other drivers could be because perhaps they don't make any API calls to the storage service during initialization; however Azure does that to create the storage container (bucket) if it does not exist.

I think UX-wise, agreed, in this case  the `panic()` call in `registry/handlers/app.go` looks a bit overkill and  we should probably replace that with a `log.Fatalf`. 

@allingeek Regarding the error you are getting, I think it could be about your subscription's state, please check if it is disabled due to billing reasons etc. Normally the storage access keys you obtain from the management portal should just work.

**Comment by stevvooe** [comment] 2015-07-24 06:49
@ahmetalpbalkan Right now, we are indeed making some calls on startup across various storage drivers. If these fail for any reason, we can block startup. This is not ideal.

The main trade off here is that a panic has the nice affect of being loud and getting a users attention. If these problems are allowed to happen at request time, they become a little more opaque and harder to troubleshoot.

**Comment by ahmetalpbalkan** [comment] 2015-07-24 07:27
Agreed. If we think panic is also fine rather than print/exit, then I guess we can close on this issue as a wontfix.

**Closed** 2015-07-25 00:45 UTC
Labels: enhancement
