### ISSUE TITLE
improve "authentication required" error

### ISSUE THREAD

**Issue by vikstrous** [docker/distribution#2037] opened 2016-11-02 22:15 UTC
This error can happen for at least two different reasons: If the user it not authenticated or if the user is not authorized. These require the user to take different actions. If they are not authenticated, they need to log in. If they are not authorized they need to make sure they have permissions on the given repo and that the given repo exists. This error message is causing a lot of confusion with users.

A push to a non-existent repo looks like this:

```
$ docker push thing
The push refers to a repository [docker.io/library/thing]

unauthorized: authentication required
```

The error string is defined in https://github.com/docker/distribution/blob/master/registry/api/errcode/register.go#L40. Even the name of the constant is about authorization while its content is about authentication.

**Comment by dmcgowan** [comment] 2016-11-02 22:57
Having a look through the code I don't quite understand why we still return a 401 when we know a 403 is needed https://github.com/docker/distribution/blob/master/registry/auth/token/accesscontroller.go#L109. We might be able to update the engine side to read this error, I didn't realize it was doing this so the client likely is not differentiating using this error field.

**Comment by vikstrous** [comment] 2016-11-02 23:03
The engine displays the text of the error so, regardless of the error code, it could be made more useful by just changing the string.

**Comment by dmcgowan** [comment] 2016-11-02 23:44
@vikstrous agreed, the detail appears lacking and in this case useless. I would expect the insufficient scope message to be inside the detail. Either way wondering if the engine can do more to present a more useful message than relying on the detail body.

```
The insufficient scope should be the detail not the require

```
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:somebaduser/somebadrepo:pull",error="insufficient_scope"
Date: Wed, 02 Nov 2016 23:40:48 GMT
Content-Length: 155
Connection: close
Strict-Transport-Security: max-age=31536000

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Name":"somebaduser/somebadrepo","Action":"pull"}]}]}

``

**Comment by dmcgowan** [comment] 2016-11-03 00:17
@vikstrous are you running the daemon with ` --disable-legacy-registry`?

**Comment by dmcgowan** [comment] 2016-11-03 23:10
I think we will have to go a step further and use a different error type here https://github.com/docker/distribution/blob/master/registry/client/errors.go#L89. The problem is right now if "unauthorized" is in the error string at all that gets returned, this monstrosity gets hit... https://github.com/docker/docker/blob/master/api/server/httputils/errors.go#L60

**Comment by vikstrous** [comment] 2016-11-04 21:32
@dmcgowan I was running docker 1.13 / master with a registry that supports only v2. It looked like changing the error string in the registry fixed it in that case, but it sounds like that won't work for all cases?

**Comment by dmcgowan** [comment] 2016-11-14 18:49
Closed by https://github.com/docker/docker/pull/28235 and #2047 and #2048

**Closed by dmcgowan** 2016-11-14 18:49 UTC
