### ISSUE TITLE
"authentication required" on push after successful login with 2.2

### ISSUE THREAD

**Issue by bweston92** [docker/distribution#1343] opened 2016-01-13 08:40 UTC
Might be related to #1165 

I've set docker registry:2 up using a docker-compose file and I use nginx to proxy from my domain name to 5000 on the server. 

```
[root@MARLOW:/opt/docker]# cat docker-compose.yml 
registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - /opt/docker/data:/var/lib/registry
    - /opt/docker/certs:/certs
    - /opt/docker/auth:/auth
```

I run `docker login {hostname}` and it works successfully. How-ever when I try to push I get authentication required.

```
bradley@lindesk22:/var/www$ docker push {hostname}/app-dashboard:latest
The push refers to a repository [{hostname}/app-dashboard] (len: 1)
bdaaa2786dbc: Pushing 1.024 kB
unauthorized: authentication required
```

When I curl with the authentication details it works fine.

**Comment by BrianBland** [comment] 2016-01-15 00:16
I'll need more information to understand the conditions in which this problem occurs. Could you provide the output of the following?

```sh
docker version
docker info
docker exec <registry-container> registry -version
```

It may also help to have the registry and daemon logs (in debug mode) from when you attempted a push.

**Comment by dmp42** [comment] 2016-01-25 19:49
@bweston92 were you able to make it work? Alternatively, can you provide the requested information?

**Comment by bweston92** [comment] 2016-01-26 09:00
I believe same issue as https://github.com/docker/docker/issues/12972

```
[root@MARLOW:~]# docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      linux/amd64
[root@MARLOW:~]# docker info
Containers: 9
Images: 116
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 134
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 1
Total Memory: 1.963 GiB
Name: MARLOW
ID: PJ4F:LJQO:ZQIG:E42X:QIQT:AQN6:KMB3:3JXW:COEX:JGAY:7E6I:VRPU
WARNING: No memory limit support
WARNING: No swap limit support
[root@MARLOW:~]# docker exec docker_registry_1 registry -v
registry github.com/docker/distribution v2.2.1
```

https://botbot.me/freenode/docker/msg/57835560/

**Comment by idioter** [comment] 2016-04-11 10:45
after i run docker login and success, i create repo in website of hub.docker.com with same name in my local repo, then i can push my local repo.
i tried this way using repo without tag name.
it works for me.

**Comment by asheshambasta** [comment] 2016-05-13 09:21
See https://github.com/docker/distribution/issues/1165#issuecomment-218992467

Same issue.

**Comment by stevvooe** [comment] 2016-05-24 21:27
@asheshambasta Please read through #1165. The issue there was a misconfigured `host` parameter and a problem with rados failures. I'm not seeing any indication in this configuration that these are related.

Unfortunately, these problems resulted in identical error message. While two issues may have common symptoms, their root cause can be completely different. We separate them to ensure that appropriate root cause analysis can be conducted. Hopefully, solid RCA can lead to a decent fix for this.

@asheshambasta I really recommend you open your own issue, rather than trying to make determination that you are seeing one problem or the other. There may be a subtle configuration problem or specific conditions for your environment that are triggering the problem. If we find them to have the same root cause, we'll link them at a later date.

**Closed** 2017-01-16 12:35 UTC
Labels: question
