### ISSUE TITLE
Registry S3 Storage region issue

### ISSUE THREAD

**Issue by madhokie** [docker/distribution#1337] opened 2016-01-12 18:55 UTC
When you are using S3 storage on an AWS platform that is not publicly available (i.e. read government version), the regions are hardcoded with no ability to map a region that doesn't exist in the public domain. Registry should provide the ability to select any region string. Currently if it isn't one of the canned regions, registry will exit.

**Comment by stevvooe** [comment] 2016-01-12 20:33
Duplicate of #767.

**Closed by stevvooe** 2016-01-12 20:33 UTC
Labels: duplicate
