### ISSUE TITLE
"authentication required" on push after successful login with 2.2

### ISSUE THREAD

**Issue by treed** [docker/distribution#1165] opened 2015-11-06 21:02 UTC
I'm having an issue with authentication (using basic auth) where I can successfully "docker login", but then "docker push" fails with "unauthorized: authentication required".

The message from the logs is not particularly helpful, because the error message is being printed as a pointer rather than the string behind it: 

"error authorizing context: basic authentication challenge: htpasswd.challenge{realm:\"basic-realm\", err:(*errors.errorString)(0xc20802ac80)}"

At the very least, this should be corrected to print the actual error, but even better would be having push work.

I attempted this with 2.1 just now, and with 2.1, there is no authentication error, but one of the layers of the image I'm attempting to push just hangs:

9ccba5c388b3: Pushing [==================================================>] 4.096 kB

So the authentication issue, at least, seems like a regression. I'm still unable to use the registry even on 2.1, however.

Let me know if you need any further information.

**Comment by treed** [comment] 2015-11-06 22:33
I've got a fix for the error message at least; asking around here to see how I can get the fix signed off to send a pull request. But in the meantime, the actual error message is:

"error authorizing context: basic authentication challenge for realm 'basic-realm': invalid authorization credential"

Which doesn't say why it's invalid, but at least I have a little more to go on.

**Comment by RichardScothern** [comment] 2015-11-06 22:39
@treed : thanks for this.  [Open a PR](https://github.com/docker/distribution/blob/master/CONTRIBUTING.md#contributing-a-patch-for-a-known-bug-or-a-small-correction) and someone will have a look.

**Comment by treed** [comment] 2015-11-06 23:40
So it looks like the underlying issue here is that "docker login" saved auth and email, but I never gave it an email, just the account name, so "docker push" had no credential to send for the username. I'm unsure why this would differ between 2.1 and 2.2.

I'm unsure how to add a username to the config to test if that will fix the issue.

**Comment by stevvooe** [comment] 2015-11-07 02:52
> "error authorizing context: basic authentication challenge: htpasswd.challenge{realm:\"basic-realm\", err:(*errors.errorString)(0xc20802ac80)}"

This is a bug in the `errcode` library when decoding/encoding the error message. #1166 will not fix this since this is happening on the server side. The encoder should detect `error` on the interface and call `Error()` before sending as json.

**Comment by treed** [comment] 2015-11-07 04:56
#1166 *is* on the server side (or is there some other server I'm not thinking of?), and does fix it, because the later error message I pasted came after I fixed it.

It does not, however, fix the actual problem I'm experiencing, it just makes the error message actually appear so it can be debugged.

**Comment by stevvooe** [comment] 2015-11-09 20:02
@treed I think I may not have been clear. If we want to see this error land on the client side, the `errcode

**Comment by treed** [comment] 2015-11-09 20:47
Last week with Registry 2.2, a push would immediately fail out with "authentication required", even after a successful login. When I tried 2.1, the push would hang on a particular layer. I tried to recreate it to get a clean log with just the relevant stuff, and now 2.2 is also hanging instead of failing. I don't know what could have changed.

Here's the registry configuration:

```
version: 0.1
log:
  level: info
  formatter: text
  fields:
    service: registry
    environment: production
storage:
  rados:
    poolname: docker
    username: docker
  cache:
    blobdescriptor: inmemory
auth:
  htpasswd:
    realm: basic-realm
    path: /etc/docker/registry/htpasswd
http:
  addr: 0.0.0.0:443
  secret: [removed]
  host: https://docker.imvu.com:443
  tls:
    certificate: /etc/imvu/certs/wildcard.imvu.com.pem
    key: /etc/imvu/certs/wildcard.imvu.com.key
```

Client info:

```
> docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
```

(Using boot2docker originally, switched to docker-machine partway through, same problem exists on both.)

Here's the output from the commands:

```
 > docker login docker.imvu.com
Username: treed
Password:
Email:
WARNING: login credentials saved in /Users/treed/.docker/config.json
Login Succeeded
> docker push docker.imvu.com/ubuntu-base:12.04
The push refers to a repository [docker.imvu.com/ubuntu-base] (len: 1)
b9418c934b95: Image already exists
12522b44255c: Image already exists
9ccba5c388b3: Preparing
```

I adjusted the config to use debug logging and here are the logs from the registry (including the initial command that I used to run it): http://sprunge.us/KYcY

It's interesting to note that even though I'm no longer getting the error message on the client, the registry is still logging the same message with the pointer address. (Without the fix this time, since I wanted to provide a log with pure upstream.)

Here's what I believe is the relevant portion of the local docker daemon logs:

```
time="2015-11-09T20:30:17.686665858Z" level=debug msg="Calling POST /v1.21/auth"
time="2015-11-09T20:30:17.686740046Z" level=info msg="POST /v1.21/auth"
time="2015-11-09T20:30:17.692186091Z" level=debug msg="hostDir: /etc/docker/certs.d/docker.imvu.com"
time="2015-11-09T20:30:17.692263039Z" level=debug msg="pinging registry endpoint https://docker.imvu.com/v0/"
time="2015-11-09T20:30:17.692282359Z" level=debug msg="attempting v2 ping for registry endpoint https://docker.imvu.com/v2/"
time="2015-11-09T20:30:17.767874189Z" level=debug msg="attempting v2 login to registry endpoint https://docker.imvu.com/v2/"
time="2015-11-09T20:30:17.767940327Z" level=debug msg="trying \"basic\" auth challenge with params map[realm:basic-realm scope:]"
time="2015-11-09T20:30:24.396840765Z" level=debug msg="Calling POST /v1.21/images/docker.imvu.com/ubuntu-base/push"
time="2015-11-09T20:30:24.396878533Z" level=info msg="POST /v1.21/images/docker.imvu.com/ubuntu-base/push?tag=12.04"
time="2015-11-09T20:30:24.408942545Z" level=debug msg="hostDir: /etc/docker/certs.d/docker.imvu.com"
time="2015-11-09T20:30:24.416812194Z" level=debug msg="hostDir: /etc/docker/certs.d/docker.imvu.com"
time="2015-11-09T20:30:24.417214330Z" level=debug msg="Trying to push docker.imvu.com/ubuntu-base to https://docker.imvu.com v2"
time="2015-11-09T20:30:24.493689007Z" level=debug msg="Checking \"12.04\" against graph.Repository{\"12.04\":\"b9418c934b955cd20975487b6bd29bcf2244be85af8060ac7dc4b0d0579f319c\"}"
time="2015-11-09T20:30:24.493732194Z" level=debug msg="Pushing repository: ubuntu-base:12.04"
time="2015-11-09T20:30:24.493877927Z" level=debug msg="Pushing layer: b9418c934b955cd20975487b6bd29bcf2244be85af8060ac7dc4b0d0579f319c"
time="2015-11-09T20:30:24.593881282Z" level=debug msg="Pushing layer: 12522b44255c63bfd85d751457fc1764393b524f673a8e116cd58ec7e4475f31"
time="2015-11-09T20:30:24.694611300Z" level=debug msg="Pushing layer: 9ccba5c388b38a0c41c59980cdf0a56436f7cc80e460b9c11511434a7872030d"
time="2015-11-09T20:30:24.695387860Z" level=debug msg="[graph] TarLayer with reassembly: 9ccba5c388b38a0c41c59980cdf0a56436f7cc80e460b9c11511434a7872030d"
time="2015-11-09T20:30:24.703817746Z" level=debug msg="[graph] 9ccba5c388b38a0c41c59980cdf0a56436f7cc80e460b9c11511434a7872030d is at \"/mnt/sda1/var/lib/docker/aufs/mnt/9ccba5c388b38a0c41c59980cdf0a56436f7cc80e460b9c11511434a7872030d\""
```

**Comment by stevvooe** [comment] 2015-11-09 20:57
@treed We are seeing the upload start in the logs (the `POST` request) but we aren't seen the parts get uploaded (`PUT` requests). It looks like the problem is here:

```
http:
  addr: 0.0.0.0:443
  secret: [removed]
  host: https://docker.imvu.com:443
```

You do not need to specify "443" and "https". This is probably causing the redirect to break. You should never set this parameter unless you're deploying in specific proxy configurations. We can see from the logs that this is not necessary:

```
http.request.host=docker.imvu.com
```

This means the registry is correctly detecting the http host.

**Comment by treed** [comment] 2015-11-09 21:07
The docs for "host" show specifying the protocol and port:

`host: https://myregistryaddress.org:5000`

The docs also don't mention anything about specific proxy configurations. Perhaps those should be updated.

Removing that line from the config causes it to instead hang a little later:

```
> docker push docker.imvu.com/ubuntu-base:12.04
The push refers to a repository [docker.imvu.com/ubuntu-base] (len: 1)
b9418c934b95: Image already exists
12522b44255c: Image already exists
9ccba5c388b3: Pushing [==================================================>] 4.096 kB
```

```
time="2015-11-09T21:02:45.305729748Z" level=debug msg="Calling POST /v1.21/images/docker.imvu.com/ubuntu-base/push"
time="2015-11-09T21:02:45.306343361Z" level=info msg="POST /v1.21/images/docker.imvu.com/ubuntu-base/push?tag=12.04"
time="2015-11-09T21:02:45.316159496Z" level=debug msg="hostDir: /etc/docker/certs.d/docker.imvu.com"
time="2015-11-09T21:02:45.320520626Z" level=debug msg="hostDir: /etc/docker/certs.d/docker.imvu.com"
time="2015-11-09T21:02:45.320715272Z" level=debug msg="Trying to push docker.imvu.com/ubuntu-base to https://docker.imvu.com v2"
time="2015-11-09T21:02:45.399251957Z" level=debug msg="Checking \"12.04\" against graph.Repository{\"12.04\":\"b9418c934b955cd20975487b6bd29bcf2244be85af8060ac7dc4b0d0579f319c\"}"
time="2015-11-09T21:02:45.399289131Z" level=debug msg="Pushing repository: ubuntu-base:12.04"
time="2015-11-09T21:02:45.399420661Z" level=debug msg="Pushing layer: b9418c934b955cd20975487b6bd29bcf2244be85af8060ac7dc4b0d0579f319c"
time="2015-11-09T21:02:45.498167983Z" level=debug msg="Pushing layer: 12522b44255c63bfd85d751457fc1764393b524f673a8e116cd58ec7e4475f31"
time="2015-11-09T21:02:45.597936003Z" level=debug msg="Pushing layer: 9ccba5c388b38a0c41c59980cdf0a56436f7cc80e460b9c11511434a7872030d"
time="2015-11-09T21:02:45.598377934Z" level=debug msg="[graph] TarLayer with reassembly: 9ccba5c388b38a0c41c59980cdf0a56436f7cc80e460b9c11511434a7872030d"
time="2015-11-09T21:02:45.604748777Z" level=debug msg="[graph] 9ccba5c388b38a0c41c59980cdf0a56436f7cc80e460b9c11511434a7872030d is at \"/mnt/sda1/var/lib/docker/aufs/mnt/9ccba5c388b38a0c41c59980cdf0a56436f7cc80e460b9c11511434a7872030d\""
```

and: http://sprunge.us/EcOb for the registry logs

**Comment by treed** [comment] 2015-11-09 21:33
So, data point: If I use localstorage instead of rados, this problem goes away, and the authentication warning is *still* present in the logs, despite the success:

```
> docker push docker.imvu.com/ubuntu-base:12.04
The push refers to a repository [docker.imvu.com/ubuntu-base] (len: 1)
b9418c934b95: Pushed
12522b44255c: Pushed
9ccba5c388b3: Pushed
a01befd2c348: Pushed
c1ec5a9663c5: Pushed
e74ea44a7d83: Pushed
13da6020d26f: Pushed
12.04: digest: sha256:89276c8700325cbeaa10843e17464b053084b1848fdd636a9722757ef45124dc size: 10329
```

So I guess the auth warning is a red herring?

**Comment by stevvooe** [comment] 2015-11-09 21:59
@treed Those docs on `host` don't really go into why it is there. Don't set it unless you know you need it, which you don't. Please remove it.

It is possible that there are a few different issues culminating in this behavior. It sounds like you're having an issue with rados, a redirect issue and a problem with authentication. My guess is that the auth issue is due to the redirect issue.

**Comment by treed** [comment] 2015-11-10 01:18
It already was removed. The output after that was the hang on "pushing", which went away when I switched away from Rados.

Given that I can no longer reproduce the original problem, and the current problem seems to have to do with Rados, should we close this issue and open a new one? (And re-open if necessary if it comes back, since I have no idea what changed to cause it to hang instead of error.)

**Comment by stevvooe** [comment] 2015-11-10 02:56
@treed I think that sounds okay. Let's troubleshoot the issues with rados. Closing this issue.

**Closed by stevvooe** 2015-11-10 02:56 UTC

**Comment by erulabs** [comment] 2015-11-16 23:58
Hello! I had these exact symptoms and figured out it was actually a redirection issue

Changing:

`host: "https://registry.{{ tt_domain.stdout }}:5000"`

to

`host: "https://registry.{{ tt_domain.stdout }}"`

Resolved the issue. Looks like PUSH does a redirect, which auto-includes the port on the address. The way I had it, PUSH was failing because the URI wound up being https://registry.{{ tt_domain.stdout }}:5000:5000

Hope this helps!

**Comment by aug-riedinger** [comment] 2016-04-18 08:50
Same issue here. I don't understand, what's the fix?

Using: 

```
▶ docker --version
Docker version 1.11.0, build 4dc5990
```

**Comment by gtirloni** [comment] 2016-04-18 17:01
I'm having the same issue.

    # docker logout
    Remove login credentials for docker.io

    # docker login
    Username: user
    Password: 
    Email: user@example.com
    WARNING: login credentials saved in /root/.docker/config.json
    Login Succeeded
    
    # docker push user/repository
    
    Do you really want to push to public registry? [y/n]: y
    The push refers to a repository [docker.io/user/repository] (len: 0)
    202bee33ffd2: Preparing 
    unauthorized: authentication required

**Comment by stevvooe** [comment] 2016-04-18 20:11
@aug-riedinger The suggested fix is called out in https://github.com/docker/distribution/issues/1165#issuecomment-155190893. If you're still having problems, make sure to compare your configuration thoroughly and understand each parameter.

 @gtirloni I'm not sure what you're asking. It doesn't look like you're working with a private registry, so it is unlikely this particular issue applies to your situation.

**Comment by gtirloni** [comment] 2016-04-18 20:14
@stevvooe yes, I'm not using a private registry. This is happening on Docker Hub, so I've contacted support. Thanks.

**Comment by stevvooe** [comment] 2016-04-18 20:17
@gtirloni Great!

**Comment by zhiwu88** [comment] 2016-04-20 09:37
@gtirloni   hi，have you fix it now ?

**Comment by stevvooe** [comment] 2016-04-20 21:53
@zhiwu88 Please contact support.docker.com.

**Comment by asheshambasta** [comment] 2016-05-13 09:15
Seeing this issue;
```
-> % docker --version
Docker version 1.11.1, build 5604cbe
```

**Comment by rrnewton** [comment] 2016-05-15 04:19
Having this problem on dockerhub as well.

**Comment by cnwarden** [comment] 2016-05-16 08:46
also has this problem.
`
$ docker version
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-25.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      78ee77d/1.9.1
 Built:
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-25.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      78ee77d/1.9.1
 Built:
 OS/Arch:         linux/amd64
`

**Comment by vtolstov** [comment] 2016-05-16 16:03
ping!

**Comment by vtolstov** [comment] 2016-05-16 16:03
i'm have thsi problem too. i'm try to push to hub.docker.com

**Comment by gtirloni** [comment] 2016-05-16 16:07
My issue turned out to be a defective Docker that was shipped by CentOS alone (v1.9.1). The official Docker package did not show this issue. This was fixed in recent packages in Fedora (v1.10 and later).

Your ~/.docker/config.json should look like this after `docker login`:

```
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "token",
			"email": "user@example.com"
		}
	}
}
```

Fix the URL in case it's not the same and it should work.

**Comment by vtolstov** [comment] 2016-05-16 21:49
Thanks! this works =)

**Comment by swaroopkundeti** [comment] 2016-05-18 19:29
The push refers to a repository [docker.io/organization/proxy] (len: 1)
d54c4fess0a0: Preparing 
unauthorized: authentication required

**Comment by TheLoneRanger14** [comment] 2016-05-20 13:27
even after following @gtirloni 's comment, I get the same error :\

**Comment by wrfly** [comment] 2016-05-21 08:16
```bash
docker info:
Username: wrfly
Registry: https://index.docker.io/v1/
➜  ~ docker push dao_api:latest       
The push refers to a repository [docker.io/library/dao_api]
e89cc27b9b92: Preparing 
c27eefc1663f: Preparing 
d6138eddb0fd: Preparing 
5f70bf18a086: Preparing 
4592214fdfc9: Preparing 
3f9e224fca30: Image push failed 
e12b76467769: Waiting 
unauthorized: authentication required
➜  ~ sudo apt upgrade docker.io
Reading package lists... Done
Building dependency tree       
Reading state information... Done
docker.io is already the newest version (1.10.3-0ubuntu6).
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
➜  ~ 
```

Same error... How to play?

**Comment by rickmed** [comment] 2016-05-23 00:12
+1!!

**Comment by TheLoneRanger14** [comment] 2016-05-23 00:17
My mistake was I was not using the proper name hierarchy. one your local machine the name can be anything, but if you are pushing it into a hub with a username <tester>, it should be of the format
`<tester>/<reponame>`, where reponame is anything. 

Then only you are allowed to push into that repo.

I changed it accordingly and now able to push correctly :)

**Comment by keerthiadu** [comment] 2016-05-23 22:32
+1!!!

**Comment by RichardScothern** [comment] 2016-05-23 22:54
Please stop commenting on closed issues especially with `+1` both are against the guidelines of this project:
https://github.com/docker/distribution/blob/master/CONTRIBUTING.md#reporting-an-issue-properly

If you have read through the thread and nothing has solved your issue, read the above document and then open a new issue.

**Comment by stevvooe** [comment] 2016-05-24 03:06
Locking conversation. Sorry.

If you're seeing issues related to this, please open another issue referencing this one.

**Comment by dmp42** [comment] 2016-05-24 16:42
This issue conflates together many (at least four) different, unrelated problems:

 * defective docker packages shipped by distro maintainers (to be addressed by using official Docker packages instead)
 * issues with Hub operations (to be addressed by support@docker.com)
 * PEBCAK
 * rados driver issue (this driver has been deprecated in favor of a swift gateway)

... none of them (but the rados one) being actionable.

In that context, further commenting on this issue is entirely useless (both to reporters and maintainers), which is why we locked it, and encourage people facing "similar symptoms" to open a proper new issue with specific enough information to be actionable, as stated before (https://github.com/docker/distribution/blob/master/CONTRIBUTING.md#reporting-an-issue-properly).

Thanks.
