### ISSUE TITLE
Registry SWIFT backend create directories with long filenames of 284 chars, making backups on a filesystem impossible

### ISSUE THREAD

**Issue by zoobab** [docker/distribution#2311] opened 2017-06-20 08:17 UTC
Hi,

I am trying to backup a SWIFT volume of a registry.

The docker registry appears to create directories like this:
```
CloudFiles/Containers/myregistry/segments/2f646f636b65722f72656769737472792f76322f7265706f7369746f726965732f62757379626f782f5f75706c6f6164732f32303934663265382d636565642d346165652d396336332d3465643234653230653932322f6461746188d844f2e21d3c105ef84989a563e45cebeed52752a43737a4732f90b7d38018da39a3ee5e6b4b0d3255bfef95601890afd80709/0000000000000001
```

When you try to backup those files by copying them to a standard linux filesystem, you will hit a 255 filename limitation.

Here with the rclone tool:

```
2017/06/20 07:53:08 segments/2f6/46f636b65722f72656769737472792f76322f7265706f7369746f726965732f616c70696e653335366d2f5f75706c6f6164732f63343361313531662d383338342d343861372d626232302d3433643664383661643336302f64617461625f4826b57e72ee3dd0159e6442df9b3361759f1a6fa7ca80d823498ac6db49da39a3ee5e6b4b0d3255bfef95601890afd80709/0000000000000001: Failed to copy: mkdir /test79/segments/2f6/46f636b65722f72656769737472792f76322f7265706f7369746f726965732f616c70696e653335366d2f5f75706c6f6164732f63343361313531662d383338342d343861372d626232302d3433643664383661643336302f64617461625f4826b57e72ee3dd0159e6442df9b3361759f1a6fa7ca80d823498ac6db49da39a3ee5e6b4b0d3255bfef95601890afd80709: file name too long
```

But you can also reproduce with a simple mkdir on your linux box:

```
$ mkdir 46f636b65722f72656769737472792f76322f7265706f7369746f726965732f616c70696e653335366d2f5f75706c6f6164732f63343361313531662d383338342d343861372d626232302d3433643664383661643336302f64617461625f4826b57e72ee3dd0159e6442df9b3361759f1a6fa7ca80d823498ac6db49da39a3ee5e6b4b0d3255bfef95601890afd80709
mkdir: cannot create directory '46f636b65722f72656769737472792f76322f7265706f7369746f726965732f616c70696e653335366d2f5f75706c6f6164732f63343361313531662d383338342d343861372d626232302d3433643664383661643336302f64617461625f4826b57e72ee3dd0159e6442df9b3361759f1a6fa7ca80d823498ac6db49da39a3ee5e6b4b0d3255bfef95601890afd80709': File name too long
```
If you try the swift tool part of the openstack python package, you will hit the same problem.

Does anybody has a workaround for this (kernel patch, kernel tuning, special filesystem...)?

Could the devs shorten the directory name to a shorter length for the future?

**Comment by stevvooe** [comment] 2017-07-18 21:02
These don't look like paths created by this version of the registry. Typically, these can be around 64 characters for hashes, but we took measures to limit the path length.

What version of the registry are you using?

**Comment by zoobab** [comment] 2017-07-22 14:42
As far as I can remember, this was done with a 2.5 or 2.6. Can you reproduce? I had push a simple busybox image over there.

**Comment by stevvooe** [comment] 2017-07-24 17:56
@zoobab We cannot reproduce. These paths don't even look like paths created by this particular registry.

Without a particular version or more information, I am going to have to close this down. Let me know if you have more information.

**Comment by JordanSussman** [comment] 2017-08-24 01:51
I'm seeing this same behavior with version 2.6.2. Current setup is using the registry as a pull through cache. I can consistently reproduce the issue by pulling a image from a fresh swift container.

View empty container contents: 
`$ curl - i - H "Accept: application/json" https: //<container url>`

```json
{
    "Tenant": "tenant",
    "Name": "container-name",
    "Prefix": "",
    "Marker": "",
    "MaxKeys": 1000,
    "IsTruncated": "false"
}
```

Pull a new image that isn't cached:
`$ docker pull busybox:latest`

View the container contents 
`$ curl - i - H "Accept: application/json" https: //<container url>`

```json
{
  "Tenant": "tenant",
  "Name": "container-name",
  "Prefix": "",
  "Marker": "",
  "MaxKeys": 1000,
  "IsTruncated": "false",
  "Contents": ["files\/docker\/registry\/v2\/blobs\/sha256\/ad\/add3ddb21edebb102b552fc129273216bf6312f5f1519d7c1401864a2810738b\/data", "2017-08-24T01:40:48.882Z", "\"d41d8cd98f00b204e9800998ecf8427e\"", 0, "STANDARD", {
    "ID": "tenant$tenant",
    "DisplayName": "docker-registry"
  }],
  "Contents": ["files\/docker\/registry\/v2\/blobs\/sha256\/b8\/b82b5740006c1ab823596d2c07f081084ecdb32fd258072707b99f52a3cb8692\/data", "2017-08-24T01:40:40.720Z", "\"8419767996bb92bda744bfc45da2be98\"", 527, "STANDARD", {
    "ID": "tenant$tenant",
    "DisplayName": "docker-registry"
  }],
  "Contents": ["files\/docker\/registry\/v2\/blobs\/sha256\/d2\/d20ae45477cbc89863fff11d01cdccf28e4ff06ce2eb2f0206ef971b14eaf6c0\/data", "2017-08-24T01:40:48.729Z", "\"d41d8cd98f00b204e9800998ecf8427e\"", 0, "STANDARD", {
    "ID": "tenant$tenant",
    "DisplayName": "docker-registry"
  }],
  "Contents": ["files\/docker\/registry\/v2\/repositories\/library\/busybox\/_layers\/sha256\/add3ddb21edebb102b552fc129273216bf6312f5f1519d7c1401864a2810738b\/link", "2017-08-24T01:40:48.909Z", "\"6133f8e93ffa893feb0faf70fc07710e\"", 71, "STANDARD", {
    "ID": "tenant$tenant",
    "DisplayName": "docker-registry"
  }],
  "Contents": ["files\/docker\/registry\/v2\/repositories\/library\/busybox\/_layers\/sha256\/d20ae45477cbc89863fff11d01cdccf28e4ff06ce2eb2f0206ef971b14eaf6c0\/link", "2017-08-24T01:40:48.753Z", "\"8b6eb24481a7269bdcec38fe19e23441\"", 71, "STANDARD", {
    "ID": "tenant$tenant",
    "DisplayName": "docker-registry"
  }],
  "Contents": ["files\/docker\/registry\/v2\/repositories\/library\/busybox\/_manifests\/revisions\/sha256\/b82b5740006c1ab823596d2c07f081084ecdb32fd258072707b99f52a3cb8692\/link", "2017-08-24T01:40:40.731Z", "\"4a1c997aa233ff44506f2a4d637d02ef\"", 71, "STANDARD", {
    "ID": "tenant$tenant",
    "DisplayName": "docker-registry"
  }],
  "Contents": ["files\/docker\/registry\/v2\/repositories\/library\/busybox\/_manifests\/tags\/latest\/current\/link", "2017-08-24T01:40:48.051Z", "\"4a1c997aa233ff44506f2a4d637d02ef\"", 71, "STANDARD", {
    "ID": "tenant$tenant",
    "DisplayName": "docker-registry"
  }],
  "Contents": ["files\/docker\/registry\/v2\/repositories\/library\/busybox\/_manifests\/tags\/latest\/index\/sha256\/b82b5740006c1ab823596d2c07f081084ecdb32fd258072707b99f52a3cb8692\/link", "2017-08-24T01:40:48.036Z", "\"4a1c997aa233ff44506f2a4d637d02ef\"", 71, "STANDARD", {
    "ID": "tenant$tenant",
    "DisplayName": "docker-registry"
  }],
  "Contents": ["files\/scheduler-state.json", "2017-08-24T01:40:49.077Z", "\"5eb513a78ae6870c99686e9f0372f44f\"", 745, "STANDARD", {
    "ID": "tenant$tenant",
    "DisplayName": "docker-registry"
  }],
  "Contents": ["segments\/2f6\/46f636b65722f72656769737472792f76322f7265706f7369746f726965732f6c6962726172792f62757379626f782f5f75706c6f6164732f61383761336537632d303862362d343232392d616538642d3236346233306235386631642f6461746185df55a1d25e4b368d96563860fa5e0d868e9a89a98b57418a59bb9e5ad4b33cda39a3ee5e6b4b0d3255bfef95601890afd80709\/0000000000000001", "2017-08-24T01:40:48.809Z", "\"9fedf5fb184f14cd209267cc57678f67\"", 715181, "STANDARD", {
    "ID": "tenant$tenant",
    "DisplayName": "docker-registry"
  }],
  "Contents": ["segments\/2f6\/46f636b65722f72656769737472792f76322f7265706f7369746f726965732f6c6962726172792f62757379626f782f5f75706c6f6164732f63666332313963612d323334302d346463342d383363642d3938633330383761623461622f64617461c1009ab80d489ba8d5ec1a63b6be265093be269d15421f528f31bba0bcf086a2da39a3ee5e6b4b0d3255bfef95601890afd80709\/0000000000000001", "2017-08-24T01:40:48.671Z", "\"b1268ddc8ebec11370eb7cc46cc9f729\"", 1507, "STANDARD", {
    "ID": "tenant$tenant",
    "DisplayName": "docker-registry"
  }]
}
```

Happy to provide more info as required.

**Comment by stevvooe** [comment] 2017-08-31 01:13
@JordanSussman Is there a limit on path lengths for swift? Is it possible this is a bug on swift?

We haven't seen this before and, like I said, the "segments" paths are not created by registry code, as far as I know.

**Comment by stevvooe** [comment] 2017-08-31 01:16
Looks like these are indeed created by the swift driver. These are assembled in https://github.com/docker/distribution/blob/master/registry/storage/driver/swift/swift.go#L651.

@lebauce PTAL

**Closed** 2019-07-11 22:35 UTC
