### ISSUE TITLE
Changing a host port number for private registry re-pushes all the metadata for an image, though the image already exists on mounted folder

### ISSUE THREAD

**Issue by monikakatiyar16** [docker/distribution#1997] opened 2016-10-12 09:34 UTC
Followed the following steps -
1. Host name set to privateregistry.net:5044
2. Push an image A
3. Change the port number - privateregistry.net:5045
4. Push the same image again.

It shows Pushing==> , which gives a feeling that the whole image is pushed again.
On checking the backend file system, it was found that only the metadata is updated (_manifests, _layers)

We have the host name and port number configurable.
Why does it update these files, which contain only the links to the actual data again on re-pushing the same image? Is it updated, since the canonical names have to be updated within the docker?

**Comment by monikakatiyar16** [comment] 2016-10-12 10:43
1 GB image pushed with host port 5044 took time : 1:03:55 min
Same 1 GB image pushed with the host port changed to 5045 - took time : 1:01:91 min

**Comment by RichardScothern** [comment] 2016-10-12 17:21
*Please follow these instructions to help us diagnose your issue*

 2. copy the output of:
   - `docker version`
   - `docker info`
   - `docker exec <registry-container> registry -version`
 3. copy the command line you used to launch your Registry
 4. restart your docker daemon in debug mode (add `-D` to the daemon launch arguments)
 5. reproduce your problem and get your docker daemon logs showing the error
 6. if relevant, copy your registry logs that show the error
 7. provide any relevant detail about your specific Registry configuration (e.g., storage backend used)

**Comment by RichardScothern** [comment] 2016-10-12 17:21
Can you clarify step 3.  Are you retagging the image?

**Comment by monikakatiyar16** [comment] 2016-10-13 06:51
1. **docker version**
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

**docker info**
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 51
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 66
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null overlay host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.691 GiB
Name: monikak-Latitude-E7450
ID: XKHJ:RXCH:DHO4:NQK3:GDE7:43YG:JGI2:C2IA:GV7S:DS42:VVQ7:JWG5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**registry -version** : 2.5

2. Launching the registry using **docker-compose** with nginx:1.9 as a proxy 
version: '2'
services:
  nginx:
    image: "nginx:1.9"
    ports:
    - **5043:5043**
    links:
    - registry:registry
    volumes:
    - ./nginx/:/etc/nginx/conf.d:ro
    volumes_from:
    - registry
  registry:
    image: registry:2.5
    ports:
    - **5000:5000**
    environment:
     REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /regdata
    volumes:
    - ./regdata:/regdata

Step 3, 4,5 : No errors logged by docker daemon or registry

6. Data mounted using File System driver to a folder called regdata


NGINX Configuration -
upstream registry {
  server registry:**5000**;
}
server {
  listen **5043**;
location /v2/ {
    # Do not allow connections from docker 1.5 and earlier
    # docker pre-1.6.0 did not properly set the user agent on ping, catch "Go *" user agents
    if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
      return 404;
    }

    proxy_pass                          http://registry;
    proxy_set_header  Host              $http_host;   # required for docker client's sake
    proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
    proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header  X-Forwarded-Proto $scheme;
    proxy_read_timeout                  900;
  }
}


Steps to reproduce the issue -
1.  For testing purpose made an entry for private registry in /etc/hosts as 
127.0.0.1  privateregistry.net
2. Run the docker with the current configuration - nginx proxy port as 5043 in docker-compose and nginx conf file, using docker-compose up --build
3. Tag an image, say debian:jessie
 docker tag debian:jessie privateregistry.net:5043/debian:jessie
4. Push the image
docker push privateregistry.net:5043/debian:jessie
5. Stop the docker using docker-compose stop
6. Change the nginx proxy port as 5044 in docker-compose and nginx conf file and re-run using docker compose up --build
7. Tag and push again 
 docker tag debian:jessie privateregistry.net:5044/debian:jessie
docker push privateregistry.net:5044/debian:jessie

The push refers to a repository [privateregistry.net:5044/debian]
142a601d9793: Pushing [========================================>          ] 99.66 MB/123 MB
jessie: digest: sha256:d48e84975ba0184501cfd789283323dd4912dcc037afff50aa86bcd91048f4e5 size: 529

The question is why does it push the image again, when its already present on the file system?

**Comment by monikakatiyar16** [comment] 2016-10-13 07:12
Also, tried running the same using registry binary and nginx binary. It gives the same results.

**Comment by RichardScothern** [comment] 2016-10-14 16:39
> The question is why does it push the image again (actually only the link files in _layers and _manifests), when its already present on the file system?

Your description shows the blob being pushed, so it's not just the metadata that's being updated. The image manifest is always pushed.  The blobs are `stat`ed and not uploaded if they exist in the same repository, and are mounted from other repositories wherever possible. 

What do your registry logs show for these stat events?

**Comment by monikakatiyar16** [comment] 2016-10-14 16:52
@RichardScothern
I checked the created date and time for the data, config and schema file in the blobs folder. I found that it contained the old date and time, which made me assume that the actual blob was not pushed.

I follow IST timings and don't have access right now. I will get the debug logs for stat on monday and share them with you.

**Comment by monikakatiyar16** [comment] 2016-10-17 07:50
@RichardScothern 
I found that the issue occurs only when the frontend port is changed.
Tested the scenario by changing the mapping in docker compose and conf file as follows -
1. 5043:5043
2. 5044:5044
3. **5045:5044**

For the first and second one, it shows layer already exists. For the third one only, it shows the output as shown above.

**Comment by monikakatiyar16** [comment] 2016-10-17 08:54
@RichardScothern 
Uploading the debug logs for the above three use cases -

[Docker port debug.docx](https://github.com/docker/distribution/files/532793/Docker.port.debug.docx)

**Comment by dmcgowan** [comment] 2016-10-18 20:53
@monikakatiyar16: if you are haven't cleared your graph directory between attempts the already exist message will show up if the registry already contains the layer hash. Docker keeps a record of which hashes have been pulled from which registry. When you change the port Docker sees it as a different registry and will therefore re-push the content. Since there is no hash to check for existence with the new registry, the content is pushed. After the push has completed, the registry computes the hash and checks if the content already exists on the backend, if it does then there are no updates to the registry backend, only metadata for the repository will be updated. On the Docker engine side though, a record will be kept with the hash of the pushed content to the new registry. Closing this since it is expected behavior, feel free to ask questions if you want further clarification.

**Closed by dmcgowan** 2016-10-18 20:53 UTC

**Comment by monikakatiyar16** [comment] 2016-10-19 07:25
@RichardScothern  @dmcgowan 

Please answer the following queries : 
1. Shouldn't the private registry name (without the port no) be considered for keeping the record of hash of pushed content? Can you please explain the reason and scenarios, why are we considering the port number too? I am using file system for storage. Does it make any difference when storing the images on AWS or similar storages?

2. If hash access is affected by changing the port number, then why it doesn't create any problem when changing the ports from  5043:5043 to 5044:5044 ? Why does it create this issue only when the front port is changed as 5045:5044?

**Comment by monikakatiyar16** [comment] 2016-10-19 07:38
The technical part that you have explained for docker justifies this behavior (Except for the changing both the ports to 5044:5044).

A domain name will always remain the same, but if a port fails due to some reasons and needs to be changed, all the images (say if 1000 images existed on the system, before changing the port) can be pushed showing Pushing==> whenever any user pushes any image, instead of layer already exists?


Pull for the image happens however in all the three scenarios mentioned above. Will it make any impact on the images? For pull, docker does the hash check or is it only during the pull?

**Comment by dmcgowan** [comment] 2016-10-20 18:09
> Shouldn't the private registry name (without the port no) be considered for keeping the record of hash of pushed content? 

No, we consider the port number relevant for identifying a host. This is mostly useful for testing and development environments. Larger deployments should not use multiple hosts to refer to the same registry since Docker will refer to these as different images.

> Can you please explain the reason and scenarios, why are we considering the port number too?

Different ports are different images as defined by our image reference specification https://godoc.org/github.com/docker/distribution/reference. It is common practice for ports to be considered part of the host name, this is because when a host is user facing often the port is implicit (80 or 443) and it is only explicitly used to refer to different hosts under the same domain name. The same is true for Docker images, different port numbers are used to refer to different registry hosts.

> I am using file system for storage. Does it make any difference when storing the images on AWS or similar storages?

No, currently the registry does not consider the hostname in deciding where to store image content, from the registry perspective only the part after the hostname is considered. We hope to make this configurable int he future but today it will not make a difference.

> If hash access is affected by changing the port number, then why it doesn't create any problem when changing the ports from 5043:5043 to 5044:5044 ? Why does it create this issue only when the front port is changed as 5045:5044?

There is no different between 5043 -> 5044 vs 5045 -> 5044, the behavior you saw is likely from the hash metadata staying around after you moved the image tag to one of the hosts. As I mentioned before, when testing this behavior it is probably best to clear out the /var/lib/docker directory to ensure there is no leftover metadata.


> A domain name will always remain the same, but if a port fails due to some reasons and needs to be changed, all the images (say if 1000 images existed on the system, before changing the port) can be pushed showing Pushing==> whenever any user pushes any image, instead of layer already exists?

We don't consider using multiple ports as a good strategy for maintaining high availability of the registry. You should front multiple registries either using a load balanced like nginx (which you made mention of) or having your registries on different hosts listening on the same port and use round robin DNS.

> If the front port fails or has any issues and needs to be changed (rare scenario, but can happen), the solution would be right now to change the front port used in the domain name and the port that nginx is listening to? Would it be mandatory to keep both the ports same to avoid this behavior?

You should not need to change your host when you have a registry failure. If you are using a proxy or load balancer the front port should not be changed, the backend ports can change without any effect to Docker. Docker will only see the front ended port. If your front end fails then you might need redundancy there as well or switch to a more reliable load balancer :smile:

> Pull for the image happens however in all the three scenarios mentioned above. Will it make any impact on the images? For pull, docker does the hash check or is it only during the pull?

The hash metadata I was referring to is only relevant on push (it uses this metadata to check if the registry already has it). On pull, Docker will always verify the hash of the content and update its metadata for the registry in which the image was pulled from. As long as you are exposing the same host (same domain name and same front end), Docker will re-use the metadata even if there are multiple registries behind the load balancer.

**Comment by monikakatiyar16** [comment] 2016-10-20 19:08
That makes sense.. :)

Can you please answer one more question? /var/lib/docker stores all the docker images on my local system. If I push any image to private registry with its file system mounted on a different machine, will it make a reference check for hash in /var/lib/docker? I have noticed that the folder structure is different from the one that is mounted for private registry. Do we store the hashes you mentioned in /var/lib/docker, even while using private registry? Or might be I am not able to understand it right.
