### ISSUE TITLE
Docker should support registry URI prefix

### ISSUE THREAD

**Issue by alonbl** [docker/distribution#2267] opened 2017-05-05 21:13 UTC
Hi,

I am sure this was discussed already, however, I did not find any relevant information and in latest it is not resolved.

A configuration in which a registry is installed alongside with other components on the same HTTP server should be supported. Assumption of dedicated IP/port requires lots of resources.

The docker-distrubution supports prefix configuration option to have endpoint located under a specific prefix, and an http proxy can proxy to that prefix for example https://xxx/registry -> http://localhost:5000/registry.

However, for some reason docker accepts only a proprietary format of registry location, and it seems like it is hard-wired somewhere deep inside the code so that a prefix cannot be used.

In order to preserve the proprietary format and allow custom URLs, I suggest somekind of translation table in configuration between the registry NAME and a URL.

I hope there is already such capability, and if not please consider to add such.

Thanks!

**Comment by stevvooe** [comment] 2017-07-18 21:16
The registry can do this, but I am not sure about docker support. The problem is not "only a proprietary format of registry location" but that there are some configuration details that need to be worked out.

I'd recommend that you file this request with `moby/moby` and work from there, as it is that project where the fix needs to happen.

I'm closing this for now. Let me know if we need more discussion here.

**Closed by stevvooe** 2017-07-18 21:16 UTC

**Comment by alonbl** [comment] 2017-07-18 21:33
Hi,
What is moby/moby in this context?
Thanks!

**Comment by stevvooe** [comment] 2017-07-18 21:56
The moby project: https://github.com/moby/moby.
