### ISSUE TITLE
Update the docs/configuration.md file with information from configuration/README.md

### ISSUE THREAD

**Issue by moxiegirl** [docker/distribution#458] opened 2015-04-28 16:46 UTC
The https://github.com/docker/distribution/tree/master/configuration/README.md contains information that didn't make it into the documentation.

```
[2015-04-28 09:37:11] <richard> Hi Mary
[2015-04-28 09:37:18] <richard> I've just noticed this: https://github.com/docker/distribution/tree/master/configuration#environment-variables 
[2015-04-28 09:37:34] <richard> which is the documentation on environment variables that I thought existed
[2015-04-28 09:37:58] <richard> [mary] lol
[2015-04-28 09:38:17] <richard> [mary] not in the documentation directory
[2015-04-28 09:38:34] <richard> yes, this is configuration/README.md
[2015-04-28 09:39:33] <richard> [mary] We should probably keep the documentation in a single location; this doesn't appear as complete as docs/configuration.md
[2015-04-28 09:39:51] <richard> I agree - there should only be one
[2015-04-28 09:40:05] <richard> [mary] Are y'all using README in each "component" directory?
[2015-04-28 09:40:12] <richard> I have no idea
[2015-04-28 09:40:14] <richard> :)
[2015-04-28 09:40:38] <richard> [mary] Hmm, yeah, so like in a component directory a README is nice to explain to programmers how to change stuff or add  to tests
[2015-04-28 09:40:49] <richard> [mary] maybe even have a link to PRs against the component...
[2015-04-28 09:40:58] <richard> [mary] course, that is MO
[2015-04-28 09:41:14] <richard> [mary] "mary's opinion"
[2015-04-28 09:41:15] <richard> [mary] lol
[2015-04-28 09:42:02] <richard> haha
[2015-04-28 09:42:13] <richard> [mary] the note here is interesting
[2015-04-28 09:42:29] <richard> [mary] If an environment variable changes a map value into a string, such as replacing the storage driver type with REGISTRY_STORAGE=filesystem, then all sub-fields will be erased. As such, specifying the storage type in the environment will remove all parameters related to the old storage configuration.
[2015-04-28 09:42:32] <richard> [mary] we don't have that in the docs
[2015-04-28 09:42:47] <richard> [mary] they aren't literally removed are they?
[2015-04-28 09:42:52] <richard> [mary] just ignored
[2015-04-28 09:43:06] <richard> [mary] or overridden
[2015-04-28 09:43:17] <richard> oh
[2015-04-28 09:43:30] <richard> yeah; they just won't be read from the config file
[2015-04-28 09:44:13] <richard> [mary] we should add that to the doc and edit this I'll create an issue for tracking purposes.  Right now, I'm working on a big project schedule for Dockercon and I'm only doing essential stuff right away
[2015-04-28 09:44:20] <richard> ok
```

Closing this ticket:

- [ ] Merge information from configuration/README into docs/configuration.md
- [ ] Remove docs/configuration.md.

**Comment by stevvooe** [comment] 2015-04-28 17:46
Is this a duplicate of #401?

**Comment by moxiegirl** [comment] 2015-04-28 17:48
@stevvooe this one has some extra issue --- in particular the README has some information that didn't make it into the actual documentation.  Not sure which you want to close. This is later but more complete.

**Comment by stevvooe** [comment] 2015-04-28 19:41
@moxiegirl We should get rid of the errant README.

**Closed** 2015-05-06 22:53 UTC
Labels: bug, documentation, duplicate, in progress
