### ISSUE TITLE
docker registry api In the registry 2.3 version of the problem

### ISSUE THREAD

**Issue by hassanlhx** [docker/distribution#1564] opened 2016-03-26 16:17 UTC
In the registry2.3 version of docker push  returns digest and registry API docker return digest different, this is what the situation?This is not the case in the registry2.3.0 version.
==============================================================================
root@VM-60-189-ubuntu:/home/ubuntu/registry_config# docker push 10.105.60.189:5000/busybox
The push refers to a repository [10.105.60.189:5000/busybox]
5f70bf18a086: Pushed 
1834950e52ce: Pushed 
latest: digest: sha256:6757d4b17cd75742fc3b1fc1a8d02b45b637f2ac913ee9669f5c2aed0c9b26ba size: 711

=============================================================================
root@VM-60-189-ubuntu:/home/ubuntu/registry_config# curl -i http://10.105.60.189:5000/v2/busybox/manifests/latest
HTTP/1.1 200 OK
Content-Length: 2561
Content-Type: application/vnd.docker.distribution.manifest.v1+prettyjws
Docker-Content-Digest: sha256:e45f25b1760f616e65f106b424f4ef29185fbd80822255d79dabc73b8eb715ad
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:e45f25b1760f616e65f106b424f4ef29185fbd80822255d79dabc73b8eb715ad"
X-Content-Type-Options: nosniff
Date: Sat, 26 Mar 2016 15:48:36 GMT

**Comment by fishtek** [comment] 2016-03-28 16:24
This is causing issues for me as well, when I try to delete like @7AC is running into over in #1565

**Comment by fishtek** [comment] 2016-03-28 17:27
Just figured this out... it appears you have to [include an "accept" header](https://github.com/docker/distribution/blob/c8d8e7e357a1e5cf39aec1cfd4b3aef82414b3fc/docs/spec/manifest-v2-2.md) for the newer version of the manifest schema... (probably if we have the newer client side that did the push), so that the repo calculates the proper digest.  

I was able to get a Digest that matches my push (and which I can use for the Delete) like so:
`curl -H "Accept: application/vnd.docker.distribution.manifest.v2+json" -k -v -X GET https://dns-name-of-repo/v2/image-name/manifests/latest`

**Comment by RichardScothern** [comment] 2016-03-28 17:49
closing as duplicate of #1565

**Closed by RichardScothern** 2016-03-28 17:49 UTC
