### ISSUE TITLE
docker 1.[6,7,8] private registry image not found after update to 2.1

### ISSUE THREAD

**Issue by Deshke** [docker/distribution#884] opened 2015-08-17 15:15 UTC
after the update from the registry to 2.1 i'm not been able to "extract" images

```bash
WARNING: login credentials saved in /var/lib/jenkins/.docker/config.json
Login Succeeded
pushing docker image 0fd658e25fd8 from 06bdc8f-1508171450 to docker-registry.tld:5043/repo/ingest_preview:06bdc8f-1508171450
The push refers to a repository [docker-registry.tld:5043/repo/ingest_preview] (len: 1)
0fd658e25fd8: Buffering to Disk
0fd658e25fd8: Image successfully pushed
2db0b56a609c: Buffering to Disk
2db0b56a609c: Image successfully pushed
b0c1250074dc: Buffering to Disk
b0c1250074dc: Image successfully pushed
17bcfa6397dc: Buffering to Disk
17bcfa6397dc: Image successfully pushed
eb99a556e061: Buffering to Disk
eb99a556e061: Image successfully pushed
2f78cb7c220f: Buffering to Disk
2f78cb7c220f: Image successfully pushed
06bdc8f-1508171450: digest: sha256:4c41b80e63a3b7e02d0ca8415c7e2da90cd90e2aec2d176142e7ff79d03ab4fa size: 10607

....

docker login  docker-registry.tld:5043 
Username (repo-user): 
WARNING: login credentials saved in /root/.docker/config.json
Login Succeeded
root@HOSTNAME:~# docker pull docker-registry.tld:5043/repo/ingest_preview:06bdc8f-1508171450
06bdc8f-1508171450: Pulling from repo/ingest_preview
2f78cb7c220f: Extracting 3.342 MB/304.3 MB
eb99a556e061: Download complete 
17bcfa6397dc: Download complete 
b0c1250074dc: Download complete 
2db0b56a609c: Downloading   253 MB/409.3 MB
0fd658e25fd8: Download complete 
Pulling repository docker-registry.tld:5043/repo/ingest_preview
Error: image repo/ingest_preview:06bdc8f-1508171450 not found

```

on the server side

```bash
docker --version
Docker version 1.8.1, build d12ea79

docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                           NAMES
0c8a73f15946        nginx:1.9           "nginx -g 'daemon off"   4 hours ago         Up 26 minutes       80/tcp, 0.0.0.0:5043->443/tcp   data_nginx_1
88599696747a        registry:2          "/bin/registry /etc/d"   4 hours ago         Up 26 minutes       127.0.0.1:5000->5000/tcp        data_registry_1

docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
registry            2                   2f1ef7702586        3 days ago          220.6 MB
nginx               1.9                 6886fb5a9b8d        4 weeks ago         132.9 MB

```

**Comment by dmp42** [comment] 2015-08-17 15:53
You are likely using registry 2.1.0. We issued a hotfix release as 2.1.1, and you should upgrade to that.

You can check what version of the registry you are using by issuing: `docker exec 88599696747a registry -version`

You can upgrade to the latest registry by simply reissuing `docker pull registry:2`, and restarting your container.

Let me know if you still have issues.

**Comment by Deshke** [comment] 2015-08-17 16:39
FYI 2.1.1 is in use

```bash
docker exec 88599696747a registry -version
registry github.com/docker/distribution v2.1.1

docker pull registry:2
2: Pulling from library/registry
6071b4945dcf: Already exists
5bff21ba5409: Already exists
e5855facec0b: Already exists
8251da35e7a7: Already exists
2d449bb18c75: Already exists
a5f051f1f664: Already exists
db95df628950: Already exists
4f780ec6d926: Already exists
8703b7c675b1: Already exists
97cf055388e0: Already exists
2f1ef7702586: Already exists
Digest: sha256:51303fea21187466ee786ee6291fc15967ff9a24c9943154a64a82a63ddf3594
Status: Image is up to date for registry:2

```

**Comment by dmp42** [comment] 2015-08-17 17:59
Ok, thanks for clarifying - reopening.

Can I ask you to perform the following?

 * start registry 2.0.1, do a successful pull, get the registry logs
 * start registry 2.1.1 instead, do a failing pull, get the registry logs

Thanks a lot.

**Comment by Deshke** [comment] 2015-08-17 18:01
i'll this tomorrow morning, what is the tag vor 2.0.1? docker pull registry:2.0.1?

**Comment by dmp42** [comment] 2015-08-17 18:19
@Deshke yes, that should work (or `2.0`)

**Comment by Deshke** [comment] 2015-08-18 08:20
registry 2.0.1 log https://gist.github.com/Deshke/27badd08b37660cabce5

**Comment by Deshke** [comment] 2015-08-18 08:43
registry 2.1.1 log https://gist.github.com/Deshke/04f72b6ca4bf2b29f898

**Comment by Deshke** [comment] 2015-08-18 11:12
update: got a solution, the client who pushes the image got rollbacked to docker 1.7.1 
```bash
docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

```

which solved the bug - with a docker client 1.8.* i can't push a image to a docker registry 2.*, with a 1.7 client it works

**Comment by stevvooe** [comment] 2015-08-18 21:18
@Deshke Could you enable debug level logging for 2.1.1?

Either way, looking at the registry access logs, I agree this might be a 1.8 problem. If the registry was at fault here, we should see a 404 or 500 during one of the requests. Let's still check the debug logs during push and make sure all the required files are present.

**Comment by Deshke** [comment] 2015-08-21 08:32
https://gist.github.com/Deshke/e5e7d55bd6869166e8ce

push with 1.8.1 client 

docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

and pull on  Amazon ECS-Optimized Amazon Linux AMI 2015.03.e

docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2/1.6.2
OS/Arch (server): linux/amd64

**Comment by stevvooe** [comment] 2015-08-21 17:29
@Deshke Looking at the logs, its clear the images are being returned by the registry. We can see from these log lines:

```
/v2/repo/frontend_preview/manifests/21ac0b0-1508211024 HTTP/1.0" 200
```

Would you mind filing this over in docker/docker?

**Comment by Deshke** [comment] 2015-08-21 18:58
i'll give it a try, could you leve this open?

**Comment by dmp42** [comment] 2015-08-21 20:12
Thanks @Deshke 

Any chance you can reach out on irc if we have more questions / tests? (#docker-distribution on freenode)

**Comment by Deshke** [comment] 2015-08-21 21:12
sure thing, just write me a pm, if it's not in the middle of the night i'll be there :)

**Comment by CpuID** [comment] 2015-08-29 09:14
I am seeing something similar to this, but an immediate not found on a pull with a 1.7.1 client (works with a 1.7.0 client, but not initially, had to fix auth).

What I can see here, is the docker CLI is trying the v2 registry URIs first, then falling back to the v1 URIs and getting a 404 on the v1 part. It actually fails with a 401 when trying to talk to /v2/ which I think is an issue with the path being changed that the docker CLI looks for it's auth token (using htpasswd auth within registry:2.1.1 here).

See log of HTTP requests (IPs and hostnames redacted) - note from whgat I can tell this is only a partial log output, but it gives you the idea:

```
{"environment":"undefined","http.request.host":"docker-registry-staging.domain.com:5000","http.request.id":"ff67eed1-f306-40ba-9378-ed837bbde555","http.request.method":"GET","http.request.remoteaddr":"10.x.x.x:48807","http.request.uri":"/v2/","http.request.useragent":"Go 1.1 package http","instance.id":"03bc86c2-151d-400f-b758-c6b265b5189d","level":"debug","msg":"authorizing request","service":"registry","time":"2015-08-29T09:04:40.252546235Z","version":"v2.1.1"}
{"environment":"undefined","http.request.host":"docker-registry-staging.domain.com:5000","http.request.id":"ff67eed1-f306-40ba-9378-ed837bbde555","http.request.method":"GET","http.request.remoteaddr":"10.201.10.61:48807","http.request.uri":"/v2/","http.request.useragent":"Go 1.1 package http","instance.id":"03bc86c2-151d-400f-b758-c6b265b5189d","level":"warning","msg":"error authorizing context: basic authentication challenge: htpasswd.challenge{realm:\"Internal Docker Registry\", err:(*errors.errorString)(0xc20809a9f0)}","service":"registry","time":"2015-08-29T09:04:40.252790646Z","version":"v2.1.1"}
10.201.10.61 - - [29/Aug/2015:09:04:40 +0000] "GET /v2/ HTTP/1.1" 401 114 "" "Go 1.1 package http"
{"environment":"undefined","http.request.host":"docker-registry-staging.domain.com:5000","http.request.id":"3259c59d-11df-41e2-becd-431751d07fff","http.request.method":"GET","http.request.remoteaddr":"10.201.10.61:48809","http.request.uri":"/v2/","http.request.useragent":"Go 1.1 package http","instance.id":"03bc86c2-151d-400f-b758-c6b265b5189d","level":"debug","msg":"authorizing request","service":"registry","time":"2015-08-29T09:04:40.325611611Z","version":"v2.1.1"}
{"environment":"undefined","http.request.host":"docker-registry-staging.domain.com:5000","http.request.id":"3259c59d-11df-41e2-becd-431751d07fff","http.request.method":"GET","http.request.remoteaddr":"10.201.10.61:48809","http.request.uri":"/v2/","http.request.useragent":"Go 1.1 package http","instance.id":"03bc86c2-151d-400f-b758-c6b265b5189d","level":"warning","msg":"error authorizing context: basic authentication challenge: htpasswd.challenge{realm:\"Internal Docker Registry\", err:(*errors.errorString)(0xc20809a9f0)}","service":"registry","time":"2015-08-29T09:04:40.325838011Z","version":"v2.1.1"}
10.201.10.61 - - [29/Aug/2015:09:04:40 +0000] "GET /v2/ HTTP/1.1" 401 114 "" "Go 1.1 package http"
10.201.10.61 - - [29/Aug/2015:09:04:40 +0000] "GET /v1/repositories/nathan/imagename/images HTTP/1.1" 404 19 "" "docker/1.5.0 go/go1.3.3 kernel/3.14.35-28.38.amzn1.x86_64 os/linux arch/amd64"
```

On my 1.7.0 client I was getting the same behaviour at first, then I found it wasn't actually asking to login (it found a ~/.dockercfg but it didn't have this registry hostname in it and it didn't ask for a login. I rm'ed the file, it then asked for credentials and wrote a file called ~/.docker/config.json instead). Since fixing the cfg file it now works correctly (OSX, different client to the logs above).

Pretty sure the underlying cause, is that it is trying to fallback to the v1 API if it gets a 401 on v2, when instead it should give up and go "not authorized". When it get's to the v1 API the 404 prevails giving the "not found" end result message.

**Comment by CpuID** [comment] 2015-08-31 21:00
As per my comment above, I suspect the issue is actually related to https://github.com/docker/docker/blob/master/graph/registry.go#L67-L70 not erroring on a 401.

**Comment by CpuID** [comment] 2015-08-31 21:15
Actually it may be possible when I said 1.7.0 client, I actually meant 1.5.0. Going to upgrade it now and test some stuff.

**Comment by CpuID** [comment] 2015-08-31 21:32
Confirmed, I was on 1.5.0, updated to 1.7.1, and new credentials were written to ~/.docker/config.json instead, and pulls work fine and are nice and fast for me. My "not found" issue is no more :)

**Comment by stevvooe** [comment] 2015-09-04 21:13
@CpuID If I understand you correctly, it sounds like this was a credentials issue.

@Deshke Could you confirm that works for you for 1.8.1?

**Comment by CpuID** [comment] 2015-09-04 21:55
@stevvooe pretty sure yea, I think there is an incompatibility note that belongs somewhere, but didn't bother doing enough testing to work out where (eg. certain older docker versions and newer v2 registries with certain types of auth file types etc)

**Comment by Deshke** [comment] 2015-09-04 22:54
@stevvooe sorry, cant confirm - didn't work for me

**Comment by stevvooe** [comment] 2015-09-05 00:42
@Deshke I suspect you're having a different issue than @CpuID. There is no v1 fallback in the original reported issue.

Let's take this discussion over to https://github.com/docker/docker/issues/15759 to ascertain the root cause. I'm closing this for now.

**Closed by stevvooe** 2015-09-05 00:42 UTC
Labels: question
