### ISSUE TITLE
Ceph and non-S3 S3-compliant storage systems

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#40] opened 2015-01-06 22:10 UTC
So, Ceph lack support for important parts of the S3 specification according to @BrianBland and @AndreyKostov , but it might be usable with a swift compatible driver.

ping @bacongobbler : any plans for a v2 swift driver? :)

**Comment by dmp42** [comment] 2015-01-07 00:02
Yeah, I don't know much about it (http://ceph.com/docs/next/radosgw/swift/). Needs to be looked into.
And yes, a swift driver would be swell :)

**Comment by jamshid** [comment] 2015-02-18 07:02
Hi, just curious, what's S3 features are needed that Ceph does not have?

**Comment by dmp42** [comment] 2015-02-18 08:26
Invoking @AndreyKostov for the gory details.

**Comment by AndreyKostov** [comment] 2015-02-18 18:51
It doesn't support the Upload Part Copy api that we use for WriteStream in the s3 driver

http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadUploadPartCopy.html

**Comment by jarus** [comment] 2015-04-16 23:27
Support of the Ceph Rados Gateway would be nice but I would prefer a pure Rados storage backend.

**Comment by bobrik** [comment] 2015-04-17 08:45
Can't s3 driver be implemented without Upload Part Copy mechanism?

**Comment by jarus** [comment] 2015-04-17 17:48
It looks like that the S3 client in Go doesn't support custom API domains.
https://github.com/AdRoll/goamz/blob/master/s3/s3.go#L853

**Comment by bacongobbler** [comment] 2015-04-17 17:55
We can always fork/PR fixes so we can accomplish that, but good to know! I'm currently tied down with some onboarding stuff because we just recently merged with Engine Yard but nobody picks this up then I'd be happy to contribute a driver (assuming that we can make it work)

**Comment by jamshid** [comment] 2015-04-19 04:16
Hoping this feature returns -- the previous python version supported S3-compatible storage systems by letting you specify the endpoint.

**Comment by AndreyKostov** [comment] 2015-04-20 16:50
The core of the issue is that the new registry storage driver api requires continuous uploads and the way the s3 driver currently implements that functionality is with the Upload Part Copy mechanism. 

If an s3 alternative does support Upload Part Copy, then supporting it is fairly easy, but if it doesn't it requires an s3 driver rewrite (that I am not even sure is possible while adhering to the current storage API)

**Comment by RichardScothern** [comment] 2015-04-20 17:17
Ceph does have append support within librados (see
http://ceph.com/docs/master/rados/api/librados/)

There are two possibilities:
1. A Ceph storage driver
2. Add Upload Part Copy to the Ceph S3 API

**Comment by stevvooe** [comment] 2015-04-20 19:42
@AndreyKostov @RichardScothern The better approach might be to have "logical files" in the backend. The main use case is to accept a bunch of offset-fixed chunk writes, then assemble them on "commit" of a blob.

Let's focus on getting resumable upload support fully integrated and then attack this issue. I suspect we need to break from the VFS-style API that we cribbed from V1. It incurs too many requirements on the backend drivers and provides nearly no benefit.

**Comment by bobrik** [comment] 2015-04-20 20:19
@stevvooe is there a goal to support storages that do not support resumable uploads?

**Comment by stevvooe** [comment] 2015-04-20 20:24
@bobrik That should be a possibility but the current design of the storage drivers doesn't really provide a method for a driver to communicate this. For example, it makes more sense for a storage driver to not implement `LayerUpload.Resume` rather than have it subtly fail on writing offsets to a file. The latter is much more explicit and reliable.

**Comment by dmp42** [comment] 2015-07-22 23:03
Ceph has been implemented.

**Closed** 2015-07-22 23:03 UTC
Labels: feature, question
