### ISSUE TITLE
Graceful handling of client disconnects

### ISSUE THREAD

**Issue by RichardScothern** [docker/distribution#597] opened 2015-06-05 00:44 UTC
When a client disconnects during a registry operation, a 400 error is logged.   These mask true 400 errors, making bug hunting in Kibana more difficult.

We should detect a client disconnect in the registry and return a non-error.

**Comment by aaronlehmann** [comment] 2015-07-24 20:43
I can reproduce this by telneting in and sending:

    PUT /v2/reponame/manifests/a HTTP/1.1
    Content-Length: 1000

and then disconnecting.

It seems that the handler gets triggered whether or not the HTTP client sent the expected amount of data before disconnecting (as one would expect). I'll look into using http.CloseNotifier to get notified about a disconnect while reading the request body, and handling this case separately from a truncated request.

**Comment by aaronlehmann** [comment] 2015-07-27 18:33
I tried using http.CloseNotifier and initially ran into the same problems @RichardScothern did when he tried it. gorilla's handlers package didn't expose this interface on its ResponseWriter wrapper, and neither did our own context package.

I was going to create a patch to gorilla/handlers to submit upstream, but I checked its recent PRs, and luckily a fix was merged just a week ago. The distribution/context package was trivial to fix, since it can expose CloseNotifier unconditionally.

After my change, the interrupted PUT request described above gives this output:

    time="2015-07-27T18:22:49.759253084Z" level=error msg="client disconnected during image manifest PUT" environment=development http.request.host= http.request.id=cd3bce5c-10e7-4521-b680-872e5223c898 http.request.method=PUT http.request.remoteaddr="192.168.99.1:61080" http.request.uri="/v2/reponame/manifests/a" http.request.useragent= instance.id=6f4cb1df-699f-439d-af27-b1448f2f03ba service=registry vars.name=reponame vars.reference=a version=v2.0.0-457-g29556ef.m 
    time="2015-07-27T18:22:49.759583549Z" level=info msg="response completed" environment=development http.request.host= http.request.id=cd3bce5c-10e7-4521-b680-872e5223c898 http.request.method=PUT http.request.remoteaddr="192.168.99.1:61080" http.request.uri="/v2/reponame/manifests/a" http.request.useragent= http.response.duration=2.904740271s http.response.status=0 http.response.written=0 instance.id=6f4cb1df-699f-439d-af27-b1448f2f03ba service=registry version=v2.0.0-457-g29556ef.m 
    192.168.99.1 - - [27/Jul/2015:18:22:46 +0000] "PUT /v2/reponame/manifests/a HTTP/1.1" 0 0 "" ""


I'm opening a PR.

**Comment by aaronlehmann** [comment] 2015-08-04 19:02
PR was merged; closing.

**Closed by aaronlehmann** 2015-08-04 19:02 UTC
Labels: enhancement, theme/ops-friendliness
