### ISSUE TITLE
408 Request time-out in logs

### ISSUE THREAD

**Issue by gschukin** [docker/distribution#1704] opened 2016-05-05 13:06 UTC
I'm facing 408 Request time-out in distribution logs

```
2016/05/01 16:30:26 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Time-out\r\nCache-Control: no-cache\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n"; err=<nil>
2016/05/01 16:30:26 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Time-out\r\nCache-Control: no-cache\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n"; err=<nil>
2016/05/01 16:30:26 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Time-out\r\nCache-Control: no-cache\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n"; err=<nil>
2016/05/01 16:30:27 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Time-out\r\nCache-Control: no-cache\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n"; err=<nil>
```

But unfortunately I'm unable to identify the root cause

**Comment by RichardScothern** [comment] 2016-05-05 16:46
What is your setup here?  Registry version, engine version, proxies?

What is the reproduction case?

**Comment by gschukin** [comment] 2016-05-05 16:56
@RichardScothern master at a1d7463d67bcf6ee87b7bd6bbcc3aeacf02e2d52

```
version: 0.1
log:
  level: debug
  fields:
    service: registry
    environment: development
storage:
  swift:
    username: REMOVED
    password: REMOVED
    authurl: REMOVED
    tenantid: REMOVED
    insecureskipverify: false
    container: DockerDistribution
    rootdirectory: /registry
  delete:
    enabled: false
  cache:
    blobdescriptor: redis
  maintenance:
    uploadpurging:
      enabled: false
      age: 168h
      interval: 24h
      dryrun: false
  redirect:
    disable: true
http:
    addr: :5000
    secret: 530cceaef4af43b989405690f067d7ae
    headers:
        X-Content-Type-Options: [nosniff]
redis:
  addr: 10.16.208.6:6379
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
```

```
docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   3cd164c
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   3cd164c
 Built:        
 OS/Arch:      linux/amd64
```
```
docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.5.2-coreos
Operating System: CoreOS 1032.0.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.864 GiB
Name: ariadne90.novalocal
ID: 756Q:I2RP:N2F4:MF32:XPOB:QHUO:OFLG:VRDB:6XGL:LTDG:OOHQ:7AY5
```
I have no proxies or LB between docker <--> registry <--> Swift

Found these errors during my load tests from this issue #1673 
My test case was quite simple - start 50 vm and pull an image, then another 50 and so on

**Comment by dmcgowan** [comment] 2016-11-21 18:33
Closing this as it appears to be related to behavior on the ceph server. If this is breaking something for you or you are able to find a root cause which can be fixed in the ceph driver please re-open

**Closed by dmcgowan** 2016-11-21 18:33 UTC

**Comment by Vad1mo** [comment] 2017-02-01 22:12
@gschukin how did you resolve this issue?

**Comment by gschukin** [comment] 2017-02-01 22:15
@Vad1mo this is related to redis cache. I simply switched to in-memory implementation.

**Comment by Vad1mo** [comment] 2017-02-01 22:18
thats strange I am using the inmemory cache implementation.

```
cache:
    blobdescriptor: inmemory
```

**Comment by gschukin** [comment] 2017-02-01 22:20
What ceph version do you use?

**Comment by Vad1mo** [comment] 2017-02-01 22:25
I have actually no idea, I am on OVH. where could I get the version?

**Comment by gschukin** [comment] 2017-02-01 22:35
It seams that they use Infernalis, I was on Firefly.

The only option I see is to debug Distribution as I have no idea what is happening. It seems really ceph (rgw) related.

**Comment by Vad1mo** [comment] 2017-02-01 22:40
```
registry_1    | 172.18.0.3 - - [01/Feb/2017:21:04:04 +0000] "GET /v2/onif/spolcys-api/blobs/sha256:9dac3d0b6962fe1c6fb776ee09a3a0a673a3650655ffc253a68ee9806b1e32fc HTTP/1.1" 307 315 "" "docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/3.13.0-106-generic os/linux arch/amd64"
registry_1    | 2017/02/01 21:04:14 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Time-out\r\nCache-Control: no-cache\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n"; err=<nil>
registry_1    | 2017/02/01 21:04:14 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Time-out\r\nCache-Control: no-cache\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n"; err=<nil>
registry_1    | 2017/02/01 21:04:14 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Time-out\r\nCache-Control: no-cache\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n"; err=<nil>
registry_1    | time="2017-02-01T21:58:02Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.3 http.request.host=dockerhub.onif.digital http.request.id=e31001e5-40d6-4189-af34-fc8912540618 http.request.method=GET http.request.remoteaddr=84.72.104.165 http.request.uri="/v2/" http.request.useragent="docker/1.13.0 go/go1.7.3 git-commit/49bf474 kernel/4.9.4-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.0 \\(darwin\\))" instance.id=cd2e91e0-4d53-4a65-b0c2-e1cc769e6408 version=v2.6.0 
registry_1    | 172.18.0.3 - - [01/Feb/2017:21:58:02 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.13.0 go/go1.7.3 git-commit/49bf474 kernel/4.9.4-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.0 \\(darwin\\))"
```
I have an idea that it might be this layer.  Do you think I could check the `"Last-Modified"` header to track down if an entry exists? or is it not related to #1673?

**Comment by Vad1mo** [comment] 2017-02-01 23:13
I could lookup the image in swift but it does have a `Last Modified` date set.
```
     Container: images
        Object: files/docker/registry/v2/blobs/sha256/eb/ebe6d74087564a71a522c75f56bbd962909a1c50aaf34986d1e9a28989745e50/data
  Content Type: application/octet-stream
Content Length: 352449
 Last Modified: Wed, 01 Feb 2017 21:02:58 GMT
          ETag: "273012d5eac88325c3fd4402cfc9fb50"
      Manifest: images/segments/2f6/46f636b65722f72656769737472792f76322f7265706f7369746f726965732f66696e6f2f6379636c6f70732d6170692f5f75706c6f6164732f66663363316537322d366630662d346237322d393334612d3238303531376436666434612f646174614919c88c2e7507cdea3f03f8cb9cfcc933a003836408ec9a314e12c4f1ccc63eda39a3ee5e6b4b0d3255bfef95601890afd80709
 Accept-Ranges: bytes
   X-Timestamp: 1485982977.22844
    X-Trans-Id: tx559548c4160b4aa1a5c9e-00589268fe
```

**Comment by gschukin** [comment] 2017-02-01 23:26
It has
```
Last Modified: Wed, 01 Feb 2017 21:02:58 GMT
```

In my test I was sure that all layers exists in ceph.
