### ISSUE TITLE
FATA[0430] Error pushing to registry: Server error: 500 trying to push

### ISSUE THREAD

**Issue by fernandoneto** [docker/distribution#758] opened 2015-07-27 10:33 UTC
Hi. 

im running the last registry image and when i try to push a images with big layers (+100Mb) im getting this error 
`FATA[0430] Error pushing to registry: Server error: 500 trying to push example blob - sha256:2a5666536ffb33e441401f5156ebfdbaf1f81018976597f0856431cc46c834d7 
`
im sending the data to azure storage and with other images work well (like busybox).
maybe it can be something related with #413 ??

Update

sometimes the image push without problems, but the most of the times im getting error

**Comment by RichardScothern** [comment] 2015-07-27 16:58
@fernandoneto : thanks for the report.  We need a bit more information to debug this.

Can you give us your docker registry and daemon version information, and the logs around the time the error happened?

**Comment by fernandoneto** [comment] 2015-07-27 17:23
@RichardScothern 

docker daemon - Docker version 1.6.2, build 7c8fca2
docker registry - the latest on docker hub (release 1341222)

later on i will give you the logs. 

I can tell you now if every time the push fail in a layer you repeat the push command it will push the layer  that give you error with sucess and stop in the next one.

**Comment by NickDeClario** [comment] 2015-08-10 14:48
I am experiencing a similar problem.  I have the latest registry from github (4f7cb60190).  I configured the config.yaml to use my S3 bucket and have confirmed permission to read/write to the bucket.  I am running docker 1.7.1 build 786b29d under Ubuntu 14.04.3 LTS.  After changing the config.yaml file I built my registry container with:

```
docker build --rm=true -t registry .
```

I am starting my registry container with:

```
docker run -d -i --name registry -p 5000:5000 registry
```

When I try to push an image, 'docker push localhost:5000/myimage:revision', I get the following:

```
# docker push localhost:5000/myimage:latest
The push refers to a repository [localhost:5000/myimage] (len: 1)
af340544ed62: Image push failed 
Error pushing to registry: Server error: 500 trying to push myimage blob - sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
```

In the s3 bucket I can see the directories getting created for the registry, 'docker/registry/v2/repositories/hello-mine/_uploads/' and in that uploads directory are a handful of directories named with hashes with a 'startedat' file containing a timestamp in each directory.

I've also tried pulling the registry:2 from dockerhub and passing the AWS configuration in environment variables with the same results.

My S3 bucket originally was created with permissions to allow the user I created with the AWS access and secret key full access to the bucket.  I've since tried completely opening the bucket to full access to "everyone" with no difference in behavior.

**Comment by RichardScothern** [comment] 2015-08-10 17:33
@NickDeClario : please follow the instructions here: https://github.com/docker/distribution/blob/master/CONTRIBUTING.md#if-you-have-not-found-an-existing-issue-that-describes-your-problem

The logs from the Registry will be particularly helpful.

**Comment by RichardScothern** [comment] 2015-09-03 23:26
@NickDeClario: do you have any update?

**Comment by NickDeClario** [comment] 2015-09-04 14:25
@RichardScothern So I resolved the issue.  The problem was a typo in the bucket name in my IAM policy.  This was really confusing as it was able to write everything to S3 except the blobs until I fixed the policy.  What I don't understand is why did the policy allow some things to be placed in S3 but not the blobs?

**Comment by RichardScothern** [comment] 2015-09-08 20:47
@fernandoneto : do you have any update?

**Comment by dmp42** [comment] 2015-10-05 23:16
@fernandoneto it seems you have resolved the issue. I'm closing for bookkeeping, but please state so if it needs to be reopened.

**Closed by dmp42** 2015-10-05 23:16 UTC
Labels: bug

**Comment by fernandoneto** [comment] 2015-10-06 10:49
@RichardScothern @dmp42 
At this moment im using AWS S3 and have no issues. However when i have a little time i perform the test to Azure Storage again.
