### ISSUE TITLE
How do you configure a redis cache with s3 storage using environment variables ?

### ISSUE THREAD

**Issue by muralimadhu** [docker/distribution#657] opened 2015-06-24 00:14 UTC
docker run \
   -d \
   -e REGISTRY_STORAGE=s3 \
   -e REGISTRY_STORAGE_S3_ACCESSKEY=changeme \
   -e REGISTRY_STORAGE_S3_SECRETKEY=changeme \
   -e REGISTRY_STORAGE_S3_BUCKET=docker-registry-v2 \
   -e REGISTRY_STORAGE_S3_REGION=us-west-2 \
   -e REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR=redis \
   -e REGISTRY_REDIS_ADDR=localhost:6379 \
   -p 5000:5000 \
   registry:2

This does not however use the cache. Is this a bug ? or am I missing an environment variable ?

**Comment by RichardScothern** [comment] 2015-06-24 17:53
@muralimadhu this approach is correct, and should (in theory) work.

What are you seeing in your registry logs?  Does it attempt to connect to any redis service?  A redis service on a different port?

**Comment by muralimadhu** [comment] 2015-06-24 18:46
@RichardScothern I dont see anything in the logs related to redis. 

time="2015-06-24T18:44:14.278152853Z" level=info msg="endpoint local-8082 disabled, skipping" environment=development instance.id=bf44c42d-83bd-47df-a1a7-0f57b820677d service=registry version=v2.0.1
time="2015-06-24T18:44:14.278900357Z" level=info msg="endpoint local-8083 disabled, skipping" environment=development instance.id=bf44c42d-83bd-47df-a1a7-0f57b820677d service=registry version=v2.0.1
time="2015-06-24T18:44:14.278959606Z" level=info msg="listening on :5000" environment=development instance.id=bf44c42d-83bd-47df-a1a7-0f57b820677d service=registry version=v2.0.1
time="2015-06-24T18:44:14.278590617Z" level=info msg="Starting upload purge in 45m0s" environment=development instance.id=bf44c42d-83bd-47df-a1a7-0f57b820677d service=registry version=v2.0.1
time="2015-06-24T18:44:14.2790749Z" level=info msg="debug server listening localhost:5001"
time="2015-06-24T18:44:16.15586978Z" level=info msg="response completed" environment=development http.request.host="localhost:5000" http.request.id=362ec2dd-82ea-4d74-9fae-b9d3c34979ed http.request.method=GET http.request.remoteaddr="172.17.42.1:53242" http.request.uri="/" http.request.useragent="curl/7.29.0" http.response.contenttype="text/plain; charset=utf-8" http.response.duration="137.331µs" http.response.status=404 http.response.written=19 instance.id=bf44c42d-83bd-47df-a1a7-0f57b820677d service=registry version=v2.0.1

Monitoring the redis server also shows no activity

**Comment by stevvooe** [comment] 2015-06-26 01:05
@muralimadhu "blobdescriptor" is only supported in registry 2.1 and master, which will be released in a few weeks. For now, you'll have to use "layerinfo", which is equivalent and backwards compatible.

**Comment by stevvooe** [comment] 2015-06-26 01:05
@muralimadhu In the future, please use the mailing list for these kinds of questions.

**Comment by damnhandy** [comment] 2015-06-26 10:36
The documentation for the current release clearly states that the `blobdescriptor` and `inmemory` are valid options for storage.cache: 

https://docs.docker.com/registry/configuration/

I would never have figured that `layerinfo` would be a valid option as it's not mentioned anywhere in the registry v2 docs. I would say this is a valid forum for this issue and that it's an issue that affects the documentation. I would suggest the label is switched from "question" to something like "documentation" as the docs are currently misleading.

**Comment by muralimadhu** [comment] 2015-06-26 17:13
Yes, it seems like there is a mismatch between whats in the documentation and whats currently released. The documentation should clearly indicate what feature is available in which version. For ex) I see this issue too: https://github.com/docker/distribution/issues/522 . Now I dont know whether my configuration is wrong or if its a bug.

**Comment by stevvooe** [comment] 2015-06-26 18:11
@damnhandy @muralimadhu Here is the [documentation for the 2.0.1 release](https://github.com/docker/distribution/blob/v2.0.1/docs/configuration.md#cache) covering `layerinfo`. Sorry this is not easy to find but the docs are managed in https://github.com/docker/docs-base. I'd recommend filing an issue over there to voice your concern.

@muralimadhu #522 is completely unrelated to the documentation version. That is indeed a bug or lack of an expected behavior. However, I would recommend you draft your own Dockerfile from registry:2.0.1 with your own configuration file, rather than relying solely on environment variables. Environment variables can be used to tweak the configuration but I recommend you set a decent outline first. We are exploring better approaches to this in the future.

**Comment by undying** [comment] 2015-07-28 22:58
Well, I can understand muralimadhu, because in the production we are using an Environment Variables for configure our Docker Containers. This is a very handy way to run application without any file dependencies. So, I would make proposal that the environment variables were as equivalent as the configuration files, because it's handy and consistent with the concept of the twelve factor apps (http://12factor.net/).

**Comment by undying** [comment] 2015-07-28 23:36
By the way. I have tried to configure registry to using redis as cache, but it's not working.
I was trying to pass configuration params as envoronment variables:
```
--env=REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR=redis (I have tried --env=REGISTRY_STORAGE_CACHE_LAYERINFO=redis also)
--env=REGISTRY_REDIS_ADDR=172.17.42.1:6379
```

after then I tried with config file:
```
version: 0.1
log:
  level: debug
  fields:
    service: registry
    environment: development
http:
  addr: :5000
  secret: asecretforlocaldevelopment
  debug:
    addr: localhost:5001
redis:
  addr: 172.17.42.1:6379
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
```

but tcpdump and redis-cli tells me that registry even did't tried to use it.

**Comment by stevvooe** [comment] 2015-07-29 19:55
@undying The config you have only configures the redis connection pool. Add the following to the storage section:

```
storage:
  cache:
    blobdescriptor: redis
```

**Comment by janbeerden** [comment] 2015-08-03 18:29
Hello @stevvooe,

I am trying the same thing as @undying with:
```
storage:
  cache:
    blobdescriptor: redis
```
like you said.

I am using version distribution/registry:master, but `redis-cli monitor` does not show any trafic.

I have also tried distribution/registry:latest with:
```
storage:
  cache:
    layerinfo: redis
```
but this doesn't seam to do anything either.

Is there a method for debugging this?

**Comment by nateww** [comment] 2015-09-02 16:59
@stevvooe undying setup shows he's configuring the storage section setup with the environment variable:

--env=REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR=redis (I have tried --env=REGISTRY_STORAGE_CACHE_LAYERINFO=redis also)

Does this not work?

[ As you can imagine, we're facing the exact same issue with distribution V 2.1.1 ]

**Comment by stevvooe** [comment] 2015-09-02 18:15
Should `-e REGISTRY_REDIS_ADDR=REDIS_PORT_6379_TCP_ADDR:6379 registry:2.1.1` be `-e REGISTRY_REDIS_ADDR=$REDIS_PORT_6379_TCP_ADDR:6379 registry:2.1.1`? It seems like there is a missing `$`.

Either way, it is recommended to write a base configuration for your deployment and tweak with environment variables.

**Comment by nimicohgr** [comment] 2015-09-09 15:42
I just want to confirm what @nateww reported.  Setting s3 storage and Redis storage cache do not work through environmental variables.  I moved the config to the configuration file and Redis started up with s3 storage, so it's only an issue using environmental variables.  I am using version 2.1.1 of Distribution as well.

**Comment by overplumbum** [comment] 2015-09-09 16:15
REGISTRY_STORAGE env var overwrites (completely wipes) underlaying structure no matter of "-e" flags order.
So it's bad idea to form entire conf structure using env vars only.
Setting individual conf values works fine.

**Comment by RichardScothern** [comment] 2015-09-10 17:03
@overplumbum this is correct.  

https://github.com/docker/distribution/pull/888 should help matters, but as mentioned above a base config with environmental overrides is the recommended approach.

**Closed by RichardScothern** 2015-09-10 17:03 UTC
Labels: question

**Comment by mrwacky42** [comment] 2015-10-08 01:14
@stevvooe 
Re: [12-factor](https://github.com/docker/distribution/issues/657#issuecomment-126077682) 

Here's a couple ideas to solve the problem at hand:

* Move the cache section to the top level (in fact [current docs](https://docs.docker.com/registry/configuration/) show it as a top-level config option in the sample YAML ) outside of the storage backend config section. Then setting ```REGISTRY_STORAGE_S3``` won't make it impossible to use redis as a cache.
* Provide as close to blank as possible ``config.yml``` in the official registry image. One with no storage backend configured. 
* Remove the ability to configure via environment completely. It is senseless to have two methods of configuration if one is opaquely incomplete. (hashtag bijections4eva)

Hopefully #888 fixes this. If not, hopefully the documentation is updated to reflect that something seemingly simple & obvious is not.

**Comment by tamsky** [comment] 2015-10-08 03:13
Even after #888 lands, some gems above should really be promoted as best practices.  Example:

https://github.com/docker/distribution/issues/657#issuecomment-115821522 , wherein @stevvooe says:
> ... I would recommend you draft your own Dockerfile from registry:2.0.1 with your own configuration file, **rather than relying solely on environment variables**[emphasis mine]. Environment variables can be used to tweak the configuration but I recommend you set a decent outline first. We are exploring better approaches to this in the future.

Since it seems ENV variables are a well-known deficiency in the registry config system (to some, at least)... please add some *BIG FAT WARNINGS* in `docs/deploying.md` and `docs/configuration.md`.

That would be *very* appropriate until "better approaches" land.
