### ISSUE TITLE
catalog still lists the repos which are deleted by delete API call

### ISSUE THREAD

**Issue by ywk253100** [docker/distribution#1615] opened 2016-04-11 02:47 UTC
After deleting the manifest and layers of a repo by calling the delete API, I can still get information of it when I call catalog API. Does this make sense or I missed something?

**Comment by RichardScothern** [comment] 2016-04-11 17:05
It's a bug.  I'm closing this as a duplicate of #1585

**Closed by RichardScothern** 2016-04-11 17:05 UTC
