### ISSUE TITLE
Docker pull not working - images in Registry

### ISSUE THREAD

**Issue by damianharvey** [docker/distribution#1206] opened 2015-11-24 06:45 UTC
Hi all,

I am running a private registry (v2.2.0) and I can push images into it, query using the API and see the tags, but cannot pull certain images from it. Note that I can pull some images, just not newer ones that I have created today.

For example:
```
docker push docker push  myrepo:5001/group/containerx
```
This push works fine.I can check to see if the image is in the registry:
```
 curl -k https://myrepo:5001/v2/group/containerx/tags/list
{"name":"group/containerx","tags":["latest"]}
```
But when I try to pull:
```
docker pull myrepo:5001/group/containerx:latest
Pulling repository myrepo:5001/group/containerx
Error: image group/containerx:latest not found
```
But pulling other (older) images works fine:
```
 docker pull myrepo:5001/group/containerz
Using default tag: latest
latest: Pulling from group/containerz
4eb0abc76e69: Pull complete
3213d73954bc: Pull complete
77b25d2a59b1: Pull complete
Digest: sha256:4b4asdasdasdasdasdxxxxx7842711aa1dae6e030da03f9e17e9cfdeda140453feed
Status: Downloaded newer image for myrepo:5001/group/containerz:latest
```

Any thoughts? Thanks

**Comment by Myp** [comment] 2015-11-24 11:04
I have similar problem
```
➜  ~  docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:35:24 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:35:24 UTC 2015
 OS/Arch:      linux/amd64

```

version registry 2.1.1

in registry log last lines: 
```
 - - [24/Nov/2015:11:03:19 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/3.13.0-37-generic os/linux arch/amd64"
 - - [24/Nov/2015:11:03:19 +0000] "GET /v1/repositories/ksp-balancer-master/images HTTP/1.1" 404 19 "" "docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/3.13.0-37-generic os/linux arch/amd64"

```

**Comment by RichardScothern** [comment] 2015-11-24 17:43
@Myp : please file a separate bug report.  The problem may not be the same and it's easier to deal with them individually.

@damianharvey : I'll need to the registry and daemon logs (in debug mode) during the pull of the missing image.  Also, what happens when you:
`curl -i -k https://myrepo:5001/v2/group/containerx/manifest/latest`

**Comment by damianharvey** [comment] 2015-11-24 20:09
@RichardScothern this is from the Registry logs when I do a pull:

time="2015-11-24T20:03:32Z" level=info msg="response completed" go.version=go1.4.3 http.request.host="myrepo:5001" http.request.id=308308cd-e87f-49bb-9c40-1cc61ca056e0 http.request.method=GET http.request.remoteaddr="10.102.34.29:38102" http.request.uri="/v2/" http.request.useragent="docker/1.9.0 go/go1.4.2 git-commit/76d6bc9 kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=2.920005ms http.response.status=200 http.response.written=2 instance.id=786a8c38-7b16-4d33-8904-0a6058faf411 version=v2.2.0
10.102.34.29 - - [24/Nov/2015:20:03:32 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.9.0 go/go1.4.2 git-commit/76d6bc9 kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64"
time="2015-11-24T20:03:32Z" level=error msg="response completed with error" err.code="MANIFEST_UNKNOWN" err.detail="unknown manifest name=group/containerx tag=latest" err.message="manifest unknown" go.version=go1.4.3 http.request.host="myrepo:5001" http.request.id=4bc997bb-ada8-4e9c-90db-d03c2e975d51 http.request.method=GET http.request.remoteaddr="10.102.34.29:38103" http.request.uri="/v2/group/containerx/manifests/latest" http.request.useragent="docker/1.9.0 go/go1.4.2 git-commit/76d6bc9 kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=3.073823ms http.response.status=404 http.response.written=121 instance.id=786a8c38-7b16-4d33-8904-0a6058faf411 vars.name="group/containerx" vars.reference=latest version=v2.2.0
10.102.34.29 - - [24/Nov/2015:20:03:32 +0000] "GET /v2/group/containerx/manifests/latest HTTP/1.1" 404 121 "" "docker/1.9.0 go/go1.4.2 git-commit/76d6bc9 kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64"
time="2015-11-24T20:03:32Z" level=info msg="response completed" go.version=go1.4.3 http.request.host="myrepo:5001" http.request.id=44978923-960e-4f96-b9f9-1aefbec46d4f http.request.method=GET http.request.remoteaddr="10.102.34.29:38104" http.request.uri="/v2/" http.request.useragent="docker/1.9.0 go/go1.4.2 git-commit/76d6bc9 kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.433079ms http.response.status=200 http.response.written=2 instance.id=786a8c38-7b16-4d33-8904-0a6058faf411 version=v2.2.0
10.102.34.29 - - [24/Nov/2015:20:03:32 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.9.0 go/go1.4.2 git-commit/76d6bc9 kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64"
10.102.34.29 - - [24/Nov/2015:20:03:32 +0000] "GET /v1/repositories/group/containerx/images HTTP/1.1" 404 19 "" "docker/1.9.0 go/go1.4.2 git-commit/76d6bc9 kernel/3.10.0-229.el7.x86_64 os/linux arch/amd64"


Note that the Daemon logs don't even move (even on debug mode).

**Comment by RichardScothern** [comment] 2015-11-24 22:09
@damianharvey : there must be daemon logs for that amount of activity.  Something is causing it to fallback to the v1protocol.

Did you try to fetch the manifest with curl?

**Comment by damianharvey** [comment] 2015-11-24 23:54
Hi @RichardScothern the curl returns a 404:

```
curl -i -k https://myrepo:5001/v2/group/containerx/manifest/latest
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
Date: Tue, 24 Nov 2015 23:40:44 GMT
Content-Length: 19

404 page not found
```

**Comment by damianharvey** [comment] 2015-11-24 23:56
From the Registry logs:
```
172.17.0.1 - - [24/Nov/2015:23:56:12 +0000] "GET /v2/group/containerx/manifest/latest HTTP/1.1" 404 19 "" "curl/7.29.0"
```

**Comment by RichardScothern** [comment] 2015-11-25 00:01
OK.  There are a couple of ways to investigate this - we should do both.

Set your registry log level to `debug`.  Paste the logs for that request here.

Investigate the file state:  which kind of backend driver are you using?

**Comment by iamlittle** [comment] 2015-11-26 07:49
Having the same issue

**Comment by damianharvey** [comment] 2015-11-26 21:04
@RichardScothern ran command and Daemon debug log showed the following that causes it to try to use the v1 API:

```
DEBU[0018] Pulling tag from V2 registry: "latest"
DEBU[0018] Error trying v2 registry: Invalid parent ID. Expected ce20c473cd8ac1fab6601529ce6a075743f2cf7a8f4cfed2216f8cfcb53bfc4e, got e9fa5d3a0d0e19519e66af2dd8ad6903a7288de0e995b6eafbcb38aebf2b606d.
DEBU[0018] Trying to pull myrepo:5001/group/containerx from https://myrepo:5001 v1 
```

**Comment by RichardScothern** [comment] 2015-11-30 18:20
Interesting, that looks like a corrupt manifest.  @aaronlehmann : we've seen this before, right?

**Comment by aaronlehmann** [comment] 2015-11-30 18:29
Yes, this corruption can be caused by Docker 1.8.3 or 1.9.0 in certain unusual cases. It is fixed by https://github.com/docker/docker/pull/18047 in the Docker Engine, which is included in 1.9.1.

**Comment by RichardScothern** [comment] 2015-12-15 23:59
@damianharvey : unfortunately it looks like an upgrade to docker 1.9.1 is required.

**Comment by dmp42** [comment] 2015-12-22 20:06
@damianharvey I'm marking this as wontfix since there is nothing to do on the registry side, and the bug is fixed in the engine. Unfortunately, like @RichardScothern  said, you will have to upgrade to 1.9.1.

**Closed by dmp42** 2015-12-22 20:06 UTC
Labels: wontfix
