### ISSUE TITLE
CloudFront creating invalid Signed URL's

### ISSUE THREAD

**Issue by benbarclay** [docker/distribution#925] opened 2015-08-26 07:11 UTC
I am trying to get the CloudFront middleware layer working on version 2.1.1

As far as I can tell, the signed url's being generated by the registry are invalid.

Both pushing and pulling images from the registry throw errors. 
- Pushing image logs: https://gist.github.com/benbarclay/e4c14e6fa3473af4e2a5
- Pulling image logs: https://gist.github.com/benbarclay/cf1f2d87bd882b8d17b8

I grabbed a HEAD request in the registry logs from one of the pull's and tested it out in Postman, including the Authorization and User-Agent headers. I successfully receive the 307 redirect to a cloudfront signed url. The cloudfront url then gives me a 403 Forbidden.

Playing around with a [CloudFront URL Tool](https://aws.amazon.com/code/CloudFront/3052) I am able to decode the URL successfully
```
Base URL: 
https://d287onwoug4r78.cloudfront.net/docker/registry/v2/blobs/sha256/a3/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4/data
Policy: 
{"Statement":[{"Resource":"https://d287onwoug4r78.cloudfront.net/docker/registry/v2/blobs/sha256/a3/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4/data","Condition":{"DateLessThan":{"AWS:EpochTime":1440572954}}}]}
Key: 
KEYHERE
```

If I then use that tool to create a new signed url, with the same Key ID and Key that the registry is using, along with the base url decoded above, I get a URL that lets me download the manually.

I'm not really sure how to debug this much further, but it's looking like the registry might be at fault here.

**Comment by dmp42** [comment] 2015-08-26 07:57
Ping @RichardScothern

**Comment by stevvooe** [comment] 2015-08-28 05:30
@benbarclay I suspect something is amiss with the configuration. Could you provide the registry configuration and the unmodified URL?

**Comment by benbarclay** [comment] 2015-08-31 00:10
Configuration:
```
version: 0.1
log:
  level: debug
  formatter: text
  fields:
    service: docker-registry-v2
storage:
  cache:
    layerinfo: redis
  s3:
    accesskey: ""
    secretkey: ""
    region: ap-southeast-2
    bucket: registry-v2.platform.dev.atl-inf.io
    encrypt: true
    secure: true
    v4auth: true
http:
  addr: 0.0.0.0:5000
  secret: yPGdkQ5IabGjolFje3d8nHeFsTfG6fKetHL5nmerWNE
  debug:
    addr: 0.0.0.0:5001
middleware:
  storage:
    - name: cloudfront
      options:
        baseurl: https://d287onwoug4r78.cloudfront.net
        privatekey: /etc/docker/registry/private-key.pem
        keypairid: AWKAIDVDANTFS65FQEDA
redis:
  addr: docker-ju78xd32q.yuyupj.ng.0001.apse2.cache.amazonaws.com:6379
```

Not sure what you mean by the unmodified URL?

**Comment by stevvooe** [comment] 2015-09-01 18:18
@benbarclay By "unmodified URL", I mean the unmodified cloudfront url, provided by the registry during the redirect. We need ensure it is not corrupted in any way.

Also, is your accesskey/secretkey set to ""? If these are set via environment variable, just don't set them in the configuration.

cc @RichardScothern Any ideas?

**Comment by benbarclay** [comment] 2015-09-02 07:19
Tried removing the keys, same result.

Just generated this URL: 
https://d287onwoug4r78.cloudfront.net/docker/registry/v2/blobs/sha256/a3/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4/data?Expires=1441179483&Signature=HHSBcwgJrKVh4Q6It0HeWdx58AP80gA4~0ebLlAHPnVEwDJXKgTqWf0Y7Ey7wprcK6-RsNwG6RB4Xact7LzO7GQGFjkTC8VVgxPBemlXDV7RWwRt7qVIPr1BIQjtrh-P2S7XbH6i1NUdsLq18TkVNn3XOZS1wnaFKX4aSIcdOmSwduyyQnv56F2WfUiqWDehGusERWZG1pAUSk4HYRSiWmkWwjcOjmEeS8~B06yd~5NnGxwEmsO1YcQ-EdH1jfABvQ02H5GPFDO8unpt-op5hY3HDL8DAhq0GA1KLq7QrAzRhYC-wyEEA4bfKwI~efdECho~sKkIxD4c9tg91e5d4g__&Key-Pair-Id=APKAIQV4ANT2S65FBELA

It uses a different keypairid (I grabbed the config from a slightly different environment), but should be otherwise identical.

**Comment by z0rc** [comment] 2015-10-20 11:10
@benbarclay was your issue resolved. I'm trying to configure cloudfront middleware and seems facing the same issue.

**Comment by z0rc** [comment] 2015-10-20 11:41
Okay, I've got what was the error. It's required to disable redirect while using cloudfront middleware.
```
storage:
  redirect:
    disable: true
```

**Comment by z0rc** [comment] 2015-10-20 14:38
But, running without redirects defeats the purpose of cloudfront middleware, as in my case cloudfront is much closer to me, that the registry.

**Comment by benbarclay** [comment] 2015-10-21 00:03
No, I haven't solved this issue yet. Parked it in the backlog for now. Having said that we recently switched from using Nginx as a reverse proxy with auth to a token service, and it has fixed lots of issues. I plan to re-try the CloudFront stuff soon.

**Comment by z0rc** [comment] 2015-10-21 15:26
Okay, I found what was the error in my case. The Cloudfront 403 response was actually proxied S3 response, the Cloudfront wasn't able to access S3 bucket. I've enabled Origin Access Identity within distribution origin settings, and everything started to work.

**Comment by stevvooe** [comment] 2015-10-21 18:04
@z0rc In your opinion, what is the best way to debug these kinds of issues? We've had a number user problems that are hard to track down to incoherent error messages in the s3 API. Is there some place we should direct users to confirm their access control setup is correct? How did you discover the ACL issue in this case?

cc @RichardScothern

**Comment by RichardScothern** [comment] 2015-10-21 18:15
There are a few areas of AWS (Cloudfront, VPC to name two) which seem to trip people up.  I think additional documentation in this area would be useful.

**Comment by z0rc** [comment] 2015-10-22 08:08
So, here is screenshot with configuration I used to allow access to S3 bucket origin from Cloudfront distribution. Sensitive data is cleaned up.
<img width="1281" alt="screen shot 2015-10-22 at 11 02 34" src="https://cloud.githubusercontent.com/assets/787519/10660073/0ad2d57c-78ad-11e5-9924-d9aff9641778.png">

**Comment by krak3n** [comment] 2015-11-17 15:21
I strongly suggest you guys provide a step by step on how to enable cloudfront for docker distributions in EC2. It's really not obvious what the steps are or the correct cloud front settings we need for it to work correctly.

**Comment by stevvooe** [comment] 2015-11-25 02:00
@benbarclay Looking back at the original issue, it looks to me like the time on the machine may be set incorrectly, causing the registry to emit expired URLs. Perhaps, ensuring that the time on the registry is up to date would address the problem.

@krak3n Have you seen this particular issue? Are you currently trying to configure cloudfront? I think @RichardScothern covered your "strong suggestion" above but was there some aspect missing specifically that his didn't cover?

**Comment by dmp42** [comment] 2016-01-22 00:43
@krak3n and others, additional documentation has since been merged about this here: 

https://github.com/docker/distribution/blob/0be4b3f27d783ea9f3bfddfbc2e3e817f7d02c24/docs/storage-drivers/s3.md#cloudfront-as-middleware-with-s3-backend

Would you have a look at it and let us know if this is shedding lights on how to achieve this / if this can be closed?

**Comment by krak3n** [comment] 2016-01-22 11:03
@dmp42 thank you, will take a look :+1:

**Comment by benbarclay** [comment] 2016-02-03 03:15
Had another look at this today. As per @stevvooe's suggestion, I checked the server time. It matches my localhost (when both converted to UTC). 

I have been playing around with the [CloudFront helper tool](https://aws.amazon.com/code/CloudFront/3052). Using it I have confirmed that the CloudFront Distribution is correctly configured. I can create valid signed url's with the same private key + keyid that the registry is using and I can download random registry blobs with the urls.

The URL's generated by the registry appear correct. They correctly decode with the helper tool, and have an expiry time in the future. I actually don't have any idea what's wrong here.

I have also been chatting to AWS support, and they have confirmed that everything is correctly configured from the AWS side.

**Comment by dliappis** [comment] 2016-02-09 13:11
This is a paint point in my case as well.
When enabling *Restrict Viewer Access*, while pushing a new docker image I am receiving:
```
<imageid>: Image push failed 
Error parsing HTTP response: unexpected end of JSON input: ""
```

I am using instance roles and have been able to confirm that the instance hosting the registry containers is able to perform all operations on the S3 bucket without issues (also verified with aws s3 cp)

My investigation so far shows that registry is trying to check existing docker content in S3 via cloudfront first (before pushing directly to S3) and evidently this doesn't work with signed urls.
Has anyone made docker distribution work reliably with cloudfront using signed URLs?

I have experimented with numerous combinations and the only thing that I managed to get working is:

```yaml
# ... skipping http , log and auth sections
storage:
    cache:
        layerinfo: inmemory
    s3:
        region: us-east-1
        bucket: <mybucket>
        encrypt: true
        secure: true
        v4auth: true
        chunksize: 5242880
        rootdirectory: /
middleware:
    storage:
        - name: cloudfront
          disabled: false
          options:
             baseurl: https://<mycfbasehostname>.cloudfront.net
             privatekey: /MYCFKEYPAIR
             keypairid: MYCLOUDFRONTKEYPAIR
             duration: 60
```

and on the cloudfront side:

#### Origin
- Enable `Restrict Bucket Access` and grant read permissions on bucket (confirmed by looking at the S3 bucket properties)

![image](https://cloud.githubusercontent.com/assets/1754575/12916473/6b8868a2-cf3b-11e5-8a27-9325304b2fb7.png)

#### Behaviours

- Restrict Viewer Access: **NO**

With this setup, serving content via CloudFront works but obviously it does not use signed URLs.

I think we need to additionally review [the documentation](https://github.com/docker/distribution/blob/0be4b3f27d783ea9f3bfddfbc2e3e817f7d02c24/docs/storage-drivers/s3.md#cloudfront-as-middleware-with-s3-backend) and clarify:

1. For S3 buckets that do not have public list/read permissions, should cloudfront "Restrict Bucket Access" be enabled and a corresponding policy[1] be added to the bucket?

2. Are the default TTL settings affecting this behaviour?
![image](https://cloud.githubusercontent.com/assets/1754575/12916567/1a1db69c-cf3c-11e5-8a9a-7d53e064c1ef.png)



[1]:
This is an example of the bucket policy added by cloudfront when enabling Restrict Viewer Access:

```json
{
	"Version": "2008-10-17",
	"Id": "PolicyForCloudFrontPrivateContent",
	"Statement": [
		{
			"Sid": "1",
			"Effect": "Allow",
			"Principal": {
				"AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity <CLOUDFRONT_DISTRIBUTION_ID>"
			},
			"Action": "s3:GetObject",
			"Resource": "arn:aws:s3:::<bucketname>/*"
		}
	]
}
```

**Comment by stevvooe** [comment] 2016-02-09 20:51
> Has anyone made docker distribution work reliably with cloudfront using signed URLs?

We use this in production for the hub. The largest problems we have are with timestamp synchronization.

> `"arn:aws:s3:::<bucketname>/*"`

I am not an expert on policy configuration, but the asterisk ("*") may not be necessary. You may just want prefix with the "/"/ or just the bucket name itself.

I'll leave it to someone else to answer your specific questions, as I don't really know the answers.

**Comment by dmp42** [comment] 2016-02-09 21:14
@dliappis 

Confirming that:

 * cloudfront signed url is the setup we are currently using
 * we use the same (defaut) policy you list here
 * we DO "restrict viewer access" (trusted signer: self)

To help you further, I would probably need your docker *daemon* logs (preferably ran in debug mode), your registry logs (and version of all that).

**Comment by dmp42** [comment] 2016-02-09 21:15
Agreed that the docs should work out of the box if you follow them step by step. They certainly could be enhanced.

**Comment by benbarclay** [comment] 2016-02-17 04:09
FYI, my college @ash2k just built and deployed commit 5a1863b76e853ec1fa8d621f95900b69911b3cf5 (where the goamz AWS SDK has been switched for the official SDK). This has resolved all the issues we are experiencing with using CloudFront in front of our S3 bucket.

We did not change any configuration (other than re-enabling the CloudFront distribution) or the environment in which the registry is deployed. It was a simple drop in replacement.

**Comment by benbarclay** [comment] 2016-03-21 00:02
Any chance of getting an official distribution release with the new AWS SDK?

**Comment by RichardScothern** [comment] 2016-03-21 17:51
@benbarclay : the next registry release will have these changes.   The target release date is 04/07

@dmp42 : is there anything more regarding documentation we need to do for this issue?

**Comment by dmp42** [comment] 2016-03-21 18:36
@moxiegirl wdyt?

**Comment by moxiegirl** [comment] 2016-03-24 18:44
@dmp42 The way I'm reading this thread, the next release on 4/7 will solve this issue. After that release, the product will work for Cloudfront as documented.  If you agree, then I would recommend that we work with Support to maintain an FAQ perhaps in the forums and leave the docs unchanged. WDYT?

**Comment by dmp42** [comment] 2016-03-24 18:58
@moxiegirl if you are satisfied with our current doc on that front, then LGTM :)

**Comment by dliappis** [comment] 2016-03-24 20:17
Very glad to hear @benbarclay you have been able to get cloudfront signed urls working.
I will be redeploying a part of the environment I am managing and will consider building a distribution image including the mentioned commit.

Regarding [documentation](https://github.com/docker/distribution/blob/0be4b3f27d783ea9f3bfddfbc2e3e817f7d02c24/docs/storage-drivers/s3.md#cloudfront-as-middleware-with-s3-backend), the *duration* parameter [in the middleware section](https://github.com/docker/distribution/blob/master/docs/configuration.md#middleware) could be clarified further, especially:

- what is the unit (minutes I believe)
- if there is any recommended value and that default value is 20

I found the above information [in the example section](https://github.com/docker/distribution/blob/master/docs/configuration.md#example-middleware-configuration) but it should be in the actual [middleware section](https://github.com/docker/distribution/blob/master/docs/configuration.md#middleware)

**Comment by dmp42** [comment] 2016-03-24 22:22
@moxiegirl ^

@dliappis the commit in question has been merged, and is available in the latest 2.4-RC (will ship with 2.4), so, you might not have to pick it up / build it yourself.

**Comment by dliappis** [comment] 2016-03-25 07:57
Awesome thanks for this info @dmp42 I will test with 2.4-RC saves me some work!

**Comment by dliappis** [comment] 2016-03-25 15:45
@dmp42 I tried extensively `distribution/registry:2.4.0-rc` without luck.
In fact I wasn't able to push any images regardless of setting restricted viewer access Yes or No in cloudfront:

![image](https://cloud.githubusercontent.com/assets/1754575/14047393/460ca4ba-f2b0-11e5-8aa9-d3a6ab1441c1.png)

Using older versions, e.g. 2.2, push works when setting restricted viewer access to No (but not with Yes)

The errors I am receiving are basically "access denied" during PATCH operations:

```json
 {"auth.user.name":"XXXX","environment":"XXXXXX","err.code":"unknown","err.detail":"s3aws: AccessDenied: Access Denied\n\tstatus code: 403, request id: 2A7C6470D4A5C0A3","err.message":"unknown error","go.version":"go1.6","http.request.host":"XXXXXXXX","http.request.id":"d0b3a9ac-b2db-4f1e-99a7-7bcc2116c068","http.request.method":"PATCH","http.request.remoteaddr":"SOMEIP","http.request.uri":"/v2/repo/hello-world/blobs/uploads/b68cf964-6252-40ad-9c6a-fae2b0c3c640?_state=elrbiaaeHJmg9zGcx4pP48QI0pGsgiSOGmxoHbs9P2l7Ik5hbWUiOiJlbGFzdGljL2hlbGxvLXdvcmxkIiwiVVVJRCI6ImI2OGNmOTY0LTYyNTItNDBhZC05YzZhLWZhZTJiMGMzYzY0MCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNi0wMy0yNVQxNToxMDowMS4wMTI1MDYxOTRaIn0%3D","http.request.useragent":"docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/4.4.6-300.fc23.x86_64 os/linux arch/amd64","http.response.contenttype":"application/json; charset=utf-8","http.response.duration":"22.335377ms","http.response.status":500,"http.response.written":117,"instance.id":"XXXXXXXX","level":"error","msg":"response completed with error","service":"registry","time":"2016-03-25T15:10:01.95176323Z","vars.name":"repo/hello-world","vars.uuid":"b68cf964-6252-40ad-9c6a-fae2b0c3c640","version":"c6b8499"}
```

I have double checked that instance does have access to S3; reverting from `2.4.0-rc` to 2.2 allows pushing without any change to cloudfront (if restrict viewer access is off). The S3 bucket does have a policy allowing access from cloudfront as shown [in my earlier comment](https://github.com/docker/distribution/issues/925#issuecomment-181856895) so I assume there is something wrong with registry trying to "pull" or check the cloudfront url.

I am pretty much out of ideas, apart from building my own registry from master and trying that.

**Comment by dmp42** [comment] 2016-03-25 16:12
@dliappis PUSH *never* go through Cloudfront whatever your configuration is - this is unrelated.

I would suggest starting by configuring registry 2.4 without CloudFront and making sure you can push and pull through the registry. 

Nevertheless, cc @RichardScothern for advice on this ^

**Comment by dliappis** [comment] 2016-03-25 16:39
@dmp42 indeed push doesn't go through cloudfront but doesn't registry first check (pull) if the blob exists?

Another thing that crossed my mind is since I am using an IAM role granting instance access to the bucket instead of exposing s3 creds, could it be the aws library change mentioned in the above commit having issues? 

I will check without cloudfront entirely (this will require disabling restricting s3 access via cloudfront only). 

I will

**Comment by dliappis** [comment] 2016-03-26 10:20
Today I confirmed that for existing images if I enabled restricted bucket access with signed urls in cloudfront older docker distribution (e.g. 2.2) doesn't work on PULL, the new 2.4.0-rc works.

The error returned with `registry:2.2` was:

`Error parsing HTTP response: invalid character '<' looking for beginning of value: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>AccessDenied</Code><Message>Access denied</Message></Error>"`

So the code has definitely fixed this. :+1: 

Unfortunately, the issue of PUSH persists as described [in my earlier comment](https://github.com/docker/distribution/issues/925#issuecomment-201339187) with or without signed urls in cloudfront. I remind that this works in registry:2.2 with signed urls disabled.

Looking at the log `POST` operations are working ok (and new directory structure does get created in the S3 bucket for the image) however `PATCH` returns `Access Denied` on s3aws operation as per my earlier comment.

My setup doesn't expose any environment variable, everything is defined in a config file and the instance is attached to an IAM role allowing it full access to the bucket (confirmed and working in registry:2.2)

Finally, I confirmed that this behaviour by disabling the middleware layer completely.
With `registry:2.2` `PUSH` works without issues but `2.4.0-rc` gives the same error.
I see already #1562 opened yesterday on this so it's confirmed.

It is likely @benbarclay by cherry picking https://github.com/docker/distribution/commit/5a1863b76e853ec1fa8d621f95900b69911b3cf5 and building his own image got into the sweet spot of having all issues resolved.

At any rate the `PUSH` issue looks like a regression as described in #1562

**Comment by benbarclay** [comment] 2016-03-26 10:32
I don't recall if my colleague tested pushes. We definitely tested pulls. 
Based on what you mentioned though, you might need to change your bucket policy. 
IIRC pushes go directly to s3, pulls from cloudfront. If you have the bucket restricted to cloudfront only then you wouldn't be able to push.  That's probably a config change I need to make as well.

**Comment by dliappis** [comment] 2016-03-26 15:08
@benbarclay the IAM role I have granted allows read/write to the S3 bucket. For example if I disable the cloudfront middleware in the registry push+pull work fine with registry 2.2 but push doesn't with 2.4.0-rc.

Restricting bucket access via origin identity in cloudfront does not affect IAM role granted privileges for the S3 bucket to instances. When you enable this restriction you need to grant those read permissions to the cloudfront origin identity. If you click `Yes update bucket policy` in the below dialogue you will see additional privileges for `read` in your S3 bucket:

![image](https://cloud.githubusercontent.com/assets/1754575/14060696/bca0dd84-f374-11e5-9bf4-c3318cb90d27.png)

Enabling this increases security in read operation **via cloudfront** as explained in the [cloudfront documentation](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html).

>Typically, if you're using an Amazon S3 bucket as the origin for a CloudFront distribution, you grant everyone permission to read the objects in your bucket. This allows anyone to access your objects either through CloudFront or using the Amazon S3 URL. CloudFront doesn't expose Amazon S3 URLs, but your users might have those URLs if your application serves any objects directly from Amazon S3 or if anyone gives out direct links to specific objects in Amazon S3.

Thus enabling it will disable cloudfront read access via S3 urls, but allow access via cloudfront URLs signed or not (the latter defined in a different tab [as shown earlier](https://github.com/docker/distribution/issues/925#issuecomment-201339187) 

This is definitely the desired configuration as it is more secure and log complete as explained in AWS docs:

> If users access your objects directly in Amazon S3, they bypass the controls provided by CloudFront signed URLs or signed cookies, for example, control over the date and time that a user can no longer access your content and control over which IP addresses can be used to access content. In addition, if users access objects both through CloudFront and directly by using Amazon S3 URLs, CloudFront access logs are less useful because they're incomplete.

However, the errors related to `PUSH` in `2.4.0-rc` do not seem to be to the middleware configuration. See also #1562

**Closed** 2016-03-29 17:30 UTC
