### ISSUE TITLE
Proxy bypass for registry inside on-premise and storage back end is s3.

### ISSUE THREAD

**Issue by jayaram-raju** [docker/distribution#492] opened 2015-05-05 15:03 UTC
tried providing  -e "https_proxy" not working , but similar settings works fine for docker version 1.x

**Comment by dmp42** [comment] 2015-05-05 17:02
Can you clarify what the issue is?

Is this `docker -> registry` communication or `registry -> s3`?

**Comment by dmp42** [comment] 2015-05-15 10:23
@jayaram-raju I'm closing this since I don't have enough information to help you.
If you can provide answers for my previous questions, I'll reopen this.
Thanks.

**Comment by jayaram-raju** [comment] 2015-05-15 10:53
Sorry for the delay , its from registry to s3. as we are hosting the registry inside the enterprise behind the proxy . I might be missing the configuration in registry to upload the images to s3. in docker 1.x I was facing the same issue but it got resolved on setting http_proxy as env to registry container.

**Comment by dmp42** [comment] 2015-05-15 17:34
Ok. Have you tried settings both HTTP_PROXY and HTTPS_PROXY environment variables?
Can you copy the command you are using to launch the registry?

**Comment by jayaram-raju** [comment] 2015-05-19 11:42
Yes I Have set both HTTP_PROXY as well as HTTPS_PROXY 
cmd :- 
sudo docker run -e "HTTP_PROXY=http://<<hostname>>:<<port>>/" -e "HTTPS_PROXY=http://<<hostname>>:<<port>>/" registry:2.0

**Comment by dmp42** [comment] 2015-05-19 17:02
Hi,

Can you clone this: https://github.com/dmp42/distribution/tree/proxy
and checkout the branch "proxy".

Then can you start again running the same command `sudo docker run -e "HTTP_PROXY=http://<>:<>/" -e "HTTPS_PROXY=http://<>:<>/" registry:2.0` and report if that helps?

Thanks.

**Comment by dmp42** [comment] 2015-05-19 19:13
Hi @jayaram-raju 

Can you provide your registry logs?

Thanks.

**Comment by dmp42** [comment] 2015-05-27 18:38
@jayaram-raju can you provide your registry logs?
Thanks.

**Comment by damnhandy** [comment] 2015-06-23 16:32
I'm running into the same issues. I am running Docker Registry 2.0.1 in an AWS VPC that is all behind a proxy, we also direct all S3 traffic through the proxy as well. I am using IAM roles and have verified that the host has full read/write access to the S3 bucket. I am running with debug logging enabled and here's what I got when I attempted to push a new image to the repo:
```
time="2015-06-23T16:26:32.719298199Z" level=debug msg="authorizing request" environment=development http.request.host=docker-registry http.request.id=f0a886e6-a374-4675-96f1-494418d1bdd9 http.request.method=HEAD http.request.remoteaddr=xxx.xxx.xxx.xxxhttp.request.uri="/v2/gitbucket/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" http.request.useragent="docker/1.6.2 go/go1.4.2 git-commit/7c8fca2 kernel/4.0.3-boot2docker os/linux arch/amd64" instance.id=79a6eaca-8b58-42b6-b213-d47a7b4cbde2 service=registry vars.digest="sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" vars.name=gitbucket version=v2.0.1

time="2015-06-23T16:26:32.719386943Z" level=debug msg=GetImageLayer environment=development http.request.host=docker-registry http.request.id=f0a886e6-a374-4675-96f1-494418d1bdd9 http.request.method=HEAD http.request.remoteaddr=xxx.xxx.xxx.xxx http.request.uri="/v2/gitbucket/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" http.request.useragent="docker/1.6.2 go/go1.4.2 git-commit/7c8fca2 kernel/4.0.3-boot2docker os/linux arch/amd64" instance.id=79a6eaca-8b58-42b6-b213-d47a7b4cbde2 service=registry vars.digest="sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" vars.name=gitbucket version=v2.0.1
time="2015-06-23T16:26:32.71942078Z" level=debug msg="(*layerStore).Fetch" environment=development http.request.host=docker-registry http.request.id=f0a886e6-a374-4675-96f1-494418d1bdd9 http.request.method=HEAD http.request.remoteaddr=xxx.xxx.xxx.xxx http.request.uri="/v2/gitbucket/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" http.request.useragent="docker/1.6.2 go/go1.4.2 git-commit/7c8fca2 kernel/4.0.3-boot2docker os/linux arch/amd64" instance.id=79a6eaca-8b58-42b6-b213-d47a7b4cbde2 service=registry vars.digest="sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" vars.name=gitbucket version=v2.0.1
time="2015-06-23T16:26:33.040827291Z" level=info msg="s3.GetContent(\"/docker/registry/v2/repositories/gitbucket/_layers/sha256/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4/link\")" trace.duration=321.337529ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent" trace.id=899bd60c-e412-4728-ba53-62620cae8597 trace.line=55
time="2015-06-23T16:26:33.040919924Z" level=error msg="An error occured" environment=development err.code=UNKNOWN err.detail="Access Denied" err.message="unknown error" http.request.host=docker-registry http.request.id=f0a886e6-a374-4675-96f1-494418d1bdd9 http.request.method=HEAD http.request.remoteaddr=xxx.xxx.xxx.xxxhttp.request.uri="/v2/gitbucket/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" http.request.useragent="docker/1.6.2 go/go1.4.2 git-commit/7c8fca2 kernel/4.0.3-boot2docker os/linux arch/amd64" instance.id=79a6eaca-8b58-42b6-b213-d47a7b4cbde2 service=registry vars.digest="sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" vars.name=gitbucket version=v2.0.1
time="2015-06-23T16:26:33.04100446Z" level=info msg="response completed" environment=development http.request.host=docker-registry http.request.id=f0a886e6-a374-4675-96f1-494418d1bdd9 http.request.method=HEAD http.request.remoteaddr=xxx.xxx.xxx.xxxhttp.request.uri="/v2/gitbucket/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" http.request.useragent="docker/1.6.2 go/go1.4.2 git-commit/7c8fca2 kernel/4.0.3-boot2docker os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=323.300302ms http.response.status=400 http.response.written=83 instance.id=79a6eaca-8b58-42b6-b213-d47a7b4cbde2 service=registry version=v2.0.1
172.17.0.5 - - [23/Jun/2015:16:26:32 +0000] "HEAD /v2/gitbucket/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 HTTP/1.0" 400 83 "" "docker/1.6.2 go/go1.4.2 git-commit/7c8fca2 kernel/4.0.3-boot2docker os/linux arch/amd64"
```

**Comment by dmp42** [comment] 2015-06-23 21:41
ping @stevvooe @RichardScothern

**Comment by damnhandy** [comment] 2015-06-24 03:35
Scratch that. It turns out it was in fact an IAM permission issue. My initial policy was something like so:
```
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": "arn:aws:s3:::mybucket/*"
        }
```

Once I changed it to this:

        {
            "Effect": "Allow",
            "Action": "s3:ListAllMyBuckets",
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::mybucket"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::mybucket/*"
        }

Everything started working, proxy and all. Sorry for the false alarm. 

However, the documentation could highlight the necessary IAM polices for S3 and perhaps the error message could indicate what S3 calls it's trying to make. The message "An Error Occurred" is somewhat cryptic in determining the source of the error.

**Comment by stevvooe** [comment] 2015-06-24 17:29
@damnhandy Could expand on what you mean by adding documentation? I am a little unfamiliar with this particular problem and am unsure what exactly would need to be changed to help future users avoid this issue. Would mind submitting a PR to the s3 documentation?

cc @moxiegirl

**Comment by damnhandy** [comment] 2015-06-26 10:43
What I was getting that was that if you use a naïve IAM policy like I was doing, you run into issues. My issue was more of an AWS configuration problem and not a Registry problem. I will submit a PR next week for the docs. 

However, I can confirm that the registry is functioning just fine when using the both `HTTP_PROXY` and `HTTPS_PROXY` environment variables. But I am doing so using `--env-file` but things are indeed going through the proxy with the registry -> s3 communication. I would close this particular issue regarding the proxy.

**Comment by stevvooe** [comment] 2015-06-26 20:47
@damnhandy Thank you. I assume you'll be add something that will point out possible issues with IAM roles.

Looking at the registry logs a little more closely, it looks like the s3 library reports little context for the error. This explains the cryptic "Access Denied". I can't promise anything immediately, but I've filed #664 to explore some better error messages here.

**Comment by BrianBland** [comment] 2016-01-26 01:38
Closing with #1391 to cover the IAM permissions documentation

**Closed by BrianBland** 2016-01-26 01:38 UTC
Labels: bug, in progress, question
