### ISSUE TITLE
A Question about Tag Reference Internal Mechanism

### ISSUE THREAD

**Issue by xiekeyang** [docker/distribution#1174] opened 2015-11-10 10:46 UTC
Dears,
Now deleting image on distribution is through deleting only its revision reference file(revisions/.../link), with tags ref kept.
I'm not fully understanding on the internal mechanism that deleting tag ref will corrupt data backend.
I made some experience that deleting revision and tag ref, then push same tag name (different image) to hub, repeatedly. (like PR #1137 )
But I didn't find any corruption. If I ignore some critical case?
It seems that docker distribution refers to git/git project on object operation. Deleting git tag is through deleting its tag ref.
Could anyone please explain, some detailed, the internal corruption mechanism after deleting both revision and tag reference?
And, do you have some good idea to improve it?
Thank sooo much!

ping @RichardScothern @stevvooe

**Comment by stevvooe** [comment] 2015-11-10 20:28
@xiekeyang Tags in the docker registry are not like git tags (unfortunately). Because of the way manifests are represented, multiple images can have the same value for a given tag. We maintain the tag index to provide pointers to the current value of a tag, but also any manifest that is present that ever had that tag value. If you delete that directory, you delete the index of that tag value to any revision that had it. Thus, the operation corrupts the index, since it doesn't provide the guarantee of indexing all of the manifests under a given tag name.

This also has implications for concurrency. Each member of the index can be written concurrently, since the values are immutable. The only dangerous part is writing the current link, which is effectively last writer wins.

So, given this model, what happens during delete of a tag? The tag isn't really a resource, it is an index. Do we delete all the resources indexed by tag? This would be unexpected since we would have to delete all of the manifests that ever had that tag. What if we deleted only the current value for tag? That would be annoying. We would delete a resource, only to have it still there. The index effectively would also need to be a stack, maintaining an order of tag values.

The only right thing to do is to remove the entry in the tag index for the manifest being deleted. The problem is doing this consistently, avoiding race conditions. 

At this point, I've explained this a few times. I'd recommend carefully reading the code and understanding the path layout. Take the operations through a few scenarios and you'll see the issue.

**Comment by stevvooe** [comment] 2015-11-10 20:30
I think you'll also find #938 is directly related to this.

**Comment by xiekeyang** [comment] 2015-11-11 05:21
@stevvooe 
Appreciate for your explain!

**Comment by xiekeyang** [comment] 2015-11-16 10:23
@stevvooe 
I've an initial idea.
It may set up a database (nosql or k-v storage) to store manifest and its pointer (maybe needn't pointer any more).
Database can protect contect operation consistently, avoiding race conditions.
Manifests reference layers, and tags reference manifests. So, pointer or repo+tag name can be key, and manifest content can be value. Revision history and tag index may be uncessary. layer blobs are still saved according to CAS.
When deleting given image, we just have to remove the given k-v record from database.
I'd presented some idea on issue #1064.
If the idea is useful?  Thanks a lot!

**Comment by stevvooe** [comment] 2015-11-24 23:03
@xiekeyang Anything without transactions is going to make this hard.

Let's take this discussion over to #1064.

I'm going to close this issue, since it isn't very actionable in nature.

**Closed by stevvooe** 2015-11-24 23:03 UTC
