### ISSUE TITLE
how list all images or search api?

### ISSUE THREAD

**Issue by blackfader** [docker/distribution#441] opened 2015-04-27 08:38 UTC
docker resgistry v1 have search api,I can find what imags in registry.
```
https://docker.registry.cn/v1/search?q="+query
```

registry v2 has this api? I can not find.

**Comment by stevvooe** [comment] 2015-04-27 17:58
The V2 registry API does not support listing images. This is not present in the V2 API because not all implementations will have full knowledge of their contents. There is some discussion in #206 regarding what is actually required. We may add a catalog to the Registry 2.0 implementation, depending on what the actual requirement is.

If you need to manage images now, using [`storage.Walk`](http://godoc.org/github.com/docker/distribution/registry/storage#Walk) should provide access to the backend data.

This is a duplicate of #382.

**Comment by marians** [comment] 2015-06-24 05:49
Seems like this question is answered and the issue could be closed.

**Closed** 2015-06-24 17:06 UTC
Labels: question

**Comment by rferris** [comment] 2015-07-23 01:34
How can this issue possibly be closed? What sense does it make to have docker cli include a search command that only works with the official docker registry.

What is the point of running a private registry if you can never look at what images you have in it?

**Comment by stevvooe** [comment] 2015-07-23 02:09
@rferris Inspecting the contents of a registry is not the point of the `docker search` command. For this use case, we have already gone through the process of adding the [catalog API](https://github.com/docker/distribution/pull/653).

If you are curious about the state of search in relation to v2, please see the [road map](https://github.com/docker/distribution/blob/master/ROADMAP.md#indexing-search-and-discovery).

In the future, if you have questions about the state of the project, please use IRC or the mailing list rather than commenting on closed issues. Often times, there is context to the closure that you may not have.
