### ISSUE TITLE
Insane continuous traffic generated by registry

### ISSUE THREAD

**Issue by amsdard** [docker/distribution#2201] opened 2017-02-28 14:08 UTC
Hi, I'm using docker registry 2.6 and I've notice that registry is generating insane taffic by pulling unknown data from azure storage. In this month it generated over 900gbs, even when there is no activity at all, no pulls/pushes it still generates around 4-5gbs/h of traffic.

Redis is configured, cache is set. No errors in logs. Just periodic gets of manifests and tags done by portus I suppose. 

Is it normal? Can this be improved?

**Comment by dmp42** [comment] 2017-02-28 22:26
I don't think this is normal - though I'm not familiar with the azure driver code.
I would suggest trying to run *just* the registry and confirms whether the issue is with an add-on around it or not.
Also, since you are using Portus, I would definitely look into that first.

**Comment by amsdard** [comment] 2017-03-01 08:11
With portus turned off same problem occurs.

**Comment by dmp42** [comment] 2017-03-01 09:26
Can you start *just* a registry container (nothing else), and copy out the registry logs?

Thanks.

**Comment by amsdard** [comment] 2017-03-01 10:11
Hey, I've found a culprit! Storage health-check was on. When I turned it off, immediately registry stoped pulling data from azure storage and everything operates normal now :)

**Comment by aaronlehmann** [comment] 2017-03-02 00:37
If health checking was generating 5 gb of traffic per hour, that sounds like a serious bug or misconfiguration. Can you share the `health` section of your registry config?

My wild guess, without looking to verify any of this, is that leaving `interval` being unset might be interpreted as an interval of 0, or setting it to a number without a suffix like `s` (for seconds) might be interpreted as nanoseconds.

**Comment by amsdard** [comment] 2017-03-02 08:23
I was using default settings, nothing special:

`
health:
  storagedriver:

    enabled: true
    interval: 10s
    threshold: 3

`

**Comment by yuwaMSFT2** [comment] 2017-03-20 22:12
This seems due to old azure storage driver or azure go sdk. Not sure how/when the image was updated.

When I started registry:2 container with healthcheck enabled, I could see the requests going to Azure Blob Storage did NOT have the query parameter of maxresults set for the ListBlobs operation (which is used by healthcheck). What happens is that as your registry grows, the ListBlobs response will get bigger and bigger:

26 1.0;2017-03-20T21:01:12.8129752Z;ListBlobs;Success;200;8;6;authenticated;mytestxxxx;mytestxxxx;blob;"https://mytestxxxx.blob.core.windows.net:443/testossregistry?comp=list&amp;restype=container";"/mytestxxxx/testossregistry";e6bf6b6c-0001-0069-4ebd-a14e96000000;0;10.75.68.31:52874;2015-02-21;323;0;152;18324;0;;;;;;"Go-http-client/1.1";;
27 1.0;2017-03-20T21:01:22.8176156Z;ListBlobs;Success;200;9;7;authenticated;mytestxxxx;mytestxxxx;blob;"https://mytestxxxx.blob.core.windows.net:443/testossregistry?comp=list&amp;restype=container";"/mytestxxxx/testossregistry";e6bf765c-0001-0069-63bd-a14e96000000;0;10.75.68.31:52874;2015-02-21;323;0;152;18324;0;;;;;;"Go-http-client/1.1";;


The current azure driver does set the query parameter to retrieve only 1 result so the response size is small and constant:

1.0;2017-03-20T21:30:07.4432516Z;ListBlobs;Success;200;5;5;authenticated;mytestxxxx;mytestxxxx;blob;"https://mytestxxxx.blob.core.windows.net:443/testossregistry?comp=list&amp;maxresults=1&amp;prefix=%2F&amp;restype=container";"/mytestxxxx/testossregistry";1665415c-0001-0002-07c1-a113c0000000;0;167.220.0.108:62369;2015-02-21;345;0;152;1000;0;;;;;;"Go-http-client/1.1";;
1.0;2017-03-20T21:30:17.4406947Z;ListBlobs;Success;200;3;3;authenticated;mytestxxxx;mytestxxxx;blob;"https://mytestxxxx.blob.core.windows.net:443/testossregistry?comp=list&amp;maxresults=1&amp;prefix=%2F&amp;restype=container";"/mytestxxxx/testossregistry";16654a28-0001-0002-1ac1-a113c0000000;0;167.220.0.108:62369;2015-02-21;345;0;152;1000;0;;;;;;"Go-http-client/1.1";;

**Comment by yuwaMSFT2** [comment] 2017-03-20 22:42
@sivagms @SajayAntony

**Comment by yuwaMSFT2** [comment] 2017-03-21 19:25
On DockerHub, the registry distribution image seems to be still using older code on healthchecker.

In app.go RegisterHealthChecks, it still uses app.driver.List for the health check, which will list everything under the path and very expensive.

In latest code, this is changed to use app.driver.Stat which is much cheaper as mentioned earlier.
https://github.com/docker/distribution/commit/8e915d69f4b6a732ae9a8f616e5f4bc693f51539#diff-3ce751bb26687df9f572b431f7055afaR348

@aaronlehmann How/when do we update the registry image on DockerHub? This may not be specific to Azure.

**Comment by aaronlehmann** [comment] 2017-03-21 20:01
The version on Docker Hub is 2.6.0. This is the latest released version, which doesn't have the commit you linked to.

@dmcgowan do you think #2115 is something suitable for 2.6.1?

**Comment by dmcgowan** [comment] 2017-03-21 20:06
@aaronlehmann I think it is, let me make an rc2 with it

**Comment by dmcgowan** [comment] 2017-03-21 23:19
Please test and verify the release candidate for this fix `registry:2.6.1-rc.2`

**Comment by stevvooe** [comment] 2017-07-18 21:06
Closing as fixed.

Let me know if there are further issues.

**Closed by stevvooe** 2017-07-18 21:06 UTC
