### ISSUE TITLE
Alternative s3 host

### ISSUE THREAD

**Issue by FredrikNoren** [docker/distribution#767] opened 2015-07-28 04:10 UTC
I'm trying to use https://github.com/jubos/fake-s3 with the docker registry, but from what I can tell there's no way to configure the s3 hostname? Would be awesome to be able to configure that so that I can bind it to a container running fake-s3 (using this for development purposes).

**Comment by lorieri** [comment] 2015-08-02 03:05
Hi, could you test this ? 
https://github.com/docker/distribution/pull/808

cheers

**Comment by mboersma** [comment] 2015-09-27 14:44
This should be closed by #808.

**Comment by BrianBland** [comment] 2016-01-26 01:42
Closing as duplicate of #808

**Closed by BrianBland** 2016-01-26 01:42 UTC
