### ISSUE TITLE
Docker registry - basic authentication with htpasswd

### ISSUE THREAD

**Issue by plamer** [docker/distribution#655] opened 2015-06-22 09:12 UTC
Hello there,

I've noticed here https://docs.docker.com/registry/authentication/ that is suggested to use -B (Force bcrypt encryption of the password (very secure)) wth htpasswd when generating the password but it requires bcrypt. So after bringing up the nginx/registry images you get this on the server:
    
    nginx_1    | 2015/06/22 09:00:25 [crit] 5#5: *2 crypt_r() failed (22: Invalid argument)

and this on the client trying to authenticate to the registry:

    FATA[0000] Error response from daemon: no successful auth challenge for https://someregistry.something:443/v2/ - errors: [basic auth attempt to https://someregistry.something:443/v2/ realm "registry.localhost" failed with status: 500 Internal Server Error]

After using htpasswd without -B (htpasswd -bc ...) it worked right away.

**Comment by hunterchung** [comment] 2015-06-23 01:49
I got the same error, and your answer saved me. THanks @plamer !

**Comment by stevvooe** [comment] 2015-06-25 20:10
@plamer The problem here is with nginx's support for htpasswd file. The use of `htpasswd -bc` uses the insecure apache md5 algorithm. We recommend that users use bcrypt.

What version of nginx are you using? What operating system are you running (`$ uname -a`)?

**Comment by hunterchung** [comment] 2015-06-25 20:38
Mine was pulled from [docker hub](https://registry.hub.docker.com/_/nginx/), the latest one, which should be `1.9.2`.

**Comment by plamer** [comment] 2015-06-25 20:59
Hey @stevvooe , I'm using nginx:1.9 and registry:2, followed the docs. Running docker on CentOS 7.

**Comment by stevvooe** [comment] 2015-06-26 01:06
Sounds like [support for bcrypt](http://trac.nginx.org/nginx/ticket/382) is OS dependent. Nginx relies on the libc implementation of `crypt` (in this case `crypt_r`). This is going to be dependent on the container's OS where nginx is running, so I am not sure of the cause here. The host OS should not affect this.

Here is another another link describing the issue:

https://answers.launchpad.net/ubuntu/+source/nginx/+question/263001

I am not sure what the resolution here should be. I'd not recommend using an insecure authentication password format. I am assuming this worked for @dmp42 when he wrote the guide.

**Comment by Wombasta** [comment] 2015-07-01 12:13
I experience the same issue. I configured everything according to https://docs.docker.com/registry/authentication/ and double-checked everything. Nothing helps with bcrypt except not using it (as suggested in this issue).

**Comment by phuihock** [comment] 2015-07-01 13:20
I have the same issue. Further investigation led me to this http://stackoverflow.com/a/30545501/228683
Because nginx:1.9 is based on Debian Jessie, it seems there's no way of getting it to work short of recompiling glibc. I end up using salted sha password.

**Comment by stevvooe** [comment] 2015-07-01 23:10
@phuihock @Wombasta @plamer I'd recommend filing an issue over at https://github.com/docker-library/official-images/issues to correct the base image to have proper support for bcrypt. Using a less secure hash is not a good option. If you don't care, use `htpasswd` without bcrypt. Optionally, just use Apache HTTPD, which supports bcrypt of the box.

I'm not sure if this will help, but we've become tired of dealing with nginx's edge cases for new users, so registry 2.1 will come with htpasswd based basic auth support.

@dmp42 PTAL

**Comment by melon** [comment] 2015-07-02 06:23
same issue!
ubuntu 14.04  nginx 1.9  registry 2

**Comment by stevvooe** [comment] 2015-07-02 19:21
@Wombasta Thank your for filing the issue. I've filed the issue over at nginxinc/docker-nginx#29.

**Comment by thresheek** [comment] 2015-07-02 22:35
I guess the docs needs to be fixed to use SHA-2.

**Comment by stevvooe** [comment] 2015-07-03 00:50
@thresheek I'm going to see if we can track down the source of this problem and get it fixed there. I'd rather not suggest people use an insecure hash or one that is incompatible with the htpasswd support coming in 2.1 (only bcrypt is supported).

If this is unsuccessful, we'll get the docs fixed before 2.1.

**Comment by soulcreate** [comment] 2015-07-14 09:32
some problem for me.

**Comment by dmp42** [comment] 2015-08-10 23:13
We removed bcrypt from the Nginx specific documentation, and also made the native basic auth feature the recommended default (that does support bcrypt).

Documentation has been fixed in #837

**Closed by dmp42** 2015-08-10 23:13 UTC
Labels: documentation, question

**Comment by cshimmin** [comment] 2015-09-26 22:19
Just wanted to chime in and say this is still a time sink. Ran into the exact issue (standard nginx container trying to share htpasswd with registry:2) and it took a long time for me to figure this out.

The only docs I encountered (namely [1]) simply mention that bcrypt is "recommended" when in fact it is required. The comment in #837 is very indirect and doesn't make the issue clear. Either this requirement should be stated very clearly ("htpasswd **must** be encrypted with bcrypt"), or even better simply support less secure hashes.

[1] https://docs.docker.com/registry/deploying/

**Comment by dmp42** [comment] 2015-09-28 05:34
@cshimmin https://github.com/docker/distribution/blob/master/docs/nginx.md contains explicit steps for nginx.

**Comment by burningTyger** [comment] 2016-06-12 19:06
nginx.md is here now: https://github.com/docker/distribution/blob/master/docs/recipes/nginx.md

**Comment by cdaringe** [comment] 2017-01-29 06:14
eeek. both links are dead

**Comment by stevvooe** [comment] 2017-01-30 20:16
@cdaringe Those docs have been moved to the docs repo: https://github.com/docker/docker.github.io/tree/master/registry/recipes.

**Comment by aikomastboom** [comment] 2017-02-16 11:34
workaround: use `nginx:alpine` image
https://github.com/nginxinc/docker-nginx/issues/29#issuecomment-194817391

**Comment by innocent-wang** [comment] 2017-12-24 10:54
-bc  solve the problem

**Comment by toopay** [comment] 2019-07-25 09:44
Solved using `-d` flag 
> Force CRYPT encryption
