### ISSUE TITLE
Image digest changes when layer is pushed to different repos.

### ISSUE THREAD

**Issue by VascoVisser** [docker/distribution#694] opened 2015-07-12 15:23 UTC
One of my images has a problematic layer that is always pushed when I push the image to different repos on my private registry. Let's call the repos A and B. When I push the image to a new repo A all layers are pushed as expected. Calling push again for A works as expected, nothing is pushed. Then I tag the image for B and push it. The problematic layer is pushed. Now I call push on B again, works as expected; nothing pushed. Now I call push on A; the problematic layer is pushed again! Now calling push on A again, works as expected. So:

push A > initial push
push A > nothing pushed
push B > push problem layer
push B > nothing pushed
push A > push problem layer
push A > nothing pushed
... repeat ad infinitum.

Inspecting the logs of registry I see that the digest of the problem layer is different every time it is pushed! No rebuilds occur, so I take it the digest should be the same?? Maybe this is not a distribution issue but a docker issue? I can't seem to get digest info out of the docker cli, so I can't even verify if the registry and local docker agree on the digest. The digest column in the cli output just shows `<none>` everywhere.

docker v1.7.0, build 0baf609
distribution v2.0.1

**Comment by stevvooe** [comment] 2015-07-13 23:23
@VascoVisser Thank you for the report.

This is an issue we are well aware of. This is a problem in docker, covered by docker/docker#14018, docker/docker#13945 and docker/docker#14067. The root cause of this issue is that, internally, docker is still very much tied to the v1 image model.

I'm closing this, as having another open issue around this is not constructive.

**Closed by stevvooe** 2015-07-13 23:23 UTC
