### ISSUE TITLE
Not able to run the registry with a task IAM role in AWS

### ISSUE THREAD

**Issue by danielezer** [docker/distribution#2585] opened 2018-05-16 13:40 UTC
Hi, I am running the docker-registry as an ECS service and I want to give it a task IAM role. This is only supported for aws-sdk versions that were release on July 13th, 2016 or later. You can see the documentation that state that here - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html

The task IAM role is not working for me but when I use an IAM role for the EC2 host that the container is running on, it does work. This means that the aws-sdk is probably outdated, could you please upgrade it? thanks!

**Comment by dmp42** [comment] 2018-05-25 22:17
Duplicate of #2579

**Closed** 2018-05-25 22:18 UTC
Labels: duplicate
