### ISSUE TITLE
Private registry 2.1.1 pull fail with MANIFEST_UNKNOWN Error

### ISSUE THREAD

**Issue by davelesser** [docker/distribution#880] opened 2015-08-15 00:45 UTC
I'm experiencing a `MANIFEST_UNKNOWN` error when trying to pull an image when running registry 2.1.1. I'm able to successfully pull the image using 2.0.1, but when running 2.1.1, I get the following:

```
$ docker pull <REDACTED>/hubot
Pulling repository <REDACTED>/hubot
Error: image hubot:latest not found
```

Here are all the logs (daemon and registry) for both pulls:

https://gist.github.com/davelesser/d7a759459e88322b5690

Here are the specifics of our setup:

- Running in AWS ECS with S3 as the storage backend
- The ELB receives traffic on port `80` and forwards it to port `6000` on the host
- We are not overriding the default `ENTRYPOINT` or `CMD`
- We are using the default `/etc/docker/registry/config.yml`, but are overriding with environment variables
- The environment variables passed to the container are in the gist linked to above

Please let me know what other information might be helpful to you and I'm happy to provide it.

**Comment by dmp42** [comment] 2015-08-15 03:52
Thanks for the thorough details @davelesser 
We'll look into it.

**Comment by RichardScothern** [comment] 2015-10-02 01:03
@davelesser : is this still an issue for you?  I've been trying to clear things up in #892

**Comment by davelesser** [comment] 2015-10-03 00:23
Given the issues we ran into using 2.1.1, we rolled back to 2.0.1 and have been there ever since. I just stood up some new infrastructure to test 2.1.1 and pointed it at the same S3 bucket and used the exact same configuration as our 2.0.1 registry. So, while there are two URLs for the repos, they're using the same underlying data.

Results: A quick spot check of 2.1.1 shows that while it doesn't error out on **all** pulls, it still has problems with some tags. 

Examples (both done using Docker version 1.8.2, build 0a8c2e3):

***Registry 2.0.1***
```
$ docker pull <2.0.1_registry>/hubot:4575551822f8d6be1fd789660692bb49d5aeb932
4575551822f8d6be1fd789660692bb49d5aeb932: Pulling from hubot
9213e81cb0f2: Pull complete
6ad0799af6bd: Pull complete
e0919a8b95a8: Pull complete
3383909e8f95: Pull complete
8b74d7a75802: Pull complete
9e20baae42c8: Pull complete
4bee955758de: Pull complete
e282603d8ecc: Pull complete
e614c9a69941: Pull complete
e6f27935dbf0: Pull complete
0e313d9287c7: Already exists
902b87aaaec9: Already exists
9a61b6b1315e: Already exists
1ff9f26f09fb: Already exists
607e965985c1: Already exists
Digest: sha256:e253a63be22e84c8f57dc8bd8d971f4657023494fa5770e9fc58e89c948271e3
Status: Downloaded newer image for <2.0.1_registry>/hubot:4575551822f8d6be1fd789660692bb49d5aeb932
bash-4.3$
```
vs.

***Registry 2.1.1***
```
$ docker pull <2.1.1_registry>/hubot:4575551822f8d6be1fd789660692bb49d5aeb932
Pulling repository <2.1.1_registry>/hubot
Error: image hubot:4575551822f8d6be1fd789660692bb49d5aeb932 not found
```

**Comment by RichardScothern** [comment] 2015-10-05 17:27
Thanks for digging back into this @davelesser 

Just so I understand this.
1) All data was pushed with `2.0.1` 
2) All data can be pulled with `2.0.1`.
3) Some pulls fail with `2.1.1`.  

Are there specific repositories that cannot be pulled or specific tags within a repository (or both?)

**Comment by davelesser** [comment] 2015-10-05 17:34
Items 1 through 3 are correct. 

I haven't come across any repositories which, as a whole, cannot be pulled...just specific tags.

**Comment by RichardScothern** [comment] 2015-10-12 17:18
thanks for the info @davelesser .  This is a bit ask, but could you inspect the file layout for the problematic repositories?  If it's on a posix file system `tree` or `find $root -ls` would do the trick

**Comment by davelesser** [comment] 2015-10-13 20:03
@RichardScothern It's backed by S3, so I ran a quick script to list out the keys for the problematic repository:

https://gist.github.com/davelesser/fa11565c964307359c3d

Not quite as easy to read as the output from `tree`, but it shows the structure and was the simplest way to get the info you requested. If you need more info, or if I screwed something up, please let me know and I'll get you whatever you need..

**Comment by RichardScothern** [comment] 2015-10-30 00:56
Thanks for the files @davelesser .  Without registry logs and the specific manifest/tag pairing I'm not sure how to debug.  I cannot reproduce this myself.

**Comment by dmp42** [comment] 2016-01-22 00:38
@davelesser any update on this?

**Comment by dmp42** [comment] 2016-01-25 19:24
@davelesser closing for book-keeping. Let us know if you still experience problems.

**Closed by dmp42** 2016-01-25 19:24 UTC
