### ISSUE TITLE
Support fro V2 authentication in S3 storage driver

### ISSUE THREAD

**Issue by sergeyfd** [docker/distribution#1796] opened 2016-06-21 16:36 UTC
Hello,

There are many S3-compliant storage providers that yet not support V4 authentication schema. Would it be possible to add support for V2 authentication into S3 driver? It looks like AWS SDK provides V2 signer: https://github.com/aws/aws-sdk-go/issues/547

**Comment by The-Loeki** [comment] 2016-07-29 07:47
Pretty much duplicate of #1796

**Closed** 2016-09-01 20:52 UTC
