### ISSUE TITLE
Registry with S3 backend returns 404

### ISSUE THREAD

**Issue by akerekes** [docker/distribution#873] opened 2015-08-13 21:35 UTC
We're running a private registry which uses S3 as backend storage, version 2.0.1.

We have several issues, the most recent is that pulling images are barely working.
I've created a new registry instance, and started to pull the same image from several clients.
There are a few HTTP 200s in the log but then 404s start to appear and then all pull requests fail.
For the 404s I have a few different error in the log:

- error fetching signature from \\\"/docker/registry/v2/repositories/<image_name>/_manifests/revisions/sha256/<sha>/signatures/sha256/<sha>/link\\\": The request signature we calculated does not match the signature you provided. Check your key and signing method.
- error fetching signature from <long url with AWS security token included>: net/http: transport closed before response was received\

Upgrading to 2.1.1 we got the manifest unknow errors like in #861 

```
$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

The same setup works in another environment. Any clues what should I look at?

**Comment by dmp42** [comment] 2015-08-13 22:12
2.1.1 *fixed* #861 

If things work well in another environment, it's quite likely the problem is with the environment itself.

That being said, I need more information to provide any valuable feedback, specifically things listed here: 
 https://github.com/docker/distribution/blob/master/CONTRIBUTING.md#if-you-have-not-found-an-existing-issue-that-describes-your-problem

Be sure to include registry logs at the moment you got failure, and also docker daemon logs at the same moment.

Any other details about your specific setup (proxy? load balancers?) and associated error logs might help.

**Comment by akerekes** [comment] 2015-08-14 20:24
I know #861 was fixed by 2.1.1, that's what I wanted to point out, that I'm hitting the same or a very similar bug with same symptoms.

Here is the info requested:

```~# docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64```

```~# docker info
Containers: 1
Images: 33
Storage Driver: aufs
 Root Dir: /mnt/docker/aufs
 Backing Filesystem: extfs
 Dirs: 35
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-46-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 3.676 GiB
Name: ip-172-24-8-194
ID: VTNH:7VLJ:PQ7L:UMMN:YF43:Q7BJ:BJIV:QRSF:QU3P:524F:O2HP:3MNT
WARNING: No swap limit support```

```~# docker exec registry_v2 registry -version
registry github.com/docker/distribution v2.1.1```

Command to start the registry:
```"/bin/registry /etc/docker/registry/config.yml"```

What I observed is that the error comes up under heavy load. When I'm pulling from a single client, everything is fine. But in our system we have 20-40 nodes launching 10-20 containers per node quite frequently, and after a while errors start to appear in the log. The registry has a few thousand connection to S3 (I saw values between 4K and 20K). Getting logs from the docker daemons corresponding with logs from the registry would be quite difficult.

Our setup runs on AWS, the clients are connecting to an elastic load balancer, which in turn connects to an nginx instance proxying request to the registry's container.

For the sake of testing I have launched a few more registry instances, and that has reduced the errors significantly.

**Comment by dmp42** [comment] 2015-08-14 20:53
Thank you @akerekes 

About fetching the logs, wouldn't `docker logs registry_container` get you these?

ping @docker/distribution-maintainers here.

`error fetching signature from : net/http: transport closed before response was received` is interesting.

**Comment by RichardScothern** [comment] 2015-08-14 21:06
@akerekes : just to clarify.  You are only seeing these errors under load?  If that is the case #861 is not your issue.  You would receive 404 errors 100% of the time if you were.

Unfortunately, our vendored s3 library does not reuse TCP connections which would explain what you are seeing in regards to S3.  I wonder if AWS is closing them on you due to this.

**Comment by akerekes** [comment] 2015-08-17 21:11
@dmp42 yeah, I thought fetching the logs from the clients would be difficult: finding correlation logs in the registry log and one of the clients logs (having many request per minute). I have some error messages from the registry container log.

@RichardScothern I guess then it must be because of the s3 library. What I saw is that two registry instances were producing close the 50% error responses, but then scaling them up to 10 has basically made the errors disappear. Scaling down after a while and the errors did not reappear, not sure why. We're trying to reproduce the high-load scenario and hopefully see the 404s reappearing.

Here are the error messages I saw at the registry:

```
{"log":"time=\"2015-08-14T14:45:08.542589846Z\" level=warning msg=\"the ResponseWriter does not implement CloseNotifier\" environment=dev http.request.host=XXXXX http.request.id=2b24191e-495d-4f6b-908e-1bf6a4d4bb11 http.request.method=PUT http.request.remoteaddr=172.24.0.32 http.request.uri=\"/v2/XXXXX/blobs/uploads/da0165d1-8735-41b8-8722-187af8f7752e?_state=XR-daVPRU_EeHkCQ6pMzUUGWD5sytIOneFhgVSiHfZp7Ik5hbWUiOiJjb250ZW50LnB5IiwiVVVJRCI6ImRhMDE2NWQxLTg3MzUtNDFiOC04NzIyLTE4N2FmOGY3NzUyZSIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNS0wOC0xNFQxNDo0NDo1NC4zODAxMDY0OThaIn0%3D\u0026digest=sha256%3Ae6589ada9c3d80f584fbbe185adf4f00de5a798e2cc8ac29972d1d7beb1261fe\" http.request.useragent=\"docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.13.0-46-generic os/linux arch/amd64\" instance.id=7249bedf-8152-4edd-9e6b-11f5a005d385 service=registry vars.name=content.py vars.uuid=da0165d1-8735-41b8-8722-187af8f7752e version=v2.1.1 \n","stream":"stdout","time":"2015-08-14T14:45:08.54295055Z"}

{"log":"time=\"2015-08-14T14:37:51.448007979Z\" level=error msg=\"response completed with error\" environment=dev err.code=\"MANIFEST_UNKNOWN \" err.detail=\"Get https://s3.amazonaws.com/XXXXX/registry/docker/registry/v2/repositories/XXXXX/_manifests/r evisions/sha256/8a03dbad664a66199e26f3dfffc9fbfedbab234861e1277d895db2b73b2c0d9f/signatures/sha256/ddf873addee2023c813fbfa8f193df6b3f85aab887 ee0d7bbce1719d502f8e0f/link?X-Amz-Security-Token=XXXXX: net/http: transport closed before response was received\" err.message=\"manifest un known\" http.request.host=XXXXX http.request.id=87a014fa-d781-4aeb-9b49-bfb642bd5246 http.request.method=GET http .request.remoteaddr=172.24.0.158 http.request.uri=\"/v2/XXXXX/manifests/latest\" http.request.useragent=\"docker/1.7.1 go/go1.4.2 git-co mmit/786b29d kernel/3.13.0-46-generic os/linux arch/amd64\" http.response.contenttype=\"application/json; charset=utf-8\" http.response.durat ion=7m4.482973738s http.response.status=404 http.response.written=1133 instance.id=7249bedf-8152-4edd-9e6b-11f5a005d385 service=registry vars .name=XXXXX vars.reference=latest version=v2.1.1 \n","stream":"stdout","time":"2015-08-14T14:37:51.448230884Z"}

{"log":"time=\"2015-08-14T14:37:51.44725211Z\" level=error msg=\"response completed with error\" environment=dev err.code=\"MANIFEST_UNKNOWN\ " err.detail=\"Get https://s3.amazonaws.com/XXXXX/registry/docker/registry/v2/repositories/XXXXX/_manifests/re visions/sha256/8a03dbad664a66199e26f3dfffc9fbfedbab234861e1277d895db2b73b2c0d9f/signatures/sha256/2e2f022f06aca8dce6297580ff2aab533c9026ea9ab 7a003ad794933bb314c57/link?X-Amz-Security-Token=XXXXX: EOF\" err.message=\"manifest unknown\" http.request.host=XXXXX http.request.id=8bef1c07-47d6-4ecc-93e4-37369f9e9e35 http.request.method=GET http.request.remoteaddr=172.24.0.232 http.request.uri=\"/ v2/XXXXX/manifests/latest\" http.request.useragent=\"docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.13.0-46-generic os/linux arch/a md64\" http.response.contenttype=\"application/json; charset=utf-8\" http.response.duration=7m4.477071993s http.response.status=404 http.resp onse.written=1133 instance.id=7249bedf-8152-4edd-9e6b-11f5a005d385 service=registry vars.name=XXXXX vars.reference=latest version=v2.1.1  \n","stream":"stdout","time":"2015-08-14T14:37:51.447438418Z"}
 
{"log":"time=\"2015-08-14T14:37:35.956105023Z\" level=error msg=\"error fetching signature \\\"sha256:2277607a0d5963146ea61b93a38a754252c31f7 c0624232bb002040d6c08b3d4\\\": Get https://s3.amazonaws.com/XXXXX/registry/docker/registry/v2/repositories/XXXXX/_manifests/revisions/sha256/8a03dbad664a66199e26f3dfffc9fbfedbab234861e1277d895db2b73b2c0d9f/signatures/sha256/2277607a0d5963146ea61b93a38 a754252c31f7c0624232bb002040d6c08b3d4/link?X-Amz-Security-Token=XXXXX: EOF\" environment=dev http.request.host=XXXXX http.request.id=245cdf02-d30f-494d-bfba-39792ccb5dea http.request.method=GET http.request.remoteaddr=172.24.2.113 http.request.uri=\"/v 2/XXXXX/manifests/latest\" http.request.useragent=\"docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.13.0-46-generic os/linux arch/am d64\" instance.id=7249bedf-8152-4edd-9e6b-11f5a005d385 service=registry vars.name=XXXXX vars.reference=latest version=v2.1.1 \n","stream ":"stdout","time":"2015-08-14T14:37:35.956328865Z"}

{"log":"time=\"2015-08-14T14:48:36.365509337Z\" level=error msg=\"response completed with error\" environment=dev err.code=\"BLOB_UNKNOWN\" err.detail=sha256:ba1be07a1643a89fa2a36066e070f1bb403c1248b2447e6b5958eeb23644392e err.message=\"blob unknown to registry\" http.request.host=XXXXX http.request.id=5544e737-5641-4905-8992-2c13ec6b8ded http.request.method=HEAD http.request.remoteaddr=172.24.0.32 http.request.uri=\"/v2/XXXXX/blobs/sha256:ba1be07a1643a89fa2a36066e070f1bb403c1248b2447e6b5958eeb23644392e\" http.request.useragent=\"docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.13.0-46-generic os/linux arch/amd64\" http.response.contenttype=\"application/json; charset=utf-8\" http.response.duration=4.050964698s http.response.status=404 http.response.written=157 instance.id=7249bedf-8152-4edd-9e6b-11f5a005d385 service=registry vars.digest=\"sha256:ba1be07a1643a89fa2a36066e070f1bb403c1248b2447e6b5958eeb23644392e\" vars.name=XXXXX version=v2.1.1 \n","stream":"stdout","time":"2015-08-14T14:48:36.365630759Z"}
```

**Comment by RichardScothern** [comment] 2015-10-02 01:04
@akerekes : is this still an issue for you?

**Comment by akerekes** [comment] 2015-10-02 13:44
We implemented a workaround by installing docker registry to all our worker nodes locally thus distributing the load and since then we haven't seen this type of error.

Since then we haven't tested it with high load on a single instance so not sure whether it has been resolved or still exists.

**Comment by RichardScothern** [comment] 2015-10-02 17:04
OK, I'm closing this for now.  We have seen a lot of temporal S3 errors

**Closed** 2015-10-02 17:04 UTC
Labels: question

**Comment by akerekes** [comment] 2015-10-02 18:01
For the records, because I seem to recall to find a cause for some of the error I'm linking here a libc bug and the corresponding golang issue which can cause connection errors under heavy load:

https://github.com/golang/go/issues/6336
https://sourceware.org/bugzilla/show_bug.cgi?id=15946

Also a workaround is described but it requires enabling the pure-go resolver by rebuilding the standard library with it turned on. Being a go beginner, not sure if it only means rebuilding go on the host or also rebuilding the registry code is required.

**Comment by stevvooe** [comment] 2015-10-13 21:01
@akerekes That is a nasty bug but could explain some behavior we've seen in certain systems, with and without the registry.

We may opt for the pure Go resolver when we upgrade to using Go 1.5 by default.
