### ISSUE TITLE
push a same image to the registry:2.0 and registry:0.9 ，the registry:2.0's growing size is more bigger than registry:0.9 

### ISSUE THREAD

**Issue by liuwanzhi** [docker/distribution#708] opened 2015-07-17 02:34 UTC
we pulled two images from registry0.9, imageA and imageB , imageA is imageB's base image

1 run registry2.0 container 
     docker run -d --privileged=true --net=host --name registry-2 -e SETTINGS_FLAVOR=local -e REGISTRY_HOST=localhost -e REGISTRY_PORT=5000 registry:2.0 
	 
2  firstly, wo commit the empty rigisty2.0 and see the virtual size is  548.6 MB
    (1)docker commit registry2.0-containerID  registry2.0
	localhost:5000/registry                        2.0                     ec94325cd2c4        4 weeks ago         548.6 MB
	(2) then push imageA ,and commit and see the virtual size is 1.039G
	    docker push localhost:5000/imageA 
		docker commit registry2.0-containerID  registry2.0
    the grow size is 491M 
	(3) push imageB , commit and see th virtual size is 1.119 GB
	the grow size is 70M

3 then I run registy0.9 container and do the same thing 
         (1)	when the registry is empty, we commit and see the virtual size is 413.8 MB
	(2) after pushed imageA, commit and see the virtaul size is 903.5 MB,
	    the grow size is 389.7M , the grow size is as same as regisry2.0 growed
	(3)but when I pushed imageB , commit and see th virtual size is 920.6 MB
	    the grow size only 17M

so why imageB's  grow size in registry2.0 is bigger than in registry0.9 ?

**Comment by dmp42** [comment] 2015-07-17 05:02
Different compression settings?

**Comment by bohai** [comment] 2015-07-17 06:54
@dmp42   
Do you mean the registry2.0 and registry0.9 use the different compress ration settings?  
And how to modify the compress ratio settings?

**Comment by oilbeater** [comment] 2015-07-17 07:28
In fact the compression is processed in client side. 

And the way you comparing size is not accurate. The difference between two container size can from log, some intermediate file, blob, metadata and so on.

As I tested, the blob size is different but the content in the tar file is same. So I guess docker client use different archive method for different registry.

**Comment by dmp42** [comment] 2015-07-17 16:03
@oilbeater this is correct
Protocol v2 and v1 are significantly different, and size discrepancies is expected.

@bohai you cannot modify compression settings on the client side - and the registries themselves don't touch the payloads.

@liuwanzhi I'm closing this as "answered" - if you still feel this is not satisfactory, I'll reopen.

Thanks.

**Comment by bohai** [comment] 2015-07-20 02:18
@dmp42  
Thanks for your answer. I still have some question about this thing.

**I feel maybe there is a defect in the V2 registry.**
The below is the detail information and my analyzation.

I pushed the same image to the registry0.9 and registry 2.0.1. And then commit the registry    containers and save them  as tar file.
And then go through the tar file , and see what happened in them .

### In the 0.9 registry:
/home/0.9.3/a6c847604ae100de4ffcacc06ebcf3db05326758c9609fc4d3a29bb36c832676/tmp/registry/images
[root@localhost images]# du -hs * |grep M
45M     1753f91adeef2a15a9d3ba11a0c7e570cef5cc39c3eb8ea995f6505c60a66b1f
320M    480e5080a24e3d069615143445d62e2101677148da2ff92197c64fe1171a98be
37M     73a756be114946cfd8415ebc7c25bc41355fe1ca5d398deee93c538b286adeea
60M     b6ae834858770d2c32c811460d480311575ff15090d3f6486d7b68242fc45a2d
325M    c08e0d908fd705c459adc5b49008eed77339e0a266797c25a8da24baeedd6657

### But in the 2.0.1registry:
[root@localhost sha256]# pwd
/home/2.0.3/edbf1f4011ccdbd151d8e59e136e011dbb17465ff2fd99965ee66d070620bd3d/tmp/registry-dev/docker/registry/v2/blobs/sha256
[root@localhost sha256]# du -hs *|grep M
105M    15
320M    20
60M     d2
37M     d3
326M    e8

**We can see almost every layer is same only one exception.**         
**A 45M  layer in the 0.9 registry becomes 105M layer in the 2.0.1 registry.** 

Then i enter the directory, and see what's the reason.  
### in the 0.9 registry
[root@localhost images]# du -hs 1753f91adeef2a15a9d3ba11a0c7e570cef5cc39c3eb8ea995f6505c60a66b1f/*
4.0K    1753f91adeef2a15a9d3ba11a0c7e570cef5cc39c3eb8ea995f6505c60a66b1f/ancestry
4.0K    1753f91adeef2a15a9d3ba11a0c7e570cef5cc39c3eb8ea995f6505c60a66b1f/_checksum
4.0K    1753f91adeef2a15a9d3ba11a0c7e570cef5cc39c3eb8ea995f6505c60a66b1f/json
45M     1753f91adeef2a15a9d3ba11a0c7e570cef5cc39c3eb8ea995f6505c60a66b1f/layer

### in the 2.0.1 registry 
[root@localhost sha256]# du -hs 15/*
45M     15/15410c7dd43c023c605b7daeaa99ee3d6f0e3a8b82d222f525b57433a5b281d5
60M     15/15aadd037d91d1f9907b6bc14b536d42671542be1e483cef5a6366092e6903d8

**I doubt the 60M layer is saved twice in registry 2.0.1**

**Comment by bohai** [comment] 2015-07-20 06:52
@dmp42

Could you reopen the issue to make more people pay the attentions.

**Comment by oilbeater** [comment] 2015-07-20 09:43
I can't reproduce your result. As far as I can guess from your description, there is two layers in 15/ and the data file in the layer directory is also a tar file. May be you can extract it and find more information.

However, as different layer will have different tarsum, I guess the two 60M layers are different in content.

**Comment by bohai** [comment] 2015-07-20 11:19
@oilbeater 
Thanks. 
I will try to make a  simple and reproduce example. 
I tried to look the content of the 60M file  and found the files are similar.(I am sorry, i didn't find a method to verify all the files are same )

**Comment by jimmyxian** [comment] 2015-07-25 09:34
@dmp42 Can you reopen this issue? Thanks
@liuwanzhi @bohai @oilbeater 
Maybe I meet the same issue. Reproduce step:

### 1. Environment:
```
[root@localhost ~]# docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

[root@localhost ~]# docker info
Containers: 0
Images: 22
Storage Driver: devicemapper
 Pool Name: docker-8:3-25559259-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 956.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 106.4 GB
 Metadata Space Used: 1.688 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.7-200.fc21.x86_64
Operating System: Fedora 21 (Twenty One)
CPUs: 24
Total Memory: 39.29 GiB
Name: localhost.localdomain
ID: 4X4Z:SGWX:TE4M:ZMJ6:SHEO:M6OY:AOIC:NTMD:E6QZ:CLE7:INSO:GJBK
Debug mode (server): true
File Descriptors: 20
Goroutines: 17
System Time: 2015-07-25T04:41:44.101328519-04:00
EventsListeners: 0
Init SHA1: 40961d6bd68cc99eba3cb8b5a8e91c021b087934
Init Path: /usr/libexec/docker/dockerinit
Docker Root Dir: /var/lib/docker
```
### 2. Reproduce Step
```
[root@localhost xcb]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
registry            2.0.1               f9684be4155a        10 days ago         548.6 MB

[root@localhost xcb]# docker run -d  -p 5200:5000 --name 2.0.1 registry:2.0.1
8fe6d4479136b33b66d531eb407fa8d13ed002a3e2d2596debd654c6d20726b7
```
#### 2.1 Push image(registry:latest)
```
Host:
[root@localhost xcb]# docker tag f9684be4155a 127.0.0.1:5200/registry:latest
[root@localhost xcb]# 
[root@localhost xcb]# docker push 127.0.0.1:5200/registry:latest
The push refers to a repository [127.0.0.1:5200/registry] (len: 1)
f9684be4155a: Image already exists 
6df65975f079: Image successfully pushed 
10afac01c05b: Image successfully pushed 
98cc4694054b: Image successfully pushed 
e6c388bc67fb: Image successfully pushed 
66780839eff4: Image successfully pushed 
6a192b88c36f: Image successfully pushed 
aeb43bf230e4: Image successfully pushed 
124e2127157f: Image successfully pushed 
69c177f0c117: Image successfully pushed 
141b650c3281: Image successfully pushed 
8fb45e60e014: Image successfully pushed 
63e9d2557cd7: Image successfully pushed 
b279b4aae826: Image successfully pushed 
d86979befb72: Image successfully pushed 
8ddc08289e1a: Image successfully pushed 
8d38711ccc0d: Image successfully pushed 
0f5121dd42a6: Image successfully pushed 
607e965985c1: Image successfully pushed 
1ff9f26f09fb: Image successfully pushed 
9a61b6b1315e: Image successfully pushed 
902b87aaaec9: Image successfully pushed 
Digest: sha256:eee530e672a0106fddea284d2b8d5cb7325f542da41eebdaac24674f8406421d
```
##### Question1: why first layer already exists ?

Registry Container:
```
[root@localhost ~]# docker exec -it 2.0.1 /bin/bash
root@8fe6d4479136:/# cd /tmp/registry-dev/docker/registry/v2/blobs/sha256
root@8fe6d4479136:/tmp/registry-dev/docker/registry/v2/blobs/sha256# du -h 
52K	./ee/eee530e672a0106fddea284d2b8d5cb7325f542da41eebdaac24674f8406421d
56K	./ee
11M	./ba/bad54a5c2ae3392a1a6224d8ab5a5400fe79b983fe423a98a56981595f2ee6c9
11M	./ba
8.0K	./dd/ddf532273b60e90431d7630711d2a31b1ab73424d88c4569fd6c793a173cdae0
12K	./dd
24M	./44/44590cce7a4f3d85cc2a5ec978512b469bd9b873f5e9c2acaa80181277276edc
24M	./44
41M	./c3/c33eb106dfcf81f8ecefeb8890e1c4cbddd97a27bb31ea49894f949a5243c4ab
41M	./c3
31M	./f9/f9a0522cbaa228af3def597b0790db18c802aba4a2b7e1c4a1054fed0dfdc41a
31M	./f9
8.0K	./a3/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
12K	./a3
3.1M	./25/259e85cb2eba63b0813396e884f16c18163c0b72edbef84dbdbb4f14cc60bb14
3.1M	./25
6.6M	./f4/f4fd525d70fd60cabafc2d2edb42da99d6e344525cb0fcc78dd94d17c16d1576
6.6M	./f4
8.0K	./ea/ea2a9399d365a1e5f01829dcc49030e4e6ec6b686247141f11dd1da015a7cbea
12K	./ea
8.0K	./dc/dc1764cdb8928c75a9cd1e4583a9f8e591a323ecc30cf99de5fe356e94552cee
12K	./dc
49M	./4d/4d2e9ae40c411dd421f35dd20c133152bed21f8f9b903ba265a5d77c69a79edc
49M	./4d
18M	./70/70c3450b82875ff61c4a9bd662efcb8a8fa2fc3b61213962d7a0787ebd70cecf
18M	./70
182M	.
root@8fe6d4479136:/tmp/registry-dev/docker/registry/v2/blobs/sha256# du -h | wc -l
27
```

#### 2.2 Push image again(registry:latest)
Host:
```
[root@localhost xcb]# docker push 127.0.0.1:5200/registry:latest
The push refers to a repository [127.0.0.1:5200/registry] (len: 1)
f9684be4155a: Image already exists 
f9684be4155a: Image already exists 
6df65975f079: Image already exists 
10afac01c05b: Image already exists 
98cc4694054b: Image already exists 
e6c388bc67fb: Image already exists 
66780839eff4: Image already exists 
6a192b88c36f: Image already exists 
aeb43bf230e4: Image already exists 
124e2127157f: Image already exists 
69c177f0c117: Image already exists 
141b650c3281: Image already exists 
8fb45e60e014: Image already exists 
63e9d2557cd7: Image already exists 
b279b4aae826: Image already exists 
d86979befb72: Image already exists 
8ddc08289e1a: Image already exists 
8d38711ccc0d: Image already exists 
0f5121dd42a6: Image already exists 
607e965985c1: Image already exists 
1ff9f26f09fb: Image already exists 
9a61b6b1315e: Image already exists 
Digest: sha256:eee530e672a0106fddea284d2b8d5cb7325f542da41eebdaac24674f8406421d
```
Registry Container:
```
root@8fe6d4479136:/tmp/registry-dev/docker/registry/v2/blobs/sha256# du -h        
52K	./ee/eee530e672a0106fddea284d2b8d5cb7325f542da41eebdaac24674f8406421d
56K	./ee
11M	./ba/bad54a5c2ae3392a1a6224d8ab5a5400fe79b983fe423a98a56981595f2ee6c9
11M	./ba
8.0K	./53/533fcaf91b8be0a663c977d5e41f0bd161d49650793aa83da7ca00ae2071c464
12K	./53
8.0K	./dd/ddf532273b60e90431d7630711d2a31b1ab73424d88c4569fd6c793a173cdae0
12K	./dd
24M	./44/44590cce7a4f3d85cc2a5ec978512b469bd9b873f5e9c2acaa80181277276edc
24M	./44
41M	./c3/c33eb106dfcf81f8ecefeb8890e1c4cbddd97a27bb31ea49894f949a5243c4ab
41M	./c3
31M	./f9/f9a0522cbaa228af3def597b0790db18c802aba4a2b7e1c4a1054fed0dfdc41a
31M	./f9
8.0K	./a3/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
12K	./a3
3.1M	./25/259e85cb2eba63b0813396e884f16c18163c0b72edbef84dbdbb4f14cc60bb14
3.1M	./25
6.6M	./f4/f4fd525d70fd60cabafc2d2edb42da99d6e344525cb0fcc78dd94d17c16d1576
6.6M	./f4
8.0K	./ea/ea2a9399d365a1e5f01829dcc49030e4e6ec6b686247141f11dd1da015a7cbea
12K	./ea
8.0K	./dc/dc1764cdb8928c75a9cd1e4583a9f8e591a323ecc30cf99de5fe356e94552cee
12K	./dc
49M	./4d/4d2e9ae40c411dd421f35dd20c133152bed21f8f9b903ba265a5d77c69a79edc
49M	./4d
18M	./70/70c3450b82875ff61c4a9bd662efcb8a8fa2fc3b61213962d7a0787ebd70cecf
18M	./70
182M	.
root@8fe6d4479136:/tmp/registry-dev/docker/registry/v2/blobs/sha256# du -h | wc -l
29
```

We can find that one layer has been saved in registry( (29-27)/2 )
##### Question2: Why added one layer when pushing the same image?

#### 2.3 Push image(registry2:latest same as registry:latest)
Host:
```
[root@localhost xcb]# docker tag f9684be4155a 127.0.0.1:5200/registry2:latest
[root@localhost xcb]# docker push 127.0.0.1:5200/registry2:latest
The push refers to a repository [127.0.0.1:5200/registry2] (len: 1)
f9684be4155a: Image already exists 
f9684be4155a: Buffering to Disk 
6df65975f079: Image already exists 
98cc4694054b: Image successfully pushed 
e6c388bc67fb: Image successfully pushed 
e6c388bc67fb: Buffering to Disk 
66780839eff4: Image already exists 
6a192b88c36f: Image already exists 
124e2127157f: Image successfully pushed 
124e2127157f: Buffering to Disk 
69c177f0c117: Image already exists 
141b650c3281: Image already exists 
63e9d2557cd7: Image successfully pushed 
63e9d2557cd7: Buffering to Disk 
d86979befb72: Image successfully pushed 
8ddc08289e1a: Image successfully pushed 
8ddc08289e1a: Buffering to Disk 
0f5121dd42a6: Image successfully pushed 
607e965985c1: Image successfully pushed 
1ff9f26f09fb: Image successfully pushed 
1ff9f26f09fb: Buffering to Disk 
902b87aaaec9: Image successfully pushed 
Digest: sha256:555a369757825dc8c02dccd6484ad0a653556494b59b96b6c0113135744af030
```
##### Question3: Why some layers are exists and another are not?

Registry Container:
```
root@8fe6d4479136:/tmp/registry-dev/docker/registry/v2/blobs/sha256# du -h        
18M	./be/be6ccd7e478c1b1750c123b4bc8ac7f13f1254bb507f785685bca903daaae86c
18M	./be
52K	./ee/eee530e672a0106fddea284d2b8d5cb7325f542da41eebdaac24674f8406421d
56K	./ee
11M	./ba/bad54a5c2ae3392a1a6224d8ab5a5400fe79b983fe423a98a56981595f2ee6c9
11M	./ba
8.0K	./95/95444a2413c1ef715eb0340a31d9396559293f4e6a8ff4b153282bafa454aaa9
12K	./95
8.0K	./53/533fcaf91b8be0a663c977d5e41f0bd161d49650793aa83da7ca00ae2071c464
12K	./53
8.0K	./dd/ddf532273b60e90431d7630711d2a31b1ab73424d88c4569fd6c793a173cdae0
12K	./dd
52K	./55/555a369757825dc8c02dccd6484ad0a653556494b59b96b6c0113135744af030
56K	./55
24M	./44/44590cce7a4f3d85cc2a5ec978512b469bd9b873f5e9c2acaa80181277276edc
24M	./44
41M	./c3/c33eb106dfcf81f8ecefeb8890e1c4cbddd97a27bb31ea49894f949a5243c4ab
41M	./c3
31M	./f9/f9a0522cbaa228af3def597b0790db18c802aba4a2b7e1c4a1054fed0dfdc41a
31M	./f9
8.0K	./a3/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
12K	./a3
3.1M	./25/259e85cb2eba63b0813396e884f16c18163c0b72edbef84dbdbb4f14cc60bb14
3.1M	./25
6.6M	./f4/f4fd525d70fd60cabafc2d2edb42da99d6e344525cb0fcc78dd94d17c16d1576
6.6M	./f4
8.0K	./ea/ea2a9399d365a1e5f01829dcc49030e4e6ec6b686247141f11dd1da015a7cbea
12K	./ea
8.0K	./dc/dc1764cdb8928c75a9cd1e4583a9f8e591a323ecc30cf99de5fe356e94552cee
12K	./dc
49M	./4d/4d2e9ae40c411dd421f35dd20c133152bed21f8f9b903ba265a5d77c69a79edc
49M	./4d
18M	./70/70c3450b82875ff61c4a9bd662efcb8a8fa2fc3b61213962d7a0787ebd70cecf
18M	./70
200M	.
root@8fe6d4479136:/tmp/registry-dev/docker/registry/v2/blobs/sha256# du -h | wc -l
35

root@8fe6d4479136:/tmp/registry-dev/docker/registry/v2/blobs/sha256# du -h | grep 18M 
18M	./be/be6ccd7e478c1b1750c123b4bc8ac7f13f1254bb507f785685bca903daaae86c
18M	./be
18M	./70/70c3450b82875ff61c4a9bd662efcb8a8fa2fc3b61213962d7a0787ebd70cecf
18M	./70
```
We can find that three layers have been saved in registry( (35-29)/2 ), such as have two 18M layers
##### Question4: Why?


#### 3. Some Analysis

I find that `check layers exists` in docker(https://github.com/docker/docker/blob/master/graph/push_v2.go#L144) using the interface `HEAD /v2/<name>/blobs/<digest>`. This will lead to:
If push the images(have same layers) with differeent reponame, the interface will return `Not exists` when push layers.
##### Why layer digest bind to reponame(check layer exists)?
#####  Also, Why the same layer have different sha256 when pushing?

**Comment by jimmyxian** [comment] 2015-07-27 06:54
Maybe we can find something meaningful in https://github.com/docker/distribution/issues/634

**Comment by oilbeater** [comment] 2015-07-27 07:45
@jimmyxian 

I did some simple test, and find something interesting. When pushing an image to a new registry,the status of pushing first layer changes from "buffer to disk" to "Image successfully pushed" and then to "Image already exists".

I think the finally status is wrong,it should stop at "Image successfully pushed". But after go through the code, I still cannot find how this comes. From the code logical, there should not be an "Image already exists" status.

**Comment by aaronlehmann** [comment] 2015-07-27 21:03
I went through a very similar series of steps a few days ago when I was investigating a separate issue, and asked myself the same questions. Here are my conclusions.

> Question1: why first layer already exists ?

It doesn't already exist, and the output that says it exists is misleading. This is a bug on the client side. It sometimes sends a HEAD request to see if a layer exists, gets a 404, then uploads the layer and sends another HEAD request. When the second HEAD request returns 200, it claims that the image already exists, even though it was just uploaded. For example:

    172.17.42.1 - - [27/Jul/2015:20:39:02 +0000] "HEAD /v2/my/repo5005/blobs/sha256:ddf532273b60e90431d7630711d2a31b1ab73424d88c4569fd6c793a173cdae0 HTTP/1.1" 404 157 "" "docker/1.7.0 go/go1.4.2 git-commit/0baf609 kernel/4.0.5-boot2docker os/linux arch/amd64"
    172.17.42.1 - - [27/Jul/2015:20:39:02 +0000] "POST /v2/my/repo5005/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/1.7.0 go/go1.4.2 git-commit/0baf609 kernel/4.0.5-boot2docker os/linux arch/amd64"
    172.17.42.1 - - [27/Jul/2015:20:39:02 +0000] "PUT /v2/my/repo5005/blobs/uploads/a940830f-a13e-419f-8779-0341f255d172?_state=b3v4eOLv7FfsO_qrInr52KIcEMl9dWohn7ECDbFocAl7Ik5hbWUiOiJteS9yZXBvNTAwNSIsIlVVSUQiOiJhOTQwODMwZi1hMTNlLTQxOWYtODc3OS0wMzQxZjI1NWQxNzIiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTUtMDctMjdUMjA6Mzk6MDIuMjc3NjYwMDM5WiJ9&digest=sha256%3Addf532273b60e90431d7630711d2a31b1ab73424d88c4569fd6c793a173cdae0 HTTP/1.1" 201 0 "" "docker/1.7.0 go/go1.4.2 git-commit/0baf609 kernel/4.0.5-boot2docker os/linux arch/amd64"
    172.17.42.1 - - [27/Jul/2015:20:39:02 +0000] "HEAD /v2/my/repo5005/blobs/sha256:ddf532273b60e90431d7630711d2a31b1ab73424d88c4569fd6c793a173cdae0 HTTP/1.1" 200 0 "" "docker/1.7.0 go/go1.4.2 git-commit/0baf609 kernel/4.0.5-boot2docker os/linux arch/amd64"

So I think this is a legitimate bug.

> Question2: Why added one layer when pushing the same image?

I believe the new blob is the manifest file for the new repository. Since it contains the repository name, it's not identical to the old manifest.

> Question3: Why some layers are exists and others are not?

See answer to question 1. All the layers are pushed, but for some the client wrongly reports that they already exist.

> Question4: We can find that three layers have been saved in registry( (35-29)/2 ), such as have two 18M layers Why?

This could be an issue with tar files being reconstructed with minor differences, so that their digests aren't the same. As of a few days ago, the Docker engine's master branch has code that should prevent this from happening. I'd suggest trying the docker/docker master branch to see if it resolves this particular issue.

**Comment by jimmyxian** [comment] 2015-07-29 03:11
@aaronlehmann Thanks for your quick reply. I have tried the docker master, it's ok, solved by https://github.com/docker/docker/pull/14067

**Comment by dmp42** [comment] 2015-07-29 04:29
Should this be closed as fixed?

**Comment by jimmyxian** [comment] 2015-07-29 06:47
@dmp42 Yeah, should be closed, thanks

**Closed** 2015-07-29 15:30 UTC
Labels: question
