### ISSUE TITLE
Push to swift storage fails to upload manifest with a 404

### ISSUE THREAD

**Issue by lynxnot** [docker/distribution#757] opened 2015-07-27 09:38 UTC
Hello,

i have tested the brand new Openstack Swift storage driver (#493) against our Ceph Swift cluster, and images are failing to upload with a 404 on the manifest file. 

The storage configuration used is the following : 

```
storage:
    cache:
        blobdescriptor: inmemory
    swift:
        username: ticloud
        password: <THE_PASS>
        authurl: http://172.16.1.5/v2.0
        tenant: ticloud
        insecureskipverify: true
        region: chgva-01
        container: docker-registry
        rootdirectory: 
    maintenance:
        uploadpurging:
            enabled: false
```

The operation for the test :
```
docker tag golang:1.4 localhost:443/ticloud/golang:1.4
docker push localhost:443/ticloud/golang:1.4
```

The error logs :

```
time="2015-07-27T08:25:32.244845786Z" level=error msg="An error occured" err.code="BLOB_UNKNOWN" err.detail=sha256:4d2e9ae40c411dd421f35dd20c133152bed21f8f9b903ba265a5d77c69a79edc err.message="blob unknown to registry" http.request.host="localhost:443" http.request.id=3b3244d5-62bd-432e-9200-9dc000df6f1c http.request.method=PUT http.request.remoteaddr="172.17.42.1:59009" http.request.uri="/v2/ticloud/golang/manifests/1.4" http.request.useragent="docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.13.0-58-generic os/linux arch/amd64" vars.name="ticloud/golang" vars.reference=1.4 
time="2015-07-27T08:25:32.245177622Z" level=info msg="response completed" http.request.host="localhost:443" http.request.id=3b3244d5-62bd-432e-9200-9dc000df6f1c http.request.method=PUT http.request.remoteaddr="172.17.42.1:59009" http.request.uri="/v2/ticloud/golang/manifests/1.4" http.request.useragent="docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.13.0-58-generic os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=139.517898ms http.response.status=404 http.response.written=2173 
172.17.42.1 - - [27/Jul/2015:08:25:32 +0000] "PUT /v2/ticloud/golang/manifests/1.4 HTTP/1.1" 404 2173 "" "docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.13.0-58-generic os/linux arch/amd64"
```

All previous layers of the image seems to upload fine. The error is preceded by numerous BLOB_UNKNOWN errors. The full trace it's [here](http://pastebin.com/MMLyntTW)

If needed the listing of the swift container after this operation has been uploaded [here](http://pastebin.com/KF5W810m)

I will keep the infrastructure as is, so let me know if i can help more, just bear in mind im not a go dev :)

**Comment by RichardScothern** [comment] 2015-07-27 17:02
@lebauce : any ideas?

**Comment by lebauce** [comment] 2015-07-28 08:47
@RichardScothern @fandav73 I'm taking a look

**Comment by lebauce** [comment] 2015-07-28 09:26
@fandav73 What version of Swift are you using ?

Also, that would be nice if you could join the distribution IRC to talk about it.

**Comment by fandav73** [comment] 2015-07-28 09:43
@lebauce We are using Ceph and radosgw to provide the swift API, the version is 0.94.2 (hammer).
The radosgw is integrated with keystone and we are using API V2 for auth.

The differences in the swift API between Ceph and Openstack are documented [here](http://ceph.com/docs/master/radosgw/swift/)  

I'm also on the IRC channel if you need anything else.

**Comment by lebauce** [comment] 2015-07-29 15:07
Some update on the bug.
Openstack Swift and Ceph Swift treat the `delimiter` parameter differently :

If I have a `test` container with a file `a/b/c`.

With Openstack Swift, if I run "swift list --prefix=a/b/c --delimiter=/", I get an the [`a/b/c`]
With Ceph RadosGW, I get an empty array.

**Comment by RichardScothern** [comment] 2015-09-03 23:27
@fandav73 : is this still an issue?  @lebauce  did you get anywhere?

**Comment by lebauce** [comment] 2015-09-04 21:22
@RichardScothern I filed a bug on Ceph and submitted a patch (http://tracker.ceph.com/issues/12960).
If we're very lucky, it may be part of the next 0.94.4 Hammer release.

**Comment by lebauce** [comment] 2015-09-09 19:16
The commit was just merged into Ceph master branch. I submitted an other PR to the `hammer` stable branch. If it's accepted, the next release of Hammer packages will contain the fix.

**Comment by fandav73** [comment] 2015-09-17 11:11
@lebauce Thanks for your work! @RichardScothern We have actually switched to the file system driver. I will try again when the Ceph fix will be released.

**Comment by dmp42** [comment] 2015-10-19 23:05
@lebauce heads-up!
The next release is nearing, we need some action on the Ceph front :-)

**Comment by lebauce** [comment] 2015-10-20 20:32
@dmp42 The 0.94.4 have just been released and they contain the fix. :tada: (http://tracker.ceph.com/issues/12701)

@fandav73 Any chance that you give the new packages a try ?

**Comment by RichardScothern** [comment] 2015-10-21 17:07
thanks @lebauce :cake:

**Comment by fandav73** [comment] 2015-10-29 16:38
@RichardScothern We just updated our infrastructure to the last Ceph version, next week ill have some time to give this a try.

**Comment by gschukin** [comment] 2015-11-27 13:32
Can we have workaround for older ceph versions since Firefly is an LTS release and some Openstack distros are built with it?

**Comment by lebauce** [comment] 2015-12-02 16:43
@gschukin I wanted to avoid it. But now that the problem is fixed upstream, I'm willing to reconsider :-) I'll ping you

**Comment by dmp42** [comment] 2016-01-25 19:26
@RichardScothern @lebauce what's the status on this now?

**Comment by gschukin** [comment] 2016-03-03 11:55
@lebauce it seems that ceph support will be broken anyway. Curently ceph incorrectly caculates etag for DLO manifest. And it also doesn't support SLO.

**Comment by RichardScothern** [comment] 2016-06-14 00:46
@fandav73 is this still an issue for you?  The swift driver has had a couple of ceph related fixes of late.

**Comment by RichardScothern** [comment] 2016-08-19 19:03
closing

**Closed by RichardScothern** 2016-08-19 19:03 UTC
Labels: bug
