### ISSUE TITLE
Pull Through Cache For Private Registry

### ISSUE THREAD

**Issue by songkamongkol** [docker/distribution#922] opened 2015-08-25 23:03 UTC
I followed instruction on how to setup [Pull Through Cache] (https://github.com/docker/distribution/blob/master/docs/mirror.md) but it turned out that pull through cache is not yet supported for private registry yet. I think the documentation needs to be updated as this restriction is not mentioned anywhere. I also think that it would be nice to be able to have a pull through cache that can proxy a private registry and not just Docker hub.

**Comment by rhardih** [comment] 2015-08-27 12:13
Second the request for being able to run a pull through cache for private registries. +1

**Comment by bwalsh** [comment] 2015-09-16 00:47
+1 this would be incredibly useful

**Comment by dmp42** [comment] 2015-09-16 01:33
Thanks for the feedback here. We are certainly considering this feature (btw the registry itself supports it, but not the docker engine), though this has to be carefully thought through, specifically wrt signed images.

That being said, I would love to hear more about the use-cases where caching of other private registries would be used.

Given its current design, the registry is meant to leverage backend storage scalability and availability. For example, if you were to delegate delivery to either your storage, or a CDN like CloudFront on top of it, wouldn't that give you basically the same benefits?

Thanks.

**Comment by songkamongkol** [comment] 2015-09-16 02:20
Hi Olivier,

For my case, we are hosting a private docker registry in AWS and we have development team in several sites around the world.

Having a docker pull through cache would help reduce the time each engineer spend trying to pull down the image from the AWS cloud to their local site (basically, all engineer at one site will share the same cache so if an image is already pulled, it will be served directly from the local cache).

Thanks,

--Somboon

**Comment by bwalsh** [comment] 2015-09-21 00:16
We use docker to store images for production use.  The central docker registry services client registries and associated clusters, all behind the firewall.  The pull through cache will simplify configuration and remove the need for a 'synchronizer'.  

Much Appreciated.

**Comment by rhardih** [comment] 2015-09-21 14:54
I've run into a similar use case, where it'd be really handy from a performance standpoint, to have an in-office cache of the registry in order to speed up fetches from a primary registry. Nothing really beats local network speeds.

**Comment by dmp42** [comment] 2015-09-21 18:14
Thanks all for the feedback.

I believe the registry itself supports caching other private registries (calling @RichardScothern to confirm), but it's the docker engine that won't let you do that for now.

It's definitely worth looking into for the future though - will have to be done carefully, wrt notary and image signing.

**Comment by RichardScothern** [comment] 2015-09-22 16:55
As @dmp42 says, this is a restriction within the Docker engine.  There is an intention to have this features, so I will leave this open.

Also, lease don't +1 issues - it just creates unnecessary noise.  You can subscribe (button above) to get notifications.

**Comment by saiwl** [comment] 2015-12-28 08:00
Dose registry support caching private registry with self-made CA, just like the --insecure-registry option in docker engine? I modifies the docker engine for testing, to make registry cache private registry, the private registry has a self-made CA, so the log shows below:
x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs
I guess it's caused by self-made CA.
Dose registry support this?
thank you!

**Comment by RichardScothern** [comment] 2016-01-04 19:14
@saiwl : Your self-signed certificate must contain a domain name.

**Comment by stevvooe** [comment] 2016-01-12 20:39
@saiwl That seems completely unrelated to this issue. Please do not hijack issues. It is impolite to others trying to understand an issue and confusing for the maintainers.

**Comment by stevvooe** [comment] 2016-01-12 20:40
The restriction is mentioned [here](https://github.com/docker/distribution/blob/master/docs/mirror.md#gotcha). I'm closing for now, but if this is insufficient, please let us know or submit a PR.

**Closed by stevvooe** 2016-01-12 20:40 UTC

**Comment by songkamongkol** [comment] 2016-01-12 20:46
@stevvooe I see that you closed this issue. Does this mean that pull-through cache for private docker registry will not be supported?

**Comment by stevvooe** [comment] 2016-01-12 22:36
I understood this was a documentation issue, rather than a feature request:

>  I think the documentation needs to be updated as this restriction is not mentioned anywhere. I also think that it would be nice to be able to have a pull through cache that can proxy a private registry and not just Docker hub.

We know this feature is desired and want to get it in. The feature request is already covered in the [ROADMAP](https://github.com/docker/distribution/blob/master/ROADMAP.md#proxying-to-other-registries) but has other dependencies. Having this issue open and getting notifications on it won't really add value.

**Comment by tehlers320** [comment] 2016-06-17 02:30
Is this back on the road map?
